/*
 Creative Commons Attribution License 3.0 (http://creativecommons.org/licenses/by/3.0/)

 @contributions Chris Leonello
 @comment Bug fix to 12 hour time and additions to handle milliseconds and
 @comment 24 hour time without am/pm suffix

*/
(function(e){function y(a){e.jqplot.ElemContainer.call(this);this.name=a;this._series=[];this.show=!1;this.tickRenderer=e.jqplot.AxisTickRenderer;this.tickOptions={};this.labelRenderer=e.jqplot.AxisLabelRenderer;this.labelOptions={};this.label=null;this.showLabel=!0;this.max=this.min=null;this.autoscale=!1;this.pad=1.2;this.padMin=this.padMax=null;this.ticks=[];this.numberTicks;this.tickInterval;this.renderer=e.jqplot.LinearAxisRenderer;this.rendererOptions={};this.showMinorTicks=this.showTickMarks=
this.showTicks=!0;this.useSeriesColor=!1;this.borderColor=this.borderWidth=null;this._dataBounds={min:null,max:null};this._offsets={min:null,max:null};this._ticks=[];this.syncTicks=this._label=null;this.tickSpacing=75;this.__ticks=this._numberTicks=this._tickInterval=this._max=this._min=null}function B(a){e.jqplot.ElemContainer.call(this);this.show=!1;this.location="ne";this.labels=[];this.showSwatches=this.showLabels=!0;this.placement="insideGrid";this.yoffset=this.xoffset=0;this.border;this.background;
this.textColor;this.fontFamily;this.fontSize;this.rowSpacing="0.5em";this.renderer=e.jqplot.TableLegendRenderer;this.rendererOptions={};this.preDraw=!1;this.marginLeft=this.marginBottom=this.marginRight=this.marginTop=null;this.escapeHtml=!1;this._series=[];e.extend(!0,this,a)}function D(a){e.jqplot.ElemContainer.call(this);this.text=a;this.show=!0;this.fontFamily;this.fontSize;this.textAlign;this.textColor;this.renderer=e.jqplot.DivTitleRenderer;this.rendererOptions={}}function C(){e.jqplot.ElemContainer.call(this);
this.show=!0;this.xaxis="xaxis";this._xaxis;this.yaxis="yaxis";this._yaxis;this.gridBorderWidth=2;this.renderer=e.jqplot.LineRenderer;this.rendererOptions={};this.data=[];this.gridData=[];this.label="";this.showLabel=!0;this.color;this.lineWidth=2.5;this.shadow=!0;this.shadowAngle=45;this.shadowOffset=1.25;this.shadowDepth=3;this.shadowAlpha="0.1";this.breakOnNull=!1;this.markerRenderer=e.jqplot.MarkerRenderer;this.markerOptions={};this.showMarker=this.showLine=!0;this.index;this.fill=!1;this.fillColor;
this.fillAlpha;this._stack=this.disableStack=this.fillAndStroke=!1;this.neighborThreshold=4;this.fillToZero=!1;this.fillToValue=0;this.fillAxis="y";this.useNegativeColors=!0;this._stackData=[];this._plotData=[];this._plotValues={x:[],y:[]};this._intervals={x:{},y:{}};this._prevPlotData=[];this._prevGridData=[];this._stackAxis="y";this._primaryAxis="_xaxis";this.canvas=new e.jqplot.GenericCanvas;this.shadowCanvas=new e.jqplot.GenericCanvas;this.plugins={};this._sumx=this._sumy=0}function E(){e.jqplot.ElemContainer.call(this);
this.drawGridlines=!0;this.gridLineColor="#cccccc";this.gridLineWidth=1;this.background="#fffdf6";this.borderColor="#999999";this.borderWidth=2;this.shadow=this.drawBorder=!0;this.shadowAngle=45;this.shadowOffset=1.5;this.shadowDepth=this.shadowWidth=3;this.shadowColor=null;this.shadowAlpha="0.07";this._left;this._top;this._right;this._bottom;this._width;this._height;this._axes=[];this.renderer=e.jqplot.CanvasGridRenderer;this.rendererOptions={};this._offsets={top:null,bottom:null,left:null,right:null}}
function M(){function a(a){for(var b,c=0;c<a.length;c++)for(var d,e=[a[c].data,a[c]._stackData,a[c]._plotData,a[c]._prevPlotData],f=0;4>f;f++)if(d=!0,b=e[f],"x"==a[c]._stackAxis){for(var g=0;g<b.length;g++)if("number"!=typeof b[g][1]){d=!1;break}d&&b.sort(function(a,b){return a[1]-b[1]})}else{for(g=0;g<b.length;g++)if("number"!=typeof b[g][0]){d=!1;break}d&&b.sort(function(a,b){return a[0]-b[0]})}}function b(a){var b=a.data.plot,c=b.eventCanvas._elem.offset();a={x:a.pageX-c.left,y:a.pageY-c.top};
var d={xaxis:null,yaxis:null,x2axis:null,y2axis:null,y3axis:null,y4axis:null,y5axis:null,y6axis:null,y7axis:null,y8axis:null,y9axis:null},e="xaxis yaxis x2axis y2axis y3axis y4axis y5axis y6axis y7axis y8axis y9axis".split(" "),b=b.axes,f,g;for(f=11;0<f;f--)g=e[f-1],b[g].show&&(d[g]=b[g].series_p2u(a[g.charAt(0)]));return{offsets:c,gridPos:a,dataPos:d}}function d(a,b){var c=b.series,d,h,f,g,q,l,r,u,y,w,v,x;for(f=b.seriesStack.length-1;0<=f;f--)switch(d=b.seriesStack[f],g=c[d],g.renderer.constructor){case e.jqplot.BarRenderer:l=
a.x;r=a.y;for(h=g.gridData.length-1;0<=h;h--)if(d=g._barPoints[h],l>d[0][0]&&l<d[2][0]&&r>d[2][1]&&r<d[0][1])return{seriesIndex:g.index,pointIndex:h,gridData:v,data:g.data[h],points:g._barPoints[h]};break;case e.jqplot.DonutRenderer:h=g.startAngle/180*Math.PI;l=a.x-g._center[0];r=a.y-g._center[1];q=Math.sqrt(Math.pow(l,2)+Math.pow(r,2));0<l&&0<=-r?u=2*Math.PI-Math.atan(-r/l):0<l&&0>-r?u=-Math.atan(-r/l):0>l?u=Math.PI-Math.atan(-r/l):0==l&&0<-r?u=3*Math.PI/2:0==l&&0>-r?u=Math.PI/2:0==l&&0==r&&(u=0);
h&&(u-=h,0>u?u+=2*Math.PI:u>2*Math.PI&&(u-=2*Math.PI));l=g.sliceMargin/180*Math.PI;if(q<g._radius&&q>g._innerRadius)for(h=0;h<g.gridData.length;h++)if(r=0<h?g.gridData[h-1][1]+l:l,d=g.gridData[h][1],u>r&&u<d)return{seriesIndex:g.index,pointIndex:h,gridData:g.gridData[h],data:g.data[h]};break;case e.jqplot.PieRenderer:h=g.startAngle/180*Math.PI;l=a.x-g._center[0];r=a.y-g._center[1];q=Math.sqrt(Math.pow(l,2)+Math.pow(r,2));0<l&&0<=-r?u=2*Math.PI-Math.atan(-r/l):0<l&&0>-r?u=-Math.atan(-r/l):0>l?u=Math.PI-
Math.atan(-r/l):0==l&&0<-r?u=3*Math.PI/2:0==l&&0>-r?u=Math.PI/2:0==l&&0==r&&(u=0);h&&(u-=h,0>u?u+=2*Math.PI:u>2*Math.PI&&(u-=2*Math.PI));l=g.sliceMargin/180*Math.PI;if(q<g._radius)for(h=0;h<g.gridData.length;h++)if(r=0<h?g.gridData[h-1][1]+l:l,d=g.gridData[h][1],u>r&&u<d)return{seriesIndex:g.index,pointIndex:h,gridData:g.gridData[h],data:g.data[h]};break;case e.jqplot.BubbleRenderer:l=a.x;r=a.y;q=null;if(g.show){for(h=0;h<g.gridData.length;h++)if(v=g.gridData[h],w=Math.sqrt((l-v[0])*(l-v[0])+(r-v[1])*
(r-v[1])),w<=v[2]&&(w<=y||null==y))y=w,q={seriesIndex:d,pointIndex:h,gridData:v,data:g.data[h]};if(null!=q)return q}break;case e.jqplot.FunnelRenderer:l=a.x;r=a.y;d=g._vertices;h=d[0];w=d[d.length-1];x=function(a,b,c){c=(b[1]-c[1])/(b[0]-c[0]);a+=b[1];return[(a-(b[1]-c*b[0]))/c,a]};q=x(r,h[0],w[3]);w=x(r,h[1],w[2]);for(h=0;h<d.length;h++)if(cv=d[h],r>=cv[0][1]&&r<=cv[3][1]&&l>=q[0]&&l<=w[0])return{seriesIndex:g.index,pointIndex:h,gridData:null,data:g.data[h]};break;case e.jqplot.LineRenderer:l=a.x;
r=a.y;q=g.renderer;if(g.show)if(g.fill){q=!1;if(l>g._boundingBox[0][0]&&l<g._boundingBox[1][0]&&r>g._boundingBox[1][1]&&r<g._boundingBox[0][1]){w=g._areaPoints.length;h=w-1;for(x=0;x<w;x++){var z=[g._areaPoints[x][0],g._areaPoints[x][1]];h=[g._areaPoints[h][0],g._areaPoints[h][1]];if(z[1]<r&&h[1]>=r||h[1]<r&&z[1]>=r)z[0]+(r-z[1])/(h[1]-z[1])*(h[0]-z[0])<l&&(q=!q);h=x}}if(q)return{seriesIndex:d,pointIndex:null,gridData:g.gridData,data:g.data,points:g._areaPoints};break}else{h=g.markerRenderer.size/
2+g.neighborThreshold;x=0<h?h:0;for(h=0;h<g.gridData.length;h++)if(v=g.gridData[h],q.constructor==e.jqplot.OHLCRenderer)if(q.candleStick){if(w=g._yaxis.series_u2p,l>=v[0]-q._bodyWidth/2&&l<=v[0]+q._bodyWidth/2&&r>=w(g.data[h][2])&&r<=w(g.data[h][3]))return{seriesIndex:d,pointIndex:h,gridData:v,data:g.data[h]}}else if(q.hlc){if(w=g._yaxis.series_u2p,l>=v[0]-q._tickLength&&l<=v[0]+q._tickLength&&r>=w(g.data[h][1])&&r<=w(g.data[h][2]))return{seriesIndex:d,pointIndex:h,gridData:v,data:g.data[h]}}else{if(w=
g._yaxis.series_u2p,l>=v[0]-q._tickLength&&l<=v[0]+q._tickLength&&r>=w(g.data[h][2])&&r<=w(g.data[h][3]))return{seriesIndex:d,pointIndex:h,gridData:v,data:g.data[h]}}else if(null!=v[0]&&null!=v[1]&&(w=Math.sqrt((l-v[0])*(l-v[0])+(r-v[1])*(r-v[1])),w<=x&&(w<=y||null==y)))return y=w,{seriesIndex:d,pointIndex:h,gridData:v,data:g.data[h]}}break;default:if(l=a.x,r=a.y,q=g.renderer,g.show){h=g.markerRenderer.size/2+g.neighborThreshold;x=0<h?h:0;for(h=0;h<g.gridData.length;h++)if(v=g.gridData[h],q.constructor==
e.jqplot.OHLCRenderer)if(q.candleStick){if(w=g._yaxis.series_u2p,l>=v[0]-q._bodyWidth/2&&l<=v[0]+q._bodyWidth/2&&r>=w(g.data[h][2])&&r<=w(g.data[h][3]))return{seriesIndex:d,pointIndex:h,gridData:v,data:g.data[h]}}else if(q.hlc){if(w=g._yaxis.series_u2p,l>=v[0]-q._tickLength&&l<=v[0]+q._tickLength&&r>=w(g.data[h][1])&&r<=w(g.data[h][2]))return{seriesIndex:d,pointIndex:h,gridData:v,data:g.data[h]}}else{if(w=g._yaxis.series_u2p,l>=v[0]-q._tickLength&&l<=v[0]+q._tickLength&&r>=w(g.data[h][2])&&r<=w(g.data[h][3]))return{seriesIndex:d,
pointIndex:h,gridData:v,data:g.data[h]}}else if(w=Math.sqrt((l-v[0])*(l-v[0])+(r-v[1])*(r-v[1])),w<=x&&(w<=y||null==y))return y=w,{seriesIndex:d,pointIndex:h,gridData:v,data:g.data[h]}}}return null}this.data=[];this.dataRenderer;this.dataRendererOptions;this.target=this.targetId=null;this.defaults={axesDefaults:{},axes:{xaxis:{},yaxis:{},x2axis:{},y2axis:{},y3axis:{},y4axis:{},y5axis:{},y6axis:{},y7axis:{},y8axis:{},y9axis:{}},seriesDefaults:{},gridPadding:{top:10,right:10,bottom:23,left:10},series:[]};
this.series=[];this.axes={xaxis:new y("xaxis"),yaxis:new y("yaxis"),x2axis:new y("x2axis"),y2axis:new y("y2axis"),y3axis:new y("y3axis"),y4axis:new y("y4axis"),y5axis:new y("y5axis"),y6axis:new y("y6axis"),y7axis:new y("y7axis"),y8axis:new y("y8axis"),y9axis:new y("y9axis")};this.grid=new E;this.legend=new B;this.baseCanvas=new e.jqplot.GenericCanvas;this.seriesStack=[];this.previousSeriesStack=[];this.eventCanvas=new e.jqplot.GenericCanvas;this._height=this._width=null;this._plotDimensions={height:null,
width:null};this._gridPadding={top:0,right:0,bottom:0,left:0};this.syncYTicks=this.syncXTicks=!0;this.seriesColors="#579575 #4bb2c5 #EAA228 #c5b47f #839557 #958c12 #953579 #4b5de4 #d8b83f #ff5800 #0085cc #c747a3 #cddf54 #FBD178 #26B4E3 #bd70c7".split(" ");this.negativeSeriesColors="#498991 #C08840 #9F9274 #546D61 #646C4A #6F6621 #6E3F5F #4F64B0 #A89050 #C45923 #187399 #945381 #959E5C #C7AF7B #478396 #907294".split(" ");this.sortData=!0;this.textColor;this.fontFamily;this.fontSize;this.title=new D;
this.options={};this.stackSeries=!1;this.defaultAxisStart=1;this._stackData=[];this._plotData=[];this.plugins={};this._drawCount=0;this.captureRightClick=this.drawIfHidden=!1;this.themeEngine=new e.jqplot.ThemeEngine;this._sumx=this._sumy=0;this.preInitHooks=new e.jqplot.HooksManager;this.postInitHooks=new e.jqplot.HooksManager;this.preParseOptionsHooks=new e.jqplot.HooksManager;this.postParseOptionsHooks=new e.jqplot.HooksManager;this.preDrawHooks=new e.jqplot.HooksManager;this.postDrawHooks=new e.jqplot.HooksManager;
this.preDrawSeriesHooks=new e.jqplot.HooksManager;this.postDrawSeriesHooks=new e.jqplot.HooksManager;this.preDrawLegendHooks=new e.jqplot.HooksManager;this.addLegendRowHooks=new e.jqplot.HooksManager;this.preSeriesInitHooks=new e.jqplot.HooksManager;this.postSeriesInitHooks=new e.jqplot.HooksManager;this.preParseSeriesOptionsHooks=new e.jqplot.HooksManager;this.postParseSeriesOptionsHooks=new e.jqplot.HooksManager;this.eventListenerHooks=new e.jqplot.EventListenerManager;this.preDrawSeriesShadowHooks=
new e.jqplot.HooksManager;this.postDrawSeriesShadowHooks=new e.jqplot.HooksManager;this.colorGenerator=e.jqplot.ColorGenerator;this.init=function(b,c,d){for(var f=0;f<e.jqplot.preInitHooks.length;f++)e.jqplot.preInitHooks[f].call(this,b,c,d);for(f=0;f<this.preInitHooks.hooks.length;f++)this.preInitHooks.hooks[f].call(this,b,c,d);this.targetId="#"+b;this.target=e("#"+b);this.target.removeClass("jqplot-error");if(!this.target.get(0))throw"No plot target specified";"static"==this.target.css("position")&&
this.target.css("position","relative");this.target.hasClass("jqplot-target")||this.target.addClass("jqplot-target");this.target.height()?this._height=this.target.height():(this._height=f=d&&d.height?parseInt(d.height,10):this.target.attr("data-height")?parseInt(this.target.attr("data-height"),10):parseInt(e.jqplot.config.defaultHeight,10),this.target.css("height",f+"px"));this.target.width()?this._width=this.target.width():(this._width=f=d&&d.width?parseInt(d.width,10):this.target.attr("data-width")?
parseInt(this.target.attr("data-width"),10):parseInt(e.jqplot.config.defaultWidth,10),this.target.css("width",f+"px"));this._plotDimensions.height=this._height;this._plotDimensions.width=this._height;this.grid._plotDimensions=this._plotDimensions;this.title._plotDimensions=this._plotDimensions;this.baseCanvas._plotDimensions=this._plotDimensions;this.eventCanvas._plotDimensions=this._plotDimensions;this.legend._plotDimensions=this._plotDimensions;if(0>=this._height||0>=this._width||!this._height||
!this._width)throw"Canvas dimension not set";d.dataRenderer&&"function"==typeof d.dataRenderer&&(d.dataRendererOptions&&(this.dataRendererOptions=d.dataRendererOptions),this.dataRenderer=d.dataRenderer,c=this.dataRenderer(c,this,this.dataRendererOptions));if(null==c)throw{name:"DataError",message:"No data to plot."};if(c.constructor!=Array||0==c.length||c[0].constructor!=Array||0==c[0].length)throw{name:"DataError",message:"No data to plot."};this.data=c;this.parseOptions(d);this.textColor&&this.target.css("color",
this.textColor);this.fontFamily&&this.target.css("font-family",this.fontFamily);this.fontSize&&this.target.css("font-size",this.fontSize);this.title.init();this.legend.init();for(f=this._sumx=this._sumy=0;f<this.series.length;f++){this.seriesStack.push(f);this.previousSeriesStack.push(f);this.series[f].shadowCanvas._plotDimensions=this._plotDimensions;this.series[f].canvas._plotDimensions=this._plotDimensions;for(var h=0;h<e.jqplot.preSeriesInitHooks.length;h++)e.jqplot.preSeriesInitHooks[h].call(this.series[f],
b,c,this.options.seriesDefaults,this.options.series[f],this);for(h=0;h<this.preSeriesInitHooks.hooks.length;h++)this.preSeriesInitHooks.hooks[h].call(this.series[f],b,c,this.options.seriesDefaults,this.options.series[f],this);this.populatePlotData(this.series[f],f);this.series[f]._plotDimensions=this._plotDimensions;this.series[f].init(f,this.grid.borderWidth,this);for(h=0;h<e.jqplot.postSeriesInitHooks.length;h++)e.jqplot.postSeriesInitHooks[h].call(this.series[f],b,c,this.options.seriesDefaults,
this.options.series[f],this);for(h=0;h<this.postSeriesInitHooks.hooks.length;h++)this.postSeriesInitHooks.hooks[h].call(this.series[f],b,c,this.options.seriesDefaults,this.options.series[f],this);this._sumy+=this.series[f]._sumy;this._sumx+=this.series[f]._sumx}for(var p in this.axes)this.axes[p]._plotDimensions=this._plotDimensions,this.axes[p].init();this.sortData&&a(this.series);this.grid.init();this.grid._axes=this.axes;this.legend._series=this.series;for(f=0;f<e.jqplot.postInitHooks.length;f++)e.jqplot.postInitHooks[f].call(this,
b,c,d);for(f=0;f<this.postInitHooks.hooks.length;f++)this.postInitHooks.hooks[f].call(this,b,c,d)};this.resetAxesScale=function(a){a=a!=x?a:this.axes;!0===a&&(a=this.axes);if(a.constructor===Array)for(var b=0;b<a.length;b++)this.axes[a[b]].resetScale();else if(a.constructor===Object)for(b in a)this.axes[b].resetScale()};this.reInitialize=function(){if(this.target.height())this._height=this.target.height();else{var b;this._height=b=options&&options.height?parseInt(options.height,10):this.target.attr("data-height")?
parseInt(this.target.attr("data-height"),10):parseInt(e.jqplot.config.defaultHeight,10);this.target.css("height",b+"px")}this.target.width()?this._width=this.target.width():(this._width=b=options&&options.width?parseInt(options.width,10):this.target.attr("data-width")?parseInt(this.target.attr("data-width"),10):parseInt(e.jqplot.config.defaultWidth,10),this.target.css("width",b+"px"));if(0>=this._height||0>=this._width||!this._height||!this._width)throw"Target dimension not set";this._plotDimensions.height=
this._height;this._plotDimensions.width=this._width;this.grid._plotDimensions=this._plotDimensions;this.title._plotDimensions=this._plotDimensions;this.baseCanvas._plotDimensions=this._plotDimensions;this.eventCanvas._plotDimensions=this._plotDimensions;this.legend._plotDimensions=this._plotDimensions;for(var c in this.axes)this.axes[c]._plotWidth=this._width,this.axes[c]._plotHeight=this._height;this.title._plotWidth=this._width;this.textColor&&this.target.css("color",this.textColor);this.fontFamily&&
this.target.css("font-family",this.fontFamily);this.fontSize&&this.target.css("font-size",this.fontSize);for(c=this._sumx=this._sumy=0;c<this.series.length;c++)this.populatePlotData(this.series[c],c),this.series[c]._plotDimensions=this._plotDimensions,this.series[c].canvas._plotDimensions=this._plotDimensions,this._sumy+=this.series[c]._sumy,this._sumx+=this.series[c]._sumx;for(var d in this.axes)this.axes[d]._plotDimensions=this._plotDimensions,this.axes[d]._ticks=[],this.axes[d].renderer.init.call(this.axes[d],
{});this.sortData&&a(this.series);this.grid._axes=this.axes;this.legend._series=this.series};this.populatePlotData=function(a,b){this._plotData=[];this._stackData=[];a._stackData=[];a._plotData=[];var c={x:[],y:[]};if(this.stackSeries&&!a.disableStack){a._stack=!0;for(var d="x"==a._stackAxis?0:1,f=e.extend(!0,[],a.data),p=e.extend(!0,[],a.data),g=0;g<b;g++)for(var q=this.series[g].data,l=0;l<q.length;l++)f[l][0]+=q[l][0],f[l][1]+=q[l][1],p[l][d]+=q[l][d];for(d=0;d<p.length;d++)c.x.push(p[d][0]),c.y.push(p[d][1]);
this._plotData.push(p);this._stackData.push(f);a._stackData=f;a._plotData=p}else{for(d=0;d<a.data.length;d++)c.x.push(a.data[d][0]),c.y.push(a.data[d][1]);this._stackData.push(a.data);this.series[b]._stackData=a.data;this._plotData.push(a.data);a._plotData=a.data}a._plotValues=c;0<b&&(a._prevPlotData=this.series[b-1]._plotData);a._sumy=0;a._sumx=0;for(d=a.data.length-1;-1<d;d--)a._sumy+=a.data[d][1],a._sumx+=a.data[d][0]};var c=0,f=this.seriesColors;this.getNextSeriesColor=function(){c<f.length||
(c=0);return f[c++]};this.parseOptions=function(a){for(var b=0;b<this.preParseOptionsHooks.hooks.length;b++)this.preParseOptionsHooks.hooks[b].call(this,a);for(b=0;b<e.jqplot.preParseOptionsHooks.length;b++)e.jqplot.preParseOptionsHooks[b].call(this,a);this.options=e.extend(!0,{},this.defaults,a);this.stackSeries=this.options.stackSeries;this.options.seriesColors&&(this.seriesColors=this.options.seriesColors);this.options.negativeSeriesColors&&(this.negativeSeriesColors=this.options.negativeSeriesColors);
this.options.captureRightClick&&(this.captureRightClick=this.options.captureRightClick);this.defaultAxisStart=a&&null!=a.defaultAxisStart?a.defaultAxisStart:this.defaultAxisStart;var c=new this.colorGenerator(this.seriesColors);e.extend(!0,this._gridPadding,this.options.gridPadding);this.sortData=null!=this.options.sortData?this.options.sortData:this.sortData;for(var d in this.axes)b=this.axes[d],e.extend(!0,b,this.options.axesDefaults,this.options.axes[d]),b._plotWidth=this._width,b._plotHeight=
this._height;if(0==this.data.length){this.data=[];for(b=0;b<this.options.series.length;b++)this.data.push(this.options.series.data)}for(b=0;b<this.data.length;b++){for(var f=new C,p=0;p<e.jqplot.preParseSeriesOptionsHooks.length;p++)e.jqplot.preParseSeriesOptionsHooks[p].call(f,this.options.seriesDefaults,this.options.series[b]);for(p=0;p<this.preParseSeriesOptionsHooks.hooks.length;p++)this.preParseSeriesOptionsHooks.hooks[p].call(f,this.options.seriesDefaults,this.options.series[b]);e.extend(!0,
f,{seriesColors:this.seriesColors,negativeSeriesColors:this.negativeSeriesColors},this.options.seriesDefaults,this.options.series[b]);var g="vertical";f.renderer.constructor==e.jqplot.barRenderer&&(f.rendererOptions&&"horizontal"==f.rendererOptions.barDirection)&&(g="horizontal");var p=f,q=this.data[b],l=this.defaultAxisStart,r=[],u=void 0,g=g||"vertical";if(q[0]instanceof Array)e.extend(!0,r,q);else for(u=0;u<q.length;u++)"vertical"==g?r.push([l+u,q[u]]):r.push([q[u],l+u]);p.data=r;switch(f.xaxis){case "xaxis":f._xaxis=
this.axes.xaxis;break;case "x2axis":f._xaxis=this.axes.x2axis}f._yaxis=this.axes[f.yaxis];f._xaxis._series.push(f);f._yaxis._series.push(f);f.show&&(f._xaxis.show=!0,f._yaxis.show=!0);!f.color&&!1!=f.show&&(f.color=c.next());f.label||(f.label="Series "+(b+1).toString());this.series.push(f);for(p=0;p<e.jqplot.postParseSeriesOptionsHooks.length;p++)e.jqplot.postParseSeriesOptionsHooks[p].call(this.series[b],this.options.seriesDefaults,this.options.series[b]);for(p=0;p<this.postParseSeriesOptionsHooks.hooks.length;p++)this.postParseSeriesOptionsHooks.hooks[p].call(this.series[b],
this.options.seriesDefaults,this.options.series[b])}e.extend(!0,this.grid,this.options.grid);for(d in this.axes)b=this.axes[d],null==b.borderWidth&&(b.borderWidth=this.grid.borderWidth),null==b.borderColor&&(b.borderColor="xaxis"!=d&&"x2axis"!=d&&!0===b.useSeriesColor&&b.show?b._series[0].color:this.grid.borderColor);"string"==typeof this.options.title?this.title.text=this.options.title:"object"==typeof this.options.title&&e.extend(!0,this.title,this.options.title);this.title._plotWidth=this._width;
this.legend.setOptions(this.options.legend);for(b=0;b<e.jqplot.postParseOptionsHooks.length;b++)e.jqplot.postParseOptionsHooks[b].call(this,a);for(b=0;b<this.postParseOptionsHooks.hooks.length;b++)this.postParseOptionsHooks.hooks[b].call(this,a)};this.replot=function(a){var b=a!=x?a:{};a=b.clear!=x?b.clear:!0;b=b.resetAxes!=x?b.resetAxes:!1;this.target.trigger("jqplotPreReplot");a&&this.target.empty();b&&this.resetAxesScale(b);this.reInitialize();this.draw();this.target.trigger("jqplotPostReplot")};
this.redraw=function(a){a=null!=a?a:!0;this.target.trigger("jqplotPreRedraw");a&&this.target.empty();for(var b in this.axes)this.axes[b]._ticks=[];for(a=0;a<this.series.length;a++)this.populatePlotData(this.series[a],a);for(a=this._sumx=this._sumy=0;a<this.series.length;a++)this._sumy+=this.series[a]._sumy,this._sumx+=this.series[a]._sumx;this.draw();this.target.trigger("jqplotPostRedraw")};this.draw=function(){if(this.drawIfHidden||this.target.is(":visible")){this.target.trigger("jqplotPreDraw");
var a,b;for(a=0;a<e.jqplot.preDrawHooks.length;a++)e.jqplot.preDrawHooks[a].call(this);for(a=0;a<this.preDrawHooks.hooks.length;a++)this.preDrawHooks.hooks[a].call(this);this.target.append(this.title.draw());this.title.pack({top:0,left:0});var c=this.legend.draw();if("outsideGrid"==this.legend.placement){this.target.append(c);switch(this.legend.location){case "n":this.legend.getHeight();break;case "s":this.legend.getHeight();break;case "ne":case "e":case "se":this.legend.getWidth();break;case "nw":case "w":case "sw":this.legend.getWidth();
break;default:this.legend.getWidth()}c=c.detach()}a=this.axes;for(b in a)this.target.append(a[b].draw(this.baseCanvas._ctx)),a[b].set();a.yaxis.show&&a.yaxis.getWidth();b="y2axis y3axis y4axis y5axis y6axis y7axis y8axis y9axis".split(" ");var d=0,f;for(f=0;8>f;f++)a[b[f]].show&&(d+=a[b[f]].getWidth());a.x2axis.show&&a.x2axis.getHeight();this.title.show&&this.title.getHeight();a.xaxis.show&&a.xaxis.getHeight();d="outsideGrid"==this.legend.placement?{top:this.title.getHeight(),left:0,right:0,bottom:0}:
this._gridPadding;for(a=0;a<this.series.length;a++)b=this.seriesStack[a],this.target.append(this.series[b].shadowCanvas.createElement(this._gridPadding,"jqplot-series-shadowCanvas")),this.series[b].shadowCanvas.setContext(),this.series[b].shadowCanvas._elem.data("seriesIndex",b);for(a=0;a<this.series.length;a++)b=this.seriesStack[a],this.target.append(this.series[b].canvas.createElement(this._gridPadding,"jqplot-series-canvas")),this.series[b].canvas.setContext(),this.series[b].canvas._elem.data("seriesIndex",
b);this.target.append(this.eventCanvas.createElement(this._gridPadding,"jqplot-event-canvas"));this.eventCanvas.setContext();this.eventCanvas._ctx.fillStyle="rgba(0,0,0,0)";this.eventCanvas._ctx.fillRect(0,0,this.eventCanvas._ctx.canvas.width,this.eventCanvas._ctx.canvas.height);this.bindCustomEvents();this.legend.preDraw?(this.eventCanvas._elem.before(c),this.legend.pack(d),this.legend._elem?this.drawSeries({legendInfo:{location:this.legend.location,placement:this.legend.placement,width:this.legend.getWidth(),
height:this.legend.getHeight(),xoffset:this.legend.xoffset,yoffset:this.legend.yoffset}}):this.drawSeries()):(this.drawSeries(),e(this.series[this.series.length-1].canvas._elem).after(c),this.legend.pack(d));for(a=0;a<e.jqplot.eventListenerHooks.length;a++)this.eventCanvas._elem.bind(e.jqplot.eventListenerHooks[a][0],{plot:this},e.jqplot.eventListenerHooks[a][1]);for(a=0;a<this.eventListenerHooks.hooks.length;a++)this.eventCanvas._elem.bind(this.eventListenerHooks.hooks[a][0],{plot:this},this.eventListenerHooks.hooks[a][1]);
for(a=0;a<e.jqplot.postDrawHooks.length;a++)e.jqplot.postDrawHooks[a].call(this);for(a=0;a<this.postDrawHooks.hooks.length;a++)this.postDrawHooks.hooks[a].call(this);this.target.is(":visible")&&(this._drawCount+=1);this.target.trigger("jqplotPostDraw",[this])}};this.bindCustomEvents=function(){this.eventCanvas._elem.bind("click",{plot:this},this.onClick);this.eventCanvas._elem.bind("dblclick",{plot:this},this.onDblClick);this.eventCanvas._elem.bind("mousedown",{plot:this},this.onMouseDown);this.eventCanvas._elem.bind("mousemove",
{plot:this},this.onMouseMove);this.eventCanvas._elem.bind("mouseenter",{plot:this},this.onMouseEnter);this.eventCanvas._elem.bind("mouseleave",{plot:this},this.onMouseLeave);this.captureRightClick?(this.eventCanvas._elem.bind("mouseup",{plot:this},this.onRightClick),this.eventCanvas._elem.get(0).oncontextmenu=function(){return!1}):this.eventCanvas._elem.bind("mouseup",{plot:this},this.onMouseUp)};this.onClick=function(a){var c=b(a),f=a.data.plot,j=d(c.gridPos,f),h=jQuery.Event("jqplotClick");h.pageX=
a.pageX;h.pageY=a.pageY;e(this).trigger(h,[c.gridPos,c.dataPos,j,f])};this.onDblClick=function(a){var c=b(a),f=a.data.plot,j=d(c.gridPos,f),h=jQuery.Event("jqplotDblClick");h.pageX=a.pageX;h.pageY=a.pageY;e(this).trigger(h,[c.gridPos,c.dataPos,j,f])};this.onMouseDown=function(a){var c=b(a),f=a.data.plot,j=d(c.gridPos,f),h=jQuery.Event("jqplotMouseDown");h.pageX=a.pageX;h.pageY=a.pageY;e(this).trigger(h,[c.gridPos,c.dataPos,j,f])};this.onMouseUp=function(a){var c=b(a),d=jQuery.Event("jqplotMouseUp");
d.pageX=a.pageX;d.pageY=a.pageY;e(this).trigger(d,[c.gridPos,c.dataPos,null,a.data.plot])};this.onRightClick=function(a){var c=b(a),f=a.data.plot,j=d(c.gridPos,f);if(f.captureRightClick){var h=3==a.which?jQuery.Event("jqplotRightClick"):jQuery.Event("jqplotMouseUp");h.pageX=a.pageX;h.pageY=a.pageY;e(this).trigger(h,[c.gridPos,c.dataPos,j,f])}};this.onMouseMove=function(a){var c=b(a),f=a.data.plot,j=d(c.gridPos,f),h=jQuery.Event("jqplotMouseMove");h.pageX=a.pageX;h.pageY=a.pageY;e(this).trigger(h,
[c.gridPos,c.dataPos,j,f])};this.onMouseEnter=function(a){var c=b(a),d=a.data.plot,f=jQuery.Event("jqplotMouseEnter");f.pageX=a.pageX;f.pageY=a.pageY;e(this).trigger(f,[c.gridPos,c.dataPos,null,d])};this.onMouseLeave=function(a){var c=b(a),d=a.data.plot,f=jQuery.Event("jqplotMouseLeave");f.pageX=a.pageX;f.pageY=a.pageY;e(this).trigger(f,[c.gridPos,c.dataPos,null,d])};this.drawSeries=function(a,b){var c,d,f;b="number"==typeof a&&null==b?a:b;a="object"==typeof a?a:{};if(b!=x)d=this.series[b],f=d.shadowCanvas._ctx,
f.clearRect(0,0,f.canvas.width,f.canvas.height),d.drawShadow(f,a,this),f=d.canvas._ctx,f.clearRect(0,0,f.canvas.width,f.canvas.height),d.draw(f,a,this),d.renderer.constructor==e.jqplot.BezierCurveRenderer&&b<this.series.length-1&&this.drawSeries(b+1);else for(c=0;c<this.series.length;c++)d=this.series[c],f=d.shadowCanvas._ctx,f.clearRect(0,0,f.canvas.width,f.canvas.height),d.drawShadow(f,a,this),f=d.canvas._ctx,f.clearRect(0,0,f.canvas.width,f.canvas.height),d.draw(f,a,this)};this.moveSeriesToFront=
function(a){a=parseInt(a,10);var b=e.inArray(a,this.seriesStack);if(-1!=b)if(b==this.seriesStack.length-1)this.previousSeriesStack=this.seriesStack.slice(0);else{var c=this.seriesStack[this.seriesStack.length-1],d=this.series[a].canvas._elem.detach(),f=this.series[a].shadowCanvas._elem.detach();this.series[c].shadowCanvas._elem.after(f);this.series[c].canvas._elem.after(d);this.previousSeriesStack=this.seriesStack.slice(0);this.seriesStack.splice(b,1);this.seriesStack.push(a)}};this.moveSeriesToBack=
function(a){a=parseInt(a,10);var b=e.inArray(a,this.seriesStack);if(!(0==b||-1==b)){var c=this.seriesStack[0],d=this.series[a].canvas._elem.detach(),f=this.series[a].shadowCanvas._elem.detach();this.series[c].shadowCanvas._elem.before(f);this.series[c].canvas._elem.before(d);this.previousSeriesStack=this.seriesStack.slice(0);this.seriesStack.splice(b,1);this.seriesStack.unshift(a)}};this.restorePreviousSeriesOrder=function(){var a,b,c;if(this.seriesStack!=this.previousSeriesStack){for(a=1;a<this.previousSeriesStack.length;a++)move=
this.previousSeriesStack[a],keep=this.previousSeriesStack[a-1],b=this.series[move].canvas._elem.detach(),c=this.series[move].shadowCanvas._elem.detach(),this.series[keep].shadowCanvas._elem.after(c),this.series[keep].canvas._elem.after(b);a=this.seriesStack.slice(0);this.seriesStack=this.previousSeriesStack.slice(0);this.previousSeriesStack=a}};this.restoreOriginalSeriesOrder=function(){var a,b=[];for(a=0;a<this.series.length;a++)b.push(a);if(this.seriesStack!=b){this.previousSeriesStack=this.seriesStack.slice(0);
this.seriesStack=b;for(a=1;a<this.seriesStack.length;a++)serelem=this.series[a].canvas._elem.detach(),shadelem=this.series[a].shadowCanvas._elem.detach(),this.series[a-1].shadowCanvas._elem.after(shadelem),this.series[a-1].canvas._elem.after(serelem)}};this.activateTheme=function(a){this.themeEngine.activate(this,a)}}function N(){for(i=0;i<this.series.length;i++)this.series[i].renderer.constructor==e.jqplot.LineRenderer&&this.series[i].highlightMouseOver&&(this.series[i].highlightMouseDown=!1);this.target.bind("mouseout",
{plot:this},function(a){F(a.data.plot)})}function O(){this.plugins.lineRenderer={highlightedSeriesIndex:null};this.plugins.lineRenderer.highlightCanvas=new e.jqplot.GenericCanvas;this.eventCanvas._elem.before(this.plugins.lineRenderer.highlightCanvas.createElement(this._gridPadding,"jqplot-lineRenderer-highlight-canvas",this._plotDimensions));this.plugins.lineRenderer.highlightCanvas.setContext()}function K(a,b,d,c){var f=a.series[b],e=a.plugins.lineRenderer.highlightCanvas;e._ctx.clearRect(0,0,e._ctx.canvas.width,
e._ctx.canvas.height);f._highlightedPoint=d;a.plugins.lineRenderer.highlightedSeriesIndex=b;f.renderer.shapeRenderer.draw(e._ctx,c,{fillStyle:f.highlightColor})}function F(a){var b=a.plugins.lineRenderer.highlightCanvas;b._ctx.clearRect(0,0,b._ctx.canvas.width,b._ctx.canvas.height);for(b=0;b<a.series.length;b++)a.series[b]._highlightedPoint=null;a.plugins.lineRenderer.highlightedSeriesIndex=null;a.target.trigger("jqplotDataUnhighlight")}function P(a,b,d,c,f){c?(b=[c.seriesIndex,c.pointIndex,c.data],
d=jQuery.Event("jqplotDataMouseOver"),d.pageX=a.pageX,d.pageY=a.pageY,f.target.trigger(d,b),f.series[b[0]].highlightMouseOver&&b[0]!=f.plugins.lineRenderer.highlightedSeriesIndex&&(d=jQuery.Event("jqplotDataHighlight"),d.pageX=a.pageX,d.pageY=a.pageY,f.target.trigger(d,b),K(f,c.seriesIndex,c.pointIndex,c.points))):null==c&&F(f)}function Q(a,b,d,c,f){c?(b=[c.seriesIndex,c.pointIndex,c.data],f.series[b[0]].highlightMouseDown&&b[0]!=f.plugins.lineRenderer.highlightedSeriesIndex&&(d=jQuery.Event("jqplotDataHighlight"),
d.pageX=a.pageX,d.pageY=a.pageY,f.target.trigger(d,b),K(f,c.seriesIndex,c.pointIndex,c.points))):null==c&&F(f)}function R(a,b,d,c,f){a=f.plugins.lineRenderer.highlightedSeriesIndex;null!=a&&f.series[a].highlightMouseDown&&F(f)}function S(a,b,d,c,f){c&&(b=[c.seriesIndex,c.pointIndex,c.data],d=jQuery.Event("jqplotDataClick"),d.pageX=a.pageX,d.pageY=a.pageY,f.target.trigger(d,b))}function T(a,b,d,c,f){c&&(b=[c.seriesIndex,c.pointIndex,c.data],d=f.plugins.lineRenderer.highlightedSeriesIndex,null!=d&&
f.series[d].highlightMouseDown&&F(f),d=jQuery.Event("jqplotDataRightClick"),d.pageX=a.pageX,d.pageY=a.pageY,f.target.trigger(d,b))}function L(a,b){return a-b}function H(a){if(null==a||"object"!=typeof a)return a;var b=new a.constructor,d;for(d in a)b[d]=H(a[d]);return b}function I(a,b){if(!(null==b||"object"!=typeof b))for(var d in b)"highlightColors"==d&&(a[d]=H(b[d])),null!=b[d]&&"object"==typeof b[d]?(a.hasOwnProperty(d)||(a[d]={}),I(a[d],b[d])):a[d]=b[d]}var x;e.jqplot=function(a,b,d){var c,f;
null==d?b instanceof Array?(c=b,f=null):b.constructor==Object&&(c=null,f=b):(c=b,f=d);b=new M;e("#"+a).removeClass("jqplot-error");if(e.jqplot.config.catchErrors)try{return b.init(a,c,f),b.draw(),b.themeEngine.init.call(b),b}catch(n){c=e.jqplot.config.errorMessage||n.message,e("#"+a).append('<div class="jqplot-error-message">'+c+"</div>"),e("#"+a).addClass("jqplot-error"),document.getElementById(a).style.background=e.jqplot.config.errorBackground,document.getElementById(a).style.border=e.jqplot.config.errorBorder,
document.getElementById(a).style.fontFamily=e.jqplot.config.errorFontFamily,document.getElementById(a).style.fontSize=e.jqplot.config.errorFontSize,document.getElementById(a).style.fontStyle=e.jqplot.config.errorFontStyle,document.getElementById(a).style.fontWeight=e.jqplot.config.errorFontWeight}else return b.init(a,c,f),b.draw(),b.themeEngine.init.call(b),b};e.jqplot.debug=1;e.jqplot.config={debug:1,enablePlugins:!1,defaultHeight:300,defaultWidth:400,UTCAdjust:!1,timezoneOffset:new Date(6E4*(new Date).getTimezoneOffset()),
errorMessage:"",errorBackground:"",errorBorder:"",errorFontFamily:"",errorFontSize:"",errorFontStyle:"",errorFontWeight:"",catchErrors:!1,defaultTickFormatString:"%.1f"};e.jqplot.enablePlugins=e.jqplot.config.enablePlugins;e.jqplot.support_canvas=function(){return!!document.createElement("canvas").getContext};e.jqplot.support_canvas_text=function(){return!!(document.createElement("canvas").getContext&&"function"==typeof document.createElement("canvas").getContext("2d").fillText)};e.jqplot.use_excanvas=
e.browser.msie&&!e.jqplot.support_canvas()?!0:!1;e.jqplot.preInitHooks=[];e.jqplot.postInitHooks=[];e.jqplot.preParseOptionsHooks=[];e.jqplot.postParseOptionsHooks=[];e.jqplot.preDrawHooks=[];e.jqplot.postDrawHooks=[];e.jqplot.preDrawSeriesHooks=[];e.jqplot.postDrawSeriesHooks=[];e.jqplot.preDrawLegendHooks=[];e.jqplot.addLegendRowHooks=[];e.jqplot.preSeriesInitHooks=[];e.jqplot.postSeriesInitHooks=[];e.jqplot.preParseSeriesOptionsHooks=[];e.jqplot.postParseSeriesOptionsHooks=[];e.jqplot.eventListenerHooks=
[];e.jqplot.preDrawSeriesShadowHooks=[];e.jqplot.postDrawSeriesShadowHooks=[];e.jqplot.ElemContainer=function(){this._elem;this._plotWidth;this._plotHeight;this._plotDimensions={height:null,width:null}};e.jqplot.ElemContainer.prototype.createElement=function(a,b,d,c,f){this._offsets=b;b=d||"jqplot";a=document.createElement(a);this._elem=e(a);this._elem.addClass(b);this._elem.css(c);this._elem.attr(f);return this._elem};e.jqplot.ElemContainer.prototype.getWidth=function(){return this._elem?this._elem.outerWidth(!0):
null};e.jqplot.ElemContainer.prototype.getHeight=function(){return this._elem?this._elem.outerHeight(!0):null};e.jqplot.ElemContainer.prototype.getPosition=function(){return this._elem?this._elem.position():{top:null,left:null,bottom:null,right:null}};e.jqplot.ElemContainer.prototype.getTop=function(){return this.getPosition().top};e.jqplot.ElemContainer.prototype.getLeft=function(){return this.getPosition().left};e.jqplot.ElemContainer.prototype.getBottom=function(){return this._elem.css("bottom")};
e.jqplot.ElemContainer.prototype.getRight=function(){return this._elem.css("right")};y.prototype=new e.jqplot.ElemContainer;y.prototype.constructor=y;y.prototype.init=function(){this.renderer=new this.renderer;this.tickOptions.axis=this.name;null==this.tickOptions.showMark&&(this.tickOptions.showMark=this.showTicks);null==this.tickOptions.showMark&&(this.tickOptions.showMark=this.showTickMarks);null==this.tickOptions.showLabel&&(this.tickOptions.showLabel=this.showTicks);null==this.label||""==this.label?
this.showLabel=!1:this.labelOptions.label=this.label;!1==this.showLabel&&(this.labelOptions.show=!1);0==this.pad&&(this.pad=1);0==this.padMax&&(this.padMax=1);0==this.padMin&&(this.padMin=1);null==this.padMax&&(this.padMax=(this.pad-1)/2+1);null==this.padMin&&(this.padMin=(this.pad-1)/2+1);this.pad=this.padMax+this.padMin-1;if(null!=this.min||null!=this.max)this.autoscale=!1;null==this.syncTicks&&-1<this.name.indexOf("y")?this.syncTicks=!0:null==this.syncTicks&&(this.syncTicks=!1);this.renderer.init.call(this,
this.rendererOptions)};y.prototype.draw=function(a){return this.renderer.draw.call(this,a)};y.prototype.set=function(){this.renderer.set.call(this)};y.prototype.pack=function(a,b){this.show&&this.renderer.pack.call(this,a,b);null==this._min&&(this._min=this.min,this._max=this.max,this._tickInterval=this.tickInterval,this._numberTicks=this.numberTicks,this.__ticks=this._ticks)};y.prototype.reset=function(){this.renderer.reset.call(this)};y.prototype.resetScale=function(){this.tickInterval=this.numberTicks=
this.max=this.min=null};B.prototype=new e.jqplot.ElemContainer;B.prototype.constructor=B;B.prototype.setOptions=function(a){e.extend(!0,this,a);"inside"==this.placement&&(this.placement="insideGrid");if(0<this.xoffset){if("insideGrid"==this.placement)switch(this.location){case "nw":case "w":case "sw":null==this.marginLeft&&(this.marginLeft=this.xoffset+"px");this.marginRight="0px";break;default:null==this.marginRight&&(this.marginRight=this.xoffset+"px"),this.marginLeft="0px"}else if("outside"==this.placement)switch(this.location){case "nw":case "w":case "sw":null==
this.marginRight&&(this.marginRight=this.xoffset+"px");this.marginLeft="0px";break;default:null==this.marginLeft&&(this.marginLeft=this.xoffset+"px"),this.marginRight="0px"}this.xoffset=0}if(0<this.yoffset){if("outside"==this.placement)switch(this.location){case "sw":case "s":case "se":null==this.marginTop&&(this.marginTop=this.yoffset+"px");this.marginBottom="0px";break;default:null==this.marginBottom&&(this.marginBottom=this.yoffset+"px"),this.marginTop="0px"}else if("insideGrid"==this.placement)switch(this.location){case "sw":case "s":case "se":null==
this.marginBottom&&(this.marginBottom=this.yoffset+"px");this.marginTop="0px";break;default:null==this.marginTop&&(this.marginTop=this.yoffset+"px"),this.marginBottom="0px"}this.yoffset=0}};B.prototype.init=function(){this.renderer=new this.renderer;this.renderer.init.call(this,this.rendererOptions)};B.prototype.draw=function(a){for(var b=0;b<e.jqplot.preDrawLegendHooks.length;b++)e.jqplot.preDrawLegendHooks[b].call(this,a);return this.renderer.draw.call(this,a)};B.prototype.pack=function(a){this.renderer.pack.call(this,
a)};D.prototype=new e.jqplot.ElemContainer;D.prototype.constructor=D;D.prototype.init=function(){this.renderer=new this.renderer;this.renderer.init.call(this,this.rendererOptions)};D.prototype.draw=function(a){return this.renderer.draw.call(this,a)};D.prototype.pack=function(){this.renderer.pack.call(this)};C.prototype=new e.jqplot.ElemContainer;C.prototype.constructor=C;C.prototype.init=function(a,b,d){this.index=a;this.gridBorderWidth=b;a=this.data;b=[];var c;for(c=0;c<a.length;c++)this.breakOnNull?
b.push(a[c]):null==a[c]||(null==a[c][0]||null==a[c][1])||b.push(a[c]);this.data=b;this.fillColor||(this.fillColor=this.color);this.fillAlpha&&(a=e.jqplot.normalize2rgb(this.fillColor),a=e.jqplot.getColorComponents(a),this.fillColor="rgba("+a[0]+","+a[1]+","+a[2]+","+this.fillAlpha+")");this.renderer=new this.renderer;this.renderer.init.call(this,this.rendererOptions,d);this.markerRenderer=new this.markerRenderer;this.markerOptions.color||(this.markerOptions.color=this.color);null==this.markerOptions.show&&
(this.markerOptions.show=this.showMarker);this.showMarker=this.markerOptions.show;this.markerRenderer.init(this.markerOptions)};C.prototype.draw=function(a,b,d){b=b==x?{}:b;a=a==x?this.canvas._ctx:a;for(var c=0;c<e.jqplot.preDrawSeriesHooks.length;c++)e.jqplot.preDrawSeriesHooks[c].call(this,a,b);this.show&&(this.renderer.setGridData.call(this,d),b.preventJqPlotSeriesDrawTrigger||e(a.canvas).trigger("jqplotSeriesDraw",[this.data,this.gridData]),c=[],c=b.data?b.data:this._stack?this._plotData:this.data,
c=b.gridData||this.renderer.makeGridData.call(this,c,d),this.renderer.draw.call(this,a,c,b,d));for(c=0;c<e.jqplot.postDrawSeriesHooks.length;c++)e.jqplot.postDrawSeriesHooks[c].call(this,a,b)};C.prototype.drawShadow=function(a,b,d){b=b==x?{}:b;a=a==x?this.shadowCanvas._ctx:a;for(var c=0;c<e.jqplot.preDrawSeriesShadowHooks.length;c++)e.jqplot.preDrawSeriesShadowHooks[c].call(this,a,b);this.shadow&&(this.renderer.setGridData.call(this,d),c=[],c=b.data?b.data:this._stack?this._plotData:this.data,d=b.gridData||
this.renderer.makeGridData.call(this,c,d),this.renderer.drawShadow.call(this,a,d,b));for(c=0;c<e.jqplot.postDrawSeriesShadowHooks.length;c++)e.jqplot.postDrawSeriesShadowHooks[c].call(this,a,b)};C.prototype.toggleDisplay=function(a){var b,d;b=a.data.series?a.data.series:this;a.data.speed&&(d=a.data.speed);d?b.canvas._elem.is(":hidden")?(b.shadowCanvas._elem&&b.shadowCanvas._elem.fadeIn(d),b.canvas._elem.fadeIn(d),b.canvas._elem.nextAll(".jqplot-point-label.jqplot-series-"+b.index).fadeIn(d)):(b.shadowCanvas._elem&&
b.shadowCanvas._elem.fadeOut(d),b.canvas._elem.fadeOut(d),b.canvas._elem.nextAll(".jqplot-point-label.jqplot-series-"+b.index).fadeOut(d)):b.canvas._elem.is(":hidden")?(b.shadowCanvas._elem&&b.shadowCanvas._elem.show(),b.canvas._elem.show(),b.canvas._elem.nextAll(".jqplot-point-label.jqplot-series-"+b.index).show()):(b.shadowCanvas._elem&&b.shadowCanvas._elem.hide(),b.canvas._elem.hide(),b.canvas._elem.nextAll(".jqplot-point-label.jqplot-series-"+b.index).hide())};E.prototype=new e.jqplot.ElemContainer;
E.prototype.constructor=E;E.prototype.init=function(){this.renderer=new this.renderer;this.renderer.init.call(this,this.rendererOptions)};E.prototype.createElement=function(a){this._offsets=a;return this.renderer.createElement.call(this)};E.prototype.draw=function(){this.renderer.draw.call(this)};e.jqplot.GenericCanvas=function(){e.jqplot.ElemContainer.call(this);this._ctx};e.jqplot.GenericCanvas.prototype=new e.jqplot.ElemContainer;e.jqplot.GenericCanvas.prototype.constructor=e.jqplot.GenericCanvas;
e.jqplot.GenericCanvas.prototype.createElement=function(a,b,d){this._offsets=a;a="jqplot";b!=x&&(a=b);b=this._elem?this._elem.get(0):document.createElement("canvas");d!=x&&(this._plotDimensions=d);b.width=this._plotDimensions.width-this._offsets.left-this._offsets.right;b.height=this._plotDimensions.height-this._offsets.top-this._offsets.bottom;this._elem=e(b);this._elem.css({position:"absolute",left:this._offsets.left,top:this._offsets.top});this._elem.addClass(a);e.jqplot.use_excanvas&&(window.G_vmlCanvasManager.init_(document),
window.G_vmlCanvasManager.initElement(b));return this._elem};e.jqplot.GenericCanvas.prototype.setContext=function(){return this._ctx=this._elem.get(0).getContext("2d")};e.jqplot.HooksManager=function(){this.hooks=[]};e.jqplot.HooksManager.prototype.addOnce=function(a){var b=!1,d;for(d=0;d<this.hooks.length;d++)this.hooks[d][0]==a&&(b=!0);b||this.hooks.push(a)};e.jqplot.HooksManager.prototype.add=function(a){this.hooks.push(a)};e.jqplot.EventListenerManager=function(){this.hooks=[]};e.jqplot.EventListenerManager.prototype.addOnce=
function(a,b){var d=!1,c,f;for(f=0;f<this.hooks.length;f++)c=this.hooks[f],c[0]==a&&c[1]==b&&(d=!0);d||this.hooks.push([a,b])};e.jqplot.EventListenerManager.prototype.add=function(a,b){this.hooks.push([a,b])};e.jqplot.computeHighlightColors=function(a){var b;if("array"==typeof a){b=[];for(var d=0;d<a.length;d++){for(var c=e.jqplot.getColorComponents(a[d]),c=[c[0],c[1],c[2]],f=c[0]+c[1]+c[2],n=0;3>n;n++)c[n]=570<f?0.8*c[n]:c[n]+0.3*(255-c[n]),c[n]=parseInt(c[n],10);b.push("rgb("+c[0]+","+c[1]+","+
c[2]+")")}}else{c=e.jqplot.getColorComponents(a);c=[c[0],c[1],c[2]];f=c[0]+c[1]+c[2];for(n=0;3>n;n++)c[n]=570<f?0.8*c[n]:c[n]+0.3*(255-c[n]),c[n]=parseInt(c[n],10);b="rgb("+c[0]+","+c[1]+","+c[2]+")"}return b};e.jqplot.ColorGenerator=function(a){var b=0;this.next=function(){b<a.length||(b=0);return a[b++]};this.previous=function(){if(0<b)return a[b--];b=a.length-1;return a[b]};this.get=function(b){return a[b-a.length*Math.floor(b/a.length)]};this.setColors=function(b){a=b};this.reset=function(){b=
0}};e.jqplot.hex2rgb=function(a,b){a=a.replace("#","");3==a.length&&(a=a[0]+a[0]+a[1]+a[1]+a[2]+a[2]);var d;d="rgba("+parseInt(a.slice(0,2),16)+", "+parseInt(a.slice(2,4),16)+", "+parseInt(a.slice(4,6),16);b&&(d+=", "+b);return d+")"};e.jqplot.rgb2hex=function(a){a=a.match(/rgba?\( *([0-9]{1,3}\.?[0-9]*%?) *, *([0-9]{1,3}\.?[0-9]*%?) *, *([0-9]{1,3}\.?[0-9]*%?) *(?:, *[0-9.]*)?\)/);var b="#";for(i=1;4>i;i++){var d;d=-1!=a[i].search(/%/)?parseInt(255*a[i]/100,10).toString(16):parseInt(a[i],10).toString(16);
1==d.length&&(d="0"+d);b+=d}return b};e.jqplot.normalize2rgb=function(a,b){if(-1!=a.search(/^ *rgba?\(/))return a;if(-1!=a.search(/^ *#?[0-9a-fA-F]?[0-9a-fA-F]/))return e.jqplot.hex2rgb(a,b);throw"invalid color spec";};e.jqplot.getColorComponents=function(a){a=e.jqplot.colorKeywordMap[a]||a;a=e.jqplot.normalize2rgb(a).match(/rgba?\( *([0-9]{1,3}\.?[0-9]*%?) *, *([0-9]{1,3}\.?[0-9]*%?) *, *([0-9]{1,3}\.?[0-9]*%?) *,? *([0-9.]* *)?\)/);var b=[];for(i=1;4>i;i++)b[i-1]=-1!=a[i].search(/%/)?parseInt(255*
a[i]/100,10):parseInt(a[i],10);b[3]=parseFloat(a[4])?parseFloat(a[4]):1;return b};e.jqplot.colorKeywordMap={aliceblue:"rgb(240, 248, 255)",antiquewhite:"rgb(250, 235, 215)",aqua:"rgb( 0, 255, 255)",aquamarine:"rgb(127, 255, 212)",azure:"rgb(240, 255, 255)",beige:"rgb(245, 245, 220)",bisque:"rgb(255, 228, 196)",black:"rgb( 0, 0, 0)",blanchedalmond:"rgb(255, 235, 205)",blue:"rgb( 0, 0, 255)",blueviolet:"rgb(138, 43, 226)",brown:"rgb(165, 42, 42)",burlywood:"rgb(222, 184, 135)",cadetblue:"rgb( 95, 158, 160)",
chartreuse:"rgb(127, 255, 0)",chocolate:"rgb(210, 105, 30)",coral:"rgb(255, 127, 80)",cornflowerblue:"rgb(100, 149, 237)",cornsilk:"rgb(255, 248, 220)",crimson:"rgb(220, 20, 60)",cyan:"rgb( 0, 255, 255)",darkblue:"rgb( 0, 0, 139)",darkcyan:"rgb( 0, 139, 139)",darkgoldenrod:"rgb(184, 134, 11)",darkgray:"rgb(169, 169, 169)",darkgreen:"rgb( 0, 100, 0)",darkgrey:"rgb(169, 169, 169)",darkkhaki:"rgb(189, 183, 107)",darkmagenta:"rgb(139, 0, 139)",darkolivegreen:"rgb( 85, 107, 47)",darkorange:"rgb(255, 140, 0)",
darkorchid:"rgb(153, 50, 204)",darkred:"rgb(139, 0, 0)",darksalmon:"rgb(233, 150, 122)",darkseagreen:"rgb(143, 188, 143)",darkslateblue:"rgb( 72, 61, 139)",darkslategray:"rgb( 47, 79, 79)",darkslategrey:"rgb( 47, 79, 79)",darkturquoise:"rgb( 0, 206, 209)",darkviolet:"rgb(148, 0, 211)",deeppink:"rgb(255, 20, 147)",deepskyblue:"rgb( 0, 191, 255)",dimgray:"rgb(105, 105, 105)",dimgrey:"rgb(105, 105, 105)",dodgerblue:"rgb( 30, 144, 255)",firebrick:"rgb(178, 34, 34)",floralwhite:"rgb(255, 250, 240)",forestgreen:"rgb( 34, 139, 34)",
fuchsia:"rgb(255, 0, 255)",gainsboro:"rgb(220, 220, 220)",ghostwhite:"rgb(248, 248, 255)",gold:"rgb(255, 215, 0)",goldenrod:"rgb(218, 165, 32)",gray:"rgb(128, 128, 128)",grey:"rgb(128, 128, 128)",green:"rgb( 0, 128, 0)",greenyellow:"rgb(173, 255, 47)",honeydew:"rgb(240, 255, 240)",hotpink:"rgb(255, 105, 180)",indianred:"rgb(205, 92, 92)",indigo:"rgb( 75, 0, 130)",ivory:"rgb(255, 255, 240)",khaki:"rgb(240, 230, 140)",lavender:"rgb(230, 230, 250)",lavenderblush:"rgb(255, 240, 245)",lawngreen:"rgb(124, 252, 0)",
lemonchiffon:"rgb(255, 250, 205)",lightblue:"rgb(173, 216, 230)",lightcoral:"rgb(240, 128, 128)",lightcyan:"rgb(224, 255, 255)",lightgoldenrodyellow:"rgb(250, 250, 210)",lightgray:"rgb(211, 211, 211)",lightgreen:"rgb(144, 238, 144)",lightgrey:"rgb(211, 211, 211)",lightpink:"rgb(255, 182, 193)",lightsalmon:"rgb(255, 160, 122)",lightseagreen:"rgb( 32, 178, 170)",lightskyblue:"rgb(135, 206, 250)",lightslategray:"rgb(119, 136, 153)",lightslategrey:"rgb(119, 136, 153)",lightsteelblue:"rgb(176, 196, 222)",
lightyellow:"rgb(255, 255, 224)",lime:"rgb( 0, 255, 0)",limegreen:"rgb( 50, 205, 50)",linen:"rgb(250, 240, 230)",magenta:"rgb(255, 0, 255)",maroon:"rgb(128, 0, 0)",mediumaquamarine:"rgb(102, 205, 170)",mediumblue:"rgb( 0, 0, 205)",mediumorchid:"rgb(186, 85, 211)",mediumpurple:"rgb(147, 112, 219)",mediumseagreen:"rgb( 60, 179, 113)",mediumslateblue:"rgb(123, 104, 238)",mediumspringgreen:"rgb( 0, 250, 154)",mediumturquoise:"rgb( 72, 209, 204)",mediumvioletred:"rgb(199, 21, 133)",midnightblue:"rgb( 25, 25, 112)",
mintcream:"rgb(245, 255, 250)",mistyrose:"rgb(255, 228, 225)",moccasin:"rgb(255, 228, 181)",navajowhite:"rgb(255, 222, 173)",navy:"rgb( 0, 0, 128)",oldlace:"rgb(253, 245, 230)",olive:"rgb(128, 128, 0)",olivedrab:"rgb(107, 142, 35)",orange:"rgb(255, 165, 0)",orangered:"rgb(255, 69, 0)",orchid:"rgb(218, 112, 214)",palegoldenrod:"rgb(238, 232, 170)",palegreen:"rgb(152, 251, 152)",paleturquoise:"rgb(175, 238, 238)",palevioletred:"rgb(219, 112, 147)",papayawhip:"rgb(255, 239, 213)",peachpuff:"rgb(255, 218, 185)",
peru:"rgb(205, 133, 63)",pink:"rgb(255, 192, 203)",plum:"rgb(221, 160, 221)",powderblue:"rgb(176, 224, 230)",purple:"rgb(128, 0, 128)",red:"rgb(255, 0, 0)",rosybrown:"rgb(188, 143, 143)",royalblue:"rgb( 65, 105, 225)",saddlebrown:"rgb(139, 69, 19)",salmon:"rgb(250, 128, 114)",sandybrown:"rgb(244, 164, 96)",seagreen:"rgb( 46, 139, 87)",seashell:"rgb(255, 245, 238)",sienna:"rgb(160, 82, 45)",silver:"rgb(192, 192, 192)",skyblue:"rgb(135, 206, 235)",slateblue:"rgb(106, 90, 205)",slategray:"rgb(112, 128, 144)",
slategrey:"rgb(112, 128, 144)",snow:"rgb(255, 250, 250)",springgreen:"rgb( 0, 255, 127)",steelblue:"rgb( 70, 130, 180)",tan:"rgb(210, 180, 140)",teal:"rgb( 0, 128, 128)",thistle:"rgb(216, 191, 216)",tomato:"rgb(255, 99, 71)",turquoise:"rgb( 64, 224, 208)",violet:"rgb(238, 130, 238)",wheat:"rgb(245, 222, 179)",white:"rgb(255, 255, 255)",whitesmoke:"rgb(245, 245, 245)",yellow:"rgb(255, 255, 0)",yellowgreen:"rgb(154, 205, 50)"};e.jqplot.log=function(){};e.jqplot.AxisLabelRenderer=function(a){e.jqplot.ElemContainer.call(this);
this.axis;this.show=!0;this.label="";this.textColor=this.fontSize=this.fontFamily=null;this._elem;this.escapeHTML=!1;e.extend(!0,this,a)};e.jqplot.AxisLabelRenderer.prototype=new e.jqplot.ElemContainer;e.jqplot.AxisLabelRenderer.prototype.constructor=e.jqplot.AxisLabelRenderer;e.jqplot.AxisLabelRenderer.prototype.init=function(a){e.extend(!0,this,a)};e.jqplot.AxisLabelRenderer.prototype.draw=function(){this._elem=e('<div style="position:absolute;" class="jqplot-'+this.axis+'-label"></div>');Number(this.label)&&
this._elem.css("white-space","nowrap");this.escapeHTML?this._elem.text(this.label):this._elem.html(this.label);this.fontFamily&&this._elem.css("font-family",this.fontFamily);this.fontSize&&this._elem.css("font-size",this.fontSize);this.textColor&&this._elem.css("color",this.textColor);return this._elem};e.jqplot.AxisLabelRenderer.prototype.pack=function(){};e.jqplot.AxisTickRenderer=function(a){e.jqplot.ElemContainer.call(this);this.mark="outside";this.axis;this.showGridline=this.showMark=!0;this.isMinorTick=
!1;this.size=4;this.markSize=6;this.showLabel=this.show=!0;this.label="";this.value=null;this._styles={};this.formatter=e.jqplot.DefaultTickFormatter;this.formatString=this.prefix="";this.fontFamily;this.fontSize;this.textColor;this._elem;e.extend(!0,this,a)};e.jqplot.AxisTickRenderer.prototype.init=function(a){e.extend(!0,this,a)};e.jqplot.AxisTickRenderer.prototype=new e.jqplot.ElemContainer;e.jqplot.AxisTickRenderer.prototype.constructor=e.jqplot.AxisTickRenderer;e.jqplot.AxisTickRenderer.prototype.setTick=
function(a,b,d){this.value=a;this.axis=b;d&&(this.isMinorTick=!0);return this};e.jqplot.AxisTickRenderer.prototype.draw=function(){this.label||(this.label=this.formatter(this.formatString,this.value));this.prefix&&!this.formatString&&(this.label=this.prefix+this.label);style='style="position:absolute;';Number(this.label)&&(style+="white-space:nowrap;");style+='"';this._elem=e("<div "+style+' class="jqplot-'+this.axis+'-tick">'+this.label+"</div>");for(var a in this._styles)this._elem.css(a,this._styles[a]);
this.fontFamily&&this._elem.css("font-family",this.fontFamily);this.fontSize&&this._elem.css("font-size",this.fontSize);this.textColor&&this._elem.css("color",this.textColor);return this._elem};e.jqplot.DefaultTickFormatter=function(a,b){return"number"==typeof b?(a||(a=e.jqplot.config.defaultTickFormatString),e.jqplot.sprintf(a,b)):String(b)};e.jqplot.AxisTickRenderer.prototype.pack=function(){};e.jqplot.CanvasGridRenderer=function(){this.shadowRenderer=new e.jqplot.ShadowRenderer};e.jqplot.CanvasGridRenderer.prototype.init=
function(a){this._ctx;e.extend(!0,this,a);this.renderer.shadowRenderer.init({lineJoin:"miter",lineCap:"round",fill:!1,isarc:!1,angle:this.shadowAngle,offset:this.shadowOffset,alpha:this.shadowAlpha,depth:this.shadowDepth,lineWidth:this.shadowWidth,closePath:!1,strokeStyle:this.shadowColor})};e.jqplot.CanvasGridRenderer.prototype.createElement=function(){var a=document.createElement("canvas"),b=this._plotDimensions.width,d=this._plotDimensions.height;console.debug("w",b);console.debug("h",d);a.width=
b;a.height=d;this._elem=e(a);this._elem.addClass("jqplot-grid-canvas");this._elem.css({position:"absolute",left:0,top:0});e.jqplot.use_excanvas&&window.G_vmlCanvasManager.init_(document);e.jqplot.use_excanvas&&window.G_vmlCanvasManager.initElement(a);this._top=this._offsets.top;this._bottom=d-this._offsets.bottom;this._left=this._offsets.left;this._right=b-this._offsets.right;this._width=this._right-this._left;this._height=this._bottom-this._top;return this._elem};e.jqplot.CanvasGridRenderer.prototype.draw=
function(){function a(a,c,d,f,g){b.save();g=g||{};if(null==g.lineWidth||0!=g.lineWidth)e.extend(!0,b,g),b.beginPath(),b.moveTo(a,c),b.lineTo(d,f),b.stroke(),b.restore()}var b=this._ctx=this._elem.get(0).getContext("2d"),d=this._axes;b.save();b.clearRect(0,0,this._plotDimensions.width,this._plotDimensions.height);b.fillStyle=this.backgroundColor||this.background;b.fillRect(this._left,this._top,this._width,this._height);if(this.drawGridlines){b.save();b.lineJoin="miter";b.lineCap="butt";b.lineWidth=
this.gridLineWidth;b.strokeStyle=this.gridLineColor;for(var c,f,n=["xaxis","yaxis","x2axis","y2axis"],k=4;0<k;k--){var t=n[k-1],j=d[t],h=j._ticks;if(j.show)for(var p=h.length;0<p;p--)if(c=h[p-1],c.show){var g=Math.round(j.u2p(c.value))+0.5;switch(t){case "xaxis":c.showGridline&&a(g,this._top,g,this._bottom);if(c.showMark&&c.mark){s=c.markSize;m=c.mark;g=Math.round(j.u2p(c.value))+0.5;switch(m){case "outside":c=this._bottom;f=this._bottom+s;break;case "inside":c=this._bottom-s;f=this._bottom;break;
case "cross":c=this._bottom-s;f=this._bottom+s;break;default:c=this._bottom,f=this._bottom+s}this.shadow&&this.renderer.shadowRenderer.draw(b,[[g,c],[g,f]],{lineCap:"butt",lineWidth:this.gridLineWidth,offset:0.75*this.gridLineWidth,depth:2,fill:!1,closePath:!1});a(g,c,g,f)}break;case "yaxis":c.showGridline&&a(this._right,g,this._left,g);if(c.showMark&&c.mark){s=c.markSize;m=c.mark;g=Math.round(j.u2p(c.value))+0.5;switch(m){case "outside":c=this._left-s;f=this._left;break;case "inside":c=this._left;
f=this._left+s;break;case "cross":c=this._left-s;f=this._left+s;break;default:c=this._left-s,f=this._left}this.shadow&&this.renderer.shadowRenderer.draw(b,[[c,g],[f,g]],{lineCap:"butt",lineWidth:1.5*this.gridLineWidth,offset:0.75*this.gridLineWidth,fill:!1,closePath:!1});a(c,g,f,g,{strokeStyle:j.borderColor})}break;case "x2axis":c.showGridline&&a(g,this._bottom,g,this._top);if(c.showMark&&c.mark){s=c.markSize;m=c.mark;g=Math.round(j.u2p(c.value))+0.5;switch(m){case "outside":c=this._top-s;f=this._top;
break;case "inside":c=this._top;f=this._top+s;break;case "cross":c=this._top-s;f=this._top+s;break;default:c=this._top-s,f=this._top}this.shadow&&this.renderer.shadowRenderer.draw(b,[[g,c],[g,f]],{lineCap:"butt",lineWidth:this.gridLineWidth,offset:0.75*this.gridLineWidth,depth:2,fill:!1,closePath:!1});a(g,c,g,f)}break;case "y2axis":if(c.showGridline&&a(this._left,g,this._right,g),c.showMark&&c.mark){s=c.markSize;m=c.mark;g=Math.round(j.u2p(c.value))+0.5;switch(m){case "outside":c=this._right;f=this._right+
s;break;case "inside":c=this._right-s;f=this._right;break;case "cross":c=this._right-s;f=this._right+s;break;default:c=this._right,f=this._right+s}this.shadow&&this.renderer.shadowRenderer.draw(b,[[c,g],[f,g]],{lineCap:"butt",lineWidth:1.5*this.gridLineWidth,offset:0.75*this.gridLineWidth,fill:!1,closePath:!1});a(c,g,f,g,{strokeStyle:j.borderColor})}}}}n="y3axis y4axis y5axis y6axis y7axis y8axis y9axis".split(" ");for(k=7;0<k;k--)if(j=d[n[k-1]],h=j._ticks,j.show){var p=h[j.numberTicks-1],g=h[0],
t=j.getLeft(),q=[[t,p.getTop()+p.getHeight()/2],[t,g.getTop()+g.getHeight()/2+1]];this.shadow&&this.renderer.shadowRenderer.draw(b,q,{lineCap:"butt",fill:!1,closePath:!1});a(q[0][0],q[0][1],q[1][0],q[1][1],{lineCap:"butt",strokeStyle:j.borderColor,lineWidth:j.borderWidth});for(p=h.length;0<p;p--)if(c=h[p-1],s=c.markSize,m=c.mark,g=Math.round(j.u2p(c.value))+0.5,c.showMark&&c.mark){switch(m){case "outside":c=t;f=t+s;break;case "inside":c=t-s;f=t;break;case "cross":c=t-s;f=t+s;break;default:c=t,f=t+
s}q=[[c,g],[f,g]];this.shadow&&this.renderer.shadowRenderer.draw(b,q,{lineCap:"butt",lineWidth:1.5*this.gridLineWidth,offset:0.75*this.gridLineWidth,fill:!1,closePath:!1});a(c,g,f,g,{strokeStyle:j.borderColor})}}b.restore()}this.shadow&&(q=[[this._left,this._bottom],[this._right,this._bottom],[this._right,this._top]],this.renderer.shadowRenderer.draw(b,q));0!=this.borderWidth&&this.drawBorder&&(a(this._left,this._top,this._right,this._top,{lineCap:"round",strokeStyle:d.x2axis.borderColor,lineWidth:d.x2axis.borderWidth}),
a(this._right,this._top,this._right,this._bottom,{lineCap:"round",strokeStyle:d.y2axis.borderColor,lineWidth:d.y2axis.borderWidth}),a(this._right,this._bottom,this._left,this._bottom,{lineCap:"round",strokeStyle:d.xaxis.borderColor,lineWidth:d.xaxis.borderWidth}),a(this._left,this._bottom,this._left,this._top,{lineCap:"round",strokeStyle:d.yaxis.borderColor,lineWidth:d.yaxis.borderWidth}));b.restore()};var J=function(a,b){for(a=String(a);a.length<b;)a="0"+a;return a},A={millisecond:1,second:1E3,minute:6E4,
hour:36E5,day:864E5,week:6048E5,month:{add:function(a,b){A.year.add(a,Math[0<b?"floor":"ceil"](b/12));var d=a.getMonth()+b%12;12==d?(d=0,a.setYear(a.getFullYear()+1)):-1==d&&(d=11,a.setYear(a.getFullYear()-1));a.setMonth(d)},diff:function(a,b){var d=a.getFullYear()-b.getFullYear(),d=a.getMonth()-b.getMonth()+12*d,c=a.getDate()-b.getDate();return d+c/30}},year:{add:function(a,b){a.setYear(a.getFullYear()+Math[0<b?"floor":"ceil"](b))},diff:function(a,b){return A.month.diff(a,b)/12}}},z;for(z in A)"s"!=
z.substring(z.length-1)&&(A[z+"s"]=A[z]);z={succ:function(a){return this.clone().add(1,a)},add:function(a,b){var d=A[b]||A.day;"number"==typeof d?this.setTime(this.getTime()+d*a):d.add(this,a);return this},diff:function(a,b,d){a=Date.create(a);if(null===a)return null;b=A[b]||A.day;a="number"==typeof b?(this.getTime()-a.getTime())/b:b.diff(this,a);return d?a:Math[0<a?"floor":"ceil"](a)},strftime:function(a){a=a||"%Y-%m-%d";for(var b="",d;0<a.length;)if(d=a.match(Date.prototype.strftime.formatCodes.matcher)){var b=
b+a.slice(0,d.index),c=d[1]||"",f;f=d[2];if(Date.prototype.strftime.formatShortcuts[f])f=this.strftime(Date.prototype.strftime.formatShortcuts[f]);else{f=(Date.prototype.strftime.formatCodes[f]||"").split(".");var e=this["get"+f[0]]?this["get"+f[0]]():"";f[1]&&(e=J(e,f[1]));f=e}b+=c+f;a=a.slice(d.index+d[0].length)}else b+=a,a="";return b},getShortYear:function(){return this.getYear()%100},getMonthNumber:function(){return this.getMonth()+1},getMonthName:function(){return Date.MONTHNAMES[this.getMonth()]},
getAbbrMonthName:function(){return Date.ABBR_MONTHNAMES[this.getMonth()]},getDayName:function(){return Date.DAYNAMES[this.getDay()]},getAbbrDayName:function(){return Date.ABBR_DAYNAMES[this.getDay()]},getDayOrdinal:function(){return Date.ORDINALNAMES[this.getDate()%10]},getHours12:function(){var a=this.getHours();return 12<a?a-12:0==a?12:a},getAmPm:function(){return 12<=this.getHours()?"PM":"AM"},getUnix:function(){return Math.round(this.getTime()/1E3,0)},getGmtOffset:function(){var a=this.getTimezoneOffset()/
60,b=0>a?"+":"-",a=Math.abs(a);return b+J(Math.floor(a),2)+":"+J(60*(a%1),2)},getTimezoneName:function(){var a=/(?:\((.+)\)$| ([A-Z]{3}) )/.exec(this.toString());return a[1]||a[2]||"GMT"+this.getGmtOffset()},toYmdInt:function(){return 1E4*this.getFullYear()+100*this.getMonthNumber()+this.getDate()},clone:function(){return new Date(this.getTime())}};for(var G in z)Date.prototype[G]=z[G];z={create:function(a){if(a instanceof Date)return a;if("number"==typeof a)return new Date(a);a=String(a).replace(/^\s*(.+)\s*$/,
"$1");for(var b=0,d=Date.create.patterns.length,c,f=a;b<d;){ms=Date.parse(f);if(!isNaN(ms))return new Date(ms);c=Date.create.patterns[b];if("function"==typeof c){if(obj=c(f),obj instanceof Date)return obj}else f=a.replace(c[0],c[1]);b++}return NaN},MONTHNAMES:"January February March April May June July August September October November December".split(" "),ABBR_MONTHNAMES:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),DAYNAMES:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
ABBR_DAYNAMES:"Sun Mon Tue Wed Thu Fri Sat".split(" "),ORDINALNAMES:"th st nd rd th th th th th th".split(" "),ISO:"%Y-%m-%dT%H:%M:%S.%N%G",SQL:"%Y-%m-%d %H:%M:%S",daysInMonth:function(a,b){return 2==b?29==(new Date(a,1,29)).getDate()?29:28:[x,31,x,31,30,31,30,31,31,30,31,30,31][b]}};for(G in z)Date[G]=z[G];Date.prototype.strftime.formatCodes={matcher:/()%(#?(%|[a-z]))/i,Y:"FullYear",y:"ShortYear.2",m:"MonthNumber.2","#m":"MonthNumber",B:"MonthName",b:"AbbrMonthName",d:"Date.2","#d":"Date",e:"Date",
A:"DayName",a:"AbbrDayName",w:"Day",o:"DayOrdinal",H:"Hours.2","#H":"Hours",I:"Hours12.2","#I":"Hours12",p:"AmPm",M:"Minutes.2","#M":"Minutes",S:"Seconds.2","#S":"Seconds",s:"Unix",N:"Milliseconds.3","#N":"Milliseconds",O:"TimezoneOffset",Z:"TimezoneName",G:"GmtOffset"};Date.prototype.strftime.formatShortcuts={F:"%Y-%m-%d",T:"%H:%M:%S",X:"%H:%M:%S",x:"%m/%d/%y",D:"%m/%d/%y","#c":"%a %b %e %H:%M:%S %Y",v:"%e-%b-%Y",R:"%H:%M",r:"%I:%M:%S %p",t:"\t",n:"\n","%":"%"};Date.create.patterns=[[/-/g,"/"],[/st|nd|rd|th/g,
""],[/(3[01]|[0-2]\d)\s*\.\s*(1[0-2]|0\d)\s*\.\s*([1-9]\d{3})/,"$2/$1/$3"],[/([1-9]\d{3})\s*-\s*(1[0-2]|0\d)\s*-\s*(3[01]|[0-2]\d)/,"$2/$3/$1"],function(a){var b=a.match(/^(?:(.+)\s+)?([012]?\d)(?:\s*\:\s*(\d\d))?(?:\s*\:\s*(\d\d(\.\d*)?))?\s*(am|pm)?\s*$/i);if(b){if(b[1]){if(a=Date.create(b[1]),isNaN(a))return}else a=new Date,a.setMilliseconds(0);var d=parseFloat(b[2]);b[6]&&(d="am"==b[6].toLowerCase()?12==d?0:d:12==d?12:d+12);a.setHours(d,parseInt(b[3]||0,10),parseInt(b[4]||0,10),1E3*(parseFloat(b[5]||
0)||0))}return a},function(a){var b=a.match(/^(?:(.+))[T|\s+]([012]\d)(?:\:(\d\d))(?:\:(\d\d))(?:\.\d+)([\+\-]\d\d\:\d\d)$/i);if(b){if(b[1]){if(a=Date.create(b[1]),isNaN(a))return}else a=new Date,a.setMilliseconds(0);var d=parseFloat(b[2]);a.setHours(d,parseInt(b[3],10),parseInt(b[4],10),1E3*parseFloat(b[5]))}return a},function(a){var b=a.match(/^([0-3]?\d)\s*[-\/.\s]{1}\s*([a-zA-Z]{3,9})\s*[-\/.\s]{1}\s*([0-3]?\d)$/);if(b){a=new Date;var d=parseFloat(String(a.getFullYear()).slice(2,4)),c=100*parseInt(String(a.getFullYear())/
100,10),f=parseFloat(b[1]),n=parseFloat(b[3]),k;31<f?(k=b[3],d=f<d+1?c+f:c-100+f):(k=b[1],d=n<d+1?c+n:c-100+n);c=e.inArray(b[2],Date.ABBR_MONTHNAMES);-1==c&&(c=e.inArray(b[2],Date.MONTHNAMES));a.setFullYear(d,c,k);a.setHours(0,0,0,0)}return a}];e.jqplot.config.debug&&(e.date=Date.create);e.jqplot.DivTitleRenderer=function(){};e.jqplot.DivTitleRenderer.prototype.init=function(a){e.extend(!0,this,a)};e.jqplot.DivTitleRenderer.prototype.draw=function(){if(this.text){if(this.text){var a;this.color?a=
this.color:this.textColor&&(a=this.textColor);var b;b="position:absolute;top:0px;left:0px;"+(this._plotWidth?"width:"+this._plotWidth+"px;":"");b+=this.fontSize?"font-size:"+this.fontSize+";":"";b+=this.textAlign?"text-align:"+this.textAlign+";":"text-align:center;";b=b+(a?"color:"+a+";":"")+(this.paddingBottom?"padding-bottom:"+this.paddingBottom+";":"");this._elem=e('<div class="jqplot-title" style="'+b+'">'+this.text+"</div>");this.fontFamily&&this._elem.css("font-family",this.fontFamily)}}else this.show=
!1,this._elem=e('<div class="jqplot-title" style="height:0px;width:0px;"></div>');return this._elem};e.jqplot.DivTitleRenderer.prototype.pack=function(){};e.jqplot.LineRenderer=function(){this.shapeRenderer=new e.jqplot.ShapeRenderer;this.shadowRenderer=new e.jqplot.ShadowRenderer};e.jqplot.LineRenderer.prototype.init=function(a,b){a=a||{};var d=a.highlightMouseOver,c=a.highlightMouseDown,f=a.highlightColor;delete a.highlightMouseOver;delete a.highlightMouseDown;delete a.highlightColor;e.extend(!0,
this.renderer,a);this.renderer.shapeRenderer.init({lineJoin:"round",lineCap:"round",fill:this.fill,isarc:!1,strokeStyle:this.color,fillStyle:this.fillColor,lineWidth:this.lineWidth,closePath:this.fill});var n=2.5<this.lineWidth?this.shadowOffset*(1+0.6*(Math.atan(this.lineWidth/2.5)/0.785398163-1)):this.shadowOffset*Math.atan(this.lineWidth/2.5)/0.785398163;this.renderer.shadowRenderer.init({lineJoin:"round",lineCap:"round",fill:this.fill,isarc:!1,angle:this.shadowAngle,offset:n,alpha:this.shadowAlpha,
depth:this.shadowDepth,lineWidth:this.lineWidth,closePath:this.fill});this._areaPoints=[];this._boundingBox=[[],[]];!this.isTrendline&&this.fill&&(this.highlightMouseOver=!0,this.highlightMouseDown=!1,this.highlightColor=null,c&&null==d&&(d=!1),e.extend(!0,this,{highlightMouseOver:d,highlightMouseDown:c,highlightColor:f}),this.highlightColor||(this.highlightColor=e.jqplot.computeHighlightColors(this.fillColor)),this.highlighter&&(this.highlighter.show=!1),b.postInitHooks.addOnce(N),b.postDrawHooks.addOnce(O),
b.eventListenerHooks.addOnce("jqplotMouseMove",P),b.eventListenerHooks.addOnce("jqplotMouseDown",Q),b.eventListenerHooks.addOnce("jqplotMouseUp",R),b.eventListenerHooks.addOnce("jqplotClick",S),b.eventListenerHooks.addOnce("jqplotRightClick",T))};e.jqplot.LineRenderer.prototype.setGridData=function(){var a=this._xaxis.series_u2p,b=this._yaxis.series_u2p,d=this._plotData,c=this._prevPlotData;this.gridData=[];this._prevGridData=[];for(var f=0;f<this.data.length;f++)null!=d[f][0]&&null!=d[f][1]?this.gridData.push([a.call(this._xaxis,
d[f][0]),b.call(this._yaxis,d[f][1])]):null==d[f][0]?this.gridData.push([null,b.call(this._yaxis,d[f][1])]):null==d[f][1]&&this.gridData.push([a.call(this._xaxis,d[f][0]),null]),null!=c[f]&&null!=c[f][0]&&null!=c[f][1]?this._prevGridData.push([a.call(this._xaxis,c[f][0]),b.call(this._yaxis,c[f][1])]):null!=c[f]&&null==c[f][0]?this._prevGridData.push([null,b.call(this._yaxis,c[f][1])]):null!=c[f]&&(null!=c[f][0]&&null==c[f][1])&&this._prevGridData.push([a.call(this._xaxis,c[f][0]),null])};e.jqplot.LineRenderer.prototype.makeGridData=
function(a){for(var b=this._xaxis.series_u2p,d=this._yaxis.series_u2p,c=[],f=0;f<a.length;f++)null!=a[f][0]&&null!=a[f][1]?c.push([b.call(this._xaxis,a[f][0]),d.call(this._yaxis,a[f][1])]):null==a[f][0]?c.push([null,d.call(this._yaxis,a[f][1])]):null==a[f][1]&&c.push([b.call(this._xaxis,a[f][0]),null]);return c};e.jqplot.LineRenderer.prototype.draw=function(a,b,d){var c;d=d!=x?d:{};var f=d.shadow!=x?d.shadow:this.shadow;c=d.showLine!=x?d.showLine:this.showLine;var n=d.fill!=x?d.fill:this.fill,k=d.fillAndStroke!=
x?d.fillAndStroke:this.fillAndStroke,t,j;a.save();if(b.length){if(c)if(n){if(this.fillToZero){j=(new e.jqplot.ColorGenerator(this.negativeSeriesColors)).get(this.index);this.useNegativeColors||(j=d.fillStyle);var h=d.fillStyle;k&&(t=b.slice(0));if(0==this.index||!this._stack){var p=[];this._areaPoints=[];var g=this._yaxis.series_u2p(this.fillToValue);this._xaxis.series_u2p(this.fillToValue);if("y"==this.fillAxis){p.push([b[0][0],g]);this._areaPoints.push([b[0][0],g]);for(c=0;c<b.length-1;c++)if(p.push(b[c]),
this._areaPoints.push(b[c]),0>this._plotData[c][1]*this._plotData[c+1][1]){d.fillStyle=0>this._plotData[c][1]?j:h;var q=b[c][0]+(b[c+1][0]-b[c][0])*(g-b[c][1])/(b[c+1][1]-b[c][1]);p.push([q,g]);this._areaPoints.push([q,g]);f&&this.renderer.shadowRenderer.draw(a,p,d);this.renderer.shapeRenderer.draw(a,p,d);p=[[q,g]]}d.fillStyle=0>this._plotData[b.length-1][1]?j:h;p.push(b[b.length-1]);this._areaPoints.push(b[b.length-1]);p.push([b[b.length-1][0],g]);this._areaPoints.push([b[b.length-1][0],g])}f&&this.renderer.shadowRenderer.draw(a,
p,d);this.renderer.shapeRenderer.draw(a,p,d)}else{j=this._prevGridData;for(c=j.length;0<c;c--)b.push(j[c-1]);f&&this.renderer.shadowRenderer.draw(a,b,d);this._areaPoints=b;this.renderer.shapeRenderer.draw(a,b,d)}}else{k&&(t=b.slice(0));if(0==this.index||!this._stack)c=a.canvas.height,b.unshift([b[0][0],c]),len=b.length,b.push([b[len-1][0],c]);else{j=this._prevGridData;for(c=j.length;0<c;c--)b.push(j[c-1])}this._areaPoints=b;f&&this.renderer.shadowRenderer.draw(a,b,d);this.renderer.shapeRenderer.draw(a,
b,d)}if(k&&(c=e.extend(!0,{},d,{fill:!1,closePath:!1}),this.renderer.shapeRenderer.draw(a,t,c),this.markerRenderer.show))for(c=0;c<t.length;c++)this.markerRenderer.draw(t[c][0],t[c][1],a,d.markerOptions)}else f&&this.renderer.shadowRenderer.draw(a,b,d),this.renderer.shapeRenderer.draw(a,b,d);t=k=f=j=null;for(c=0;c<this._areaPoints.length;c++){h=this._areaPoints[c];if(t>h[0]||null==t)t=h[0];if(j<h[1]||null==j)j=h[1];if(k<h[0]||null==k)k=h[0];if(f>h[1]||null==f)f=h[1]}this._boundingBox=[[t,j],[k,f]];
if(this.markerRenderer.show&&!n)for(c=0;c<b.length;c++)null!=b[c][0]&&null!=b[c][1]&&this.markerRenderer.draw(b[c][0],b[c][1],a,d.markerOptions)}a.restore()};e.jqplot.LineRenderer.prototype.drawShadow=function(){};e.jqplot.LinearAxisRenderer=function(){};e.jqplot.LinearAxisRenderer.prototype.init=function(a){e.extend(!0,this,a);a=this._dataBounds;for(var b=0;b<this._series.length;b++)for(var d=this._series[b]._plotData,c=0;c<d.length;c++)if("xaxis"==this.name||"x2axis"==this.name){if(null!=d[c][0]&&
d[c][0]<a.min||null==a.min)a.min=d[c][0];if(null!=d[c][0]&&d[c][0]>a.max||null==a.max)a.max=d[c][0]}else{if(null!=d[c][1]&&d[c][1]<a.min||null==a.min)a.min=d[c][1];if(null!=d[c][1]&&d[c][1]>a.max||null==a.max)a.max=d[c][1]}};e.jqplot.LinearAxisRenderer.prototype.draw=function(a){if(this.show){this.renderer.createTicks.call(this);this._elem&&this._elem.empty();this._elem=e('<div class="jqplot-axis jqplot-'+this.name+'" style="position:absolute;"></div>');"xaxis"==this.name||"x2axis"==this.name?this._elem.width(this._plotDimensions.width):
this._elem.height(this._plotDimensions.height);this.labelOptions.axis=this.name;this._label=new this.labelRenderer(this.labelOptions);if(this._label.show){var b=this._label.draw(a);b.appendTo(this._elem)}for(var d=this._ticks,c=0;c<d.length;c++)if(b=d[c],b.showLabel&&(!b.isMinorTick||this.showMinorTicks))b=b.draw(a),b.appendTo(this._elem)}return this._elem};e.jqplot.LinearAxisRenderer.prototype.reset=function(){this.min=this._min;this.max=this._max;this.tickInterval=this._tickInterval;this.numberTicks=
this._numberTicks};e.jqplot.LinearAxisRenderer.prototype.set=function(){var a=0,b,d=0,c=0,f=null==this._label?!1:this._label.show;if(this.show){for(var n=this._ticks,k=0;k<n.length;k++)if(b=n[k],b.showLabel&&(!b.isMinorTick||this.showMinorTicks))b="xaxis"==this.name||"x2axis"==this.name?b._elem.outerHeight(!0):b._elem.outerWidth(!0),b>a&&(a=b);f&&(d=this._label._elem.outerWidth(!0),c=this._label._elem.outerHeight(!0));"xaxis"==this.name?this._elem.css({height:a+c+"px",left:"0px",bottom:"0px"}):"x2axis"==
this.name?(a+=c,this._elem.css({height:a+"px",left:"0px",top:"0px"})):("yaxis"==this.name?(a+=d,this._elem.css({width:a+"px",left:"0px",top:"0px"})):(a+=d,this._elem.css({width:a+"px",right:"0px",top:"0px"})),f&&this._label.constructor==e.jqplot.AxisLabelRenderer&&this._label._elem.css("width",d+"px"))}};e.jqplot.LinearAxisRenderer.prototype.createTicks=function(){var a=this.ticks,b=this.name,d=this._dataBounds,c,f,n=this.min;c=this.max;var k=this.numberTicks,t=this.tickInterval;if(a.length){for(f=
0;f<a.length;f++)c=a[f],n=new this.tickRenderer(this.tickOptions),c.constructor==Array?(n.value=c[0],n.label=c[1],n.setTick(c[0],this.name)):(n.value=c,n.setTick(c,this.name)),this._ticks.push(n);this.numberTicks=a.length;this.min=this._ticks[0].value;this.max=this._ticks[this.numberTicks-1].value;this.tickInterval=(this.max-this.min)/(this.numberTicks-1)}else{b="xaxis"==b||"x2axis"==b?this._plotDimensions.width:this._plotDimensions.height;!this.autoscale&&(null!=this.min&&null!=this.max&&null!=this.numberTicks)&&
(this.tickInterval=null);a=null!=this.min?this.min:d.min;d=null!=this.max?this.max:d.max;a==d&&(f=0.05,0<a&&(f=Math.max(Math.log(a)/Math.LN10,0.05)),a-=f,d+=f);var j=d-a;if(this.autoscale&&null==this.min&&null==this.max){var h=!1,p=!1;for(f=0;f<this._series.length;f++){var g=this._series[f];if(this.name==("x"==g.fillAxis?g._xaxis.name:g._yaxis.name)){for(var q=g._plotValues[g.fillAxis],l=q[0],r=q[0],u=1;u<q.length;u++)q[u]<l?l=q[u]:q[u]>r&&(r=q[u]);q=(r-l)/r;g.renderer.constructor==e.jqplot.BarRenderer?
0<=l&&(g.fillToZero||0.1<q)?h=!0:(h=!1,p=g.fill&&g.fillToZero&&0>l&&0<r?!0:!1):g.fill?0<=l&&(g.fillToZero||0.1<q)?h=!0:0>l&&0<r&&g.fillToZero?(h=!1,p=!0):p=h=!1:0>l&&(h=!1)}}h?(this.numberTicks=2+Math.ceil((b-(this.tickSpacing-1))/this.tickSpacing),n=this.min=0,d/=this.numberTicks-1,b=Math.pow(10,Math.abs(Math.floor(Math.log(d)/Math.LN10))),d/b==parseInt(d/b,10)&&(d+=b),this.tickInterval=Math.ceil(d/b)*b,this.max=this.tickInterval*(this.numberTicks-1)):p?(this.numberTicks=2+Math.ceil((b-(this.tickSpacing-
1))/this.tickSpacing),f=Math.ceil(Math.abs(a)/j*(this.numberTicks-1)),j=this.numberTicks-1-f,d=Math.max(Math.abs(a/f),Math.abs(d/j)),b=Math.pow(10,Math.abs(Math.floor(Math.log(d)/Math.LN10))),this.tickInterval=Math.ceil(d/b)*b,this.max=this.tickInterval*j,this.min=-this.tickInterval*f):(null==this.numberTicks&&(this.numberTicks=this.tickInterval?3+Math.ceil(j/this.tickInterval):2+Math.ceil((b-(this.tickSpacing-1))/this.tickSpacing)),null==this.tickInterval?(d=j/(this.numberTicks-1),b=1>d?Math.pow(10,
Math.abs(Math.floor(Math.log(d)/Math.LN10))):1,this.tickInterval=Math.ceil(d*b*this.pad)/b):b=1/this.tickInterval,d=this.tickInterval*(this.numberTicks-1),f=(d-j)/2,null==this.min&&(this.min=Math.floor(b*(a-f))/b),null==this.max&&(this.max=this.min+d))}else a=null!=this.min?this.min:a-j*(this.padMin-1),d=null!=this.max?this.max:d+j*(this.padMax-1),this.min=a,this.max=d,j=this.max-this.min,null==this.numberTicks&&(null!=this.tickInterval?(this.numberTicks=Math.ceil((this.max-this.min)/this.tickInterval)+
1,this.max=this.min+this.tickInterval*(this.numberTicks-1)):this.numberTicks=100<b?parseInt(3+(b-100)/75,10):2),null==this.tickInterval&&(this.tickInterval=j/(this.numberTicks-1));this.renderer.constructor==e.jqplot.LinearAxisRenderer&&(b=(new this.tickRenderer(this.tickOptions)).formatString||e.jqplot.config.defaultTickFormatString,b=b.match(e.jqplot.sprintf.regex)[0],a=0,b&&(-1<b.search(/[fFeEgGpP]/)?a=(a=b.match(/\%\.(\d{0,})?[eEfFgGpP]/))?parseInt(a[1],10):6:-1<b.search(/[di]/)&&(a=0),b=Math.pow(10,
-a),this.tickInterval<b&&(null==k&&null==t)&&(this.tickInterval=b,null==c&&null==n?(this.min=Math.floor(this._dataBounds.min/b)*b,this.min==this._dataBounds.min&&(this.min=this._dataBounds.min-this.tickInterval),this.max=Math.ceil(this._dataBounds.max/b)*b,this.max==this._dataBounds.max&&(this.max=this._dataBounds.max+this.tickInterval),n=(this.max-this.min)/this.tickInterval,n=n.toFixed(11),n=Math.ceil(n),this.numberTicks=n+1):null==c?(n=(this._dataBounds.max-this.min)/this.tickInterval,n=n.toFixed(11),
this.numberTicks=Math.ceil(n)+2,this.max=this.min+this.tickInterval*(this.numberTicks-1)):null==n?(n=(this.max-this._dataBounds.min)/this.tickInterval,n=n.toFixed(11),this.numberTicks=Math.ceil(n)+2,this.min=this.max-this.tickInterval*(this.numberTicks-1)):(this.numberTicks=Math.ceil((c-n)/this.tickInterval)+1,this.min=Math.floor(n*Math.pow(10,a))/Math.pow(10,a),this.max=Math.ceil(c*Math.pow(10,a))/Math.pow(10,a),this.numberTicks=Math.ceil((this.max-this.min)/this.tickInterval)+1))));for(f=0;f<this.numberTicks;f++)c=
this.min+f*this.tickInterval,n=new this.tickRenderer(this.tickOptions),n.setTick(c,this.name),this._ticks.push(n)}};e.jqplot.LinearAxisRenderer.prototype.pack=function(a,b){var d=this._ticks,c=this.max,f=this.min,n=b.max,k=b.min,t=null==this._label?!1:this._label.show,j;for(j in a)this._elem.css(j,a[j]);this._offsets=b;var h=n-k,p=c-f;this.p2u=function(a){return(a-k)*p/h+f};this.u2p=function(a){return(a-f)*h/p+k};"xaxis"==this.name||"x2axis"==this.name?(this.series_u2p=function(a){return(a-f)*h/p},
this.series_p2u=function(a){return a*p/h+f}):(this.series_u2p=function(a){return(a-c)*h/p},this.series_p2u=function(a){return a*p/h+c});if(this.show)if("xaxis"==this.name||"x2axis"==this.name){for(i=0;i<d.length;i++)if(j=d[i],j.show&&j.showLabel){var g;if(j.constructor==e.jqplot.CanvasAxisTickRenderer&&j.angle)switch(g="xaxis"==this.name?1:-1,j.labelPosition){case "auto":g=0>g*j.angle?-j.getWidth()+j._textRenderer.height*Math.sin(-j._textRenderer.angle)/2:-j._textRenderer.height*Math.sin(j._textRenderer.angle)/
2;break;case "end":g=-j.getWidth()+j._textRenderer.height*Math.sin(-j._textRenderer.angle)/2;break;case "start":g=-j._textRenderer.height*Math.sin(j._textRenderer.angle)/2;break;case "middle":g=-j.getWidth()/2+j._textRenderer.height*Math.sin(-j._textRenderer.angle)/2;break;default:g=-j.getWidth()/2+j._textRenderer.height*Math.sin(-j._textRenderer.angle)/2}else g=-j.getWidth()/2;g=this.u2p(j.value)+g+"px";j._elem.css("left",g);j.pack()}t&&(n=this._label._elem.outerWidth(!0),this._label._elem.css("left",
k+h/2-n/2+"px"),"xaxis"==this.name?this._label._elem.css("bottom","0px"):this._label._elem.css("top","0px"),this._label.pack())}else{for(i=0;i<d.length;i++)if(j=d[i],j.show&&j.showLabel){if(j.constructor==e.jqplot.CanvasAxisTickRenderer&&j.angle)switch(g="yaxis"==this.name?1:-1,j.labelPosition){case "auto":case "end":g=0>g*j.angle?-j._textRenderer.height*Math.cos(-j._textRenderer.angle)/2:-j.getHeight()+j._textRenderer.height*Math.cos(j._textRenderer.angle)/2;break;case "start":g=0<j.angle?-j._textRenderer.height*
Math.cos(-j._textRenderer.angle)/2:-j.getHeight()+j._textRenderer.height*Math.cos(j._textRenderer.angle)/2;break;case "middle":g=-j.getHeight()/2;break;default:g=-j.getHeight()/2}else g=-j.getHeight()/2;g=this.u2p(j.value)+g+"px";j._elem.css("top",g);j.pack()}t&&(d=this._label._elem.outerHeight(!0),this._label._elem.css("top",n-h/2-d/2+"px"),"yaxis"==this.name?this._label._elem.css("left","0px"):this._label._elem.css("right","0px"),this._label.pack())}};e.jqplot.MarkerRenderer=function(a){this.show=
!0;this.style="filledCircle";this.lineWidth=2;this.size=9;this.color="#666666";this.shadow=!0;this.shadowAngle=45;this.shadowOffset=1;this.shadowDepth=3;this.shadowAlpha="0.07";this.shadowRenderer=new e.jqplot.ShadowRenderer;this.shapeRenderer=new e.jqplot.ShapeRenderer;e.extend(!0,this,a)};e.jqplot.MarkerRenderer.prototype.init=function(a){e.extend(!0,this,a);a={angle:this.shadowAngle,offset:this.shadowOffset,alpha:this.shadowAlpha,lineWidth:this.lineWidth,depth:this.shadowDepth,closePath:!0};-1!=
this.style.indexOf("filled")&&(a.fill=!0);-1!=this.style.indexOf("ircle")&&(a.isarc=!0,a.closePath=!1);this.shadowRenderer.init(a);a={fill:!1,isarc:!1,strokeStyle:this.color,fillStyle:this.color,lineWidth:this.lineWidth,closePath:!0};-1!=this.style.indexOf("filled")&&(a.fill=!0);-1!=this.style.indexOf("ircle")&&(a.isarc=!0,a.closePath=!1);this.shapeRenderer.init(a)};e.jqplot.MarkerRenderer.prototype.drawDiamond=function(a,b,d,c,f){c=this.size/2/1.2;var e=1.2*(this.size/2);a=[[a-c,b],[a,b+e],[a+c,
b],[a,b-e]];this.shadow&&this.shadowRenderer.draw(d,a);this.shapeRenderer.draw(d,a,f)};e.jqplot.MarkerRenderer.prototype.drawPlus=function(a,b,d){var c=1*(this.size/2),f=1*(this.size/2),f=[[a,b-f],[a,b+f]];a=[[a+c,b],[a-c,b]];b=e.extend(!0,{},this.options,{closePath:!1});this.shadow&&(this.shadowRenderer.draw(d,f,{closePath:!1}),this.shadowRenderer.draw(d,a,{closePath:!1}));this.shapeRenderer.draw(d,f,b);this.shapeRenderer.draw(d,a,b)};e.jqplot.MarkerRenderer.prototype.drawX=function(a,b,d){var c=
1*(this.size/2),f=1*(this.size/2),n=e.extend(!0,{},this.options,{closePath:!1}),k=[[a-c,b-f],[a+c,b+f]];a=[[a-c,b+f],[a+c,b-f]];this.shadow&&(this.shadowRenderer.draw(d,k,{closePath:!1}),this.shadowRenderer.draw(d,a,{closePath:!1}));this.shapeRenderer.draw(d,k,n);this.shapeRenderer.draw(d,a,n)};e.jqplot.MarkerRenderer.prototype.drawDash=function(a,b,d,c,f){c=1*(this.size/2);a=[[a-c,b],[a+c,b]];this.shadow&&this.shadowRenderer.draw(d,a);this.shapeRenderer.draw(d,a,f)};e.jqplot.MarkerRenderer.prototype.drawSquare=
function(a,b,d,c,f){c=this.size/2/1;var e=1*(this.size/2);a=[[a-c,b-e],[a-c,b+e],[a+c,b+e],[a+c,b-e]];this.shadow&&this.shadowRenderer.draw(d,a);this.shapeRenderer.draw(d,a,f)};e.jqplot.MarkerRenderer.prototype.drawCircle=function(a,b,d,c,f){a=[a,b,this.size/2,0,2*Math.PI,!0];this.shadow&&this.shadowRenderer.draw(d,a);this.shapeRenderer.draw(d,a,f)};e.jqplot.MarkerRenderer.prototype.draw=function(a,b,d,c){c=c||{};if(null==c.show||!1!=c.show)switch(c.color&&!c.fillStyle&&(c.fillStyle=c.color),c.color&&
!c.strokeStyle&&(c.strokeStyle=c.color),this.style){case "diamond":this.drawDiamond(a,b,d,!1,c);break;case "filledDiamond":this.drawDiamond(a,b,d,!0,c);break;case "circle":this.drawCircle(a,b,d,!1,c);break;case "filledCircle":this.drawCircle(a,b,d,!0,c);break;case "square":this.drawSquare(a,b,d,!1,c);break;case "filledSquare":this.drawSquare(a,b,d,!0,c);break;case "x":this.drawX(a,b,d,!0,c);break;case "plus":this.drawPlus(a,b,d,!0,c);break;case "dash":this.drawDash(a,b,d,!0,c);break;default:this.drawDiamond(a,
b,d,!1,c)}};e.jqplot.ShadowRenderer=function(a){this.angle=45;this.offset=1;this.alpha=0.07;this.lineWidth=1.5;this.lineJoin="miter";this.lineCap="round";this.fill=this.closePath=!1;this.depth=3;this.strokeStyle="rgba(0,0,0,0.1)";this.isarc=!1;e.extend(!0,this,a)};e.jqplot.ShadowRenderer.prototype.init=function(a){e.extend(!0,this,a)};e.jqplot.ShadowRenderer.prototype.draw=function(a,b,d){a.save();var c=null!=d?d:{};d=null!=c.fill?c.fill:this.fill;var f=null!=c.closePath?c.closePath:this.closePath,
e=null!=c.offset?c.offset:this.offset,k=null!=c.alpha?c.alpha:this.alpha,t=null!=c.depth?c.depth:this.depth,j=null!=c.isarc?c.isarc:this.isarc;a.lineWidth=null!=c.lineWidth?c.lineWidth:this.lineWidth;a.lineJoin=null!=c.lineJoin?c.lineJoin:this.lineJoin;a.lineCap=null!=c.lineCap?c.lineCap:this.lineCap;a.strokeStyle=c.strokeStyle||this.strokeStyle||"rgba(0,0,0,"+k+")";a.fillStyle=c.fillStyle||this.fillStyle||"rgba(0,0,0,"+k+")";for(c=0;c<t;c++){a.translate(Math.cos(this.angle*Math.PI/180)*e,Math.sin(this.angle*
Math.PI/180)*e);a.beginPath();if(j)a.arc(b[0],b[1],b[2],b[3],b[4],!0);else for(var k=!0,h=0;h<b.length;h++)null!=b[h][0]&&null!=b[h][1]?k?(a.moveTo(b[h][0],b[h][1]),k=!1):a.lineTo(b[h][0],b[h][1]):k=!0;f&&a.closePath();d?a.fill():a.stroke()}a.restore()};e.jqplot.ShapeRenderer=function(a){this.lineWidth=1.5;this.lineJoin="miter";this.lineCap="round";this.clearRect=this.strokeRect=this.fillRect=this.isarc=this.fill=this.closePath=!1;this.fillStyle=this.strokeStyle="#999999";e.extend(!0,this,a)};e.jqplot.ShapeRenderer.prototype.init=
function(a){e.extend(!0,this,a)};e.jqplot.ShapeRenderer.prototype.draw=function(a,b,d){a.save();var c=null!=d?d:{};d=null!=c.fill?c.fill:this.fill;var f=null!=c.closePath?c.closePath:this.closePath,e=null!=c.fillRect?c.fillRect:this.fillRect,k=null!=c.strokeRect?c.strokeRect:this.strokeRect,t=null!=c.clearRect?c.clearRect:this.clearRect,j=null!=c.isarc?c.isarc:this.isarc;a.lineWidth=c.lineWidth||this.lineWidth;a.lineJoin=c.lineJoing||this.lineJoin;a.lineCap=c.lineCap||this.lineCap;a.strokeStyle=c.strokeStyle||
c.color||this.strokeStyle;a.fillStyle=c.fillStyle||this.fillStyle;a.beginPath();if(j)a.arc(b[0],b[1],b[2],b[3],b[4],!0),f&&a.closePath(),d?a.fill():a.stroke();else if(t)a.clearRect(b[0],b[1],b[2],b[3]);else if(e||k){if(e&&a.fillRect(b[0],b[1],b[2],b[3]),k){a.strokeRect(b[0],b[1],b[2],b[3]);a.restore();return}}else{c=!0;for(e=0;e<b.length;e++)null!=b[e][0]&&null!=b[e][1]?c?(a.moveTo(b[e][0],b[e][1]),c=!1):a.lineTo(b[e][0],b[e][1]):c=!0;f&&a.closePath();d?a.fill():a.stroke()}a.restore()};e.jqplot.TableLegendRenderer=
function(){};e.jqplot.TableLegendRenderer.prototype.init=function(a){e.extend(!0,this,a)};e.jqplot.TableLegendRenderer.prototype.addrow=function(a,b,d,c){d=d?this.rowSpacing:"0";c=c?e('<tr class="jqplot-table-legend"></tr>').prependTo(this._elem):e('<tr class="jqplot-table-legend"></tr>').appendTo(this._elem);this.showSwatches&&e('<td class="jqplot-table-legend" style="text-align:center;padding-top:'+d+';"><div><div class="jqplot-table-legend-swatch" style="background-color:'+b+";border-color:"+b+
';"></div></div></td>').appendTo(c);this.showLabels&&(b=e('<td class="jqplot-table-legend" style="padding-top:'+d+';"></td>'),b.appendTo(c),this.escapeHtml?b.text(a):b.html(a))};e.jqplot.TableLegendRenderer.prototype.draw=function(){if(this.show){var a=this._series;this._elem=e('<table id= "legendTable" class="jqplot-table-legend"  style="position: absolute; bottom: 0px;"></table>');for(var b=!1,d=!1,c=0;c<a.length;c++){s=a[c];if(s._stack||s.renderer.constructor==e.jqplot.BezierCurveRenderer)d=!0;
if(s.show&&s.showLabel){var f=this.labels[c]||s.label.toString();if(f){var n=s.color;d&&c<a.length-1?b=!0:d&&c==a.length-1&&(b=!1);this.renderer.addrow.call(this,f,n,b,d);b=!0}for(f=0;f<e.jqplot.addLegendRowHooks.length;f++)if(n=e.jqplot.addLegendRowHooks[f].call(this,s))this.renderer.addrow.call(this,n.label,n.color,b),b=!0}}}return this._elem};e.jqplot.TableLegendRenderer.prototype.pack=function(a){if(this.show)if("insideGrid"==this.placement)switch(this.location){case "nw":var b=a.left,d=a.top;
this._elem.css("left",b);this._elem.css("top",d);break;case "n":b=(a.left+(this._plotDimensions.width-a.right))/2-this.getWidth()/2;d=a.top;this._elem.css("left",b);this._elem.css("top",d);break;case "ne":b=a.right;d=a.top;this._elem.css({right:b,top:d});break;case "e":b=a.right;d=(a.top+(this._plotDimensions.height-a.bottom))/2-this.getHeight()/2;this._elem.css({right:b,top:d});break;case "se":b=a.right;d=a.bottom;this._elem.css({right:b,bottom:d});break;case "s":b=(a.left+(this._plotDimensions.width-
a.right))/2-this.getWidth()/2;d=a.bottom;this._elem.css({left:b,bottom:d});break;case "sw":b=a.left;d=a.bottom;this._elem.css({left:b,bottom:d});break;case "w":b=a.left;d=(a.top+(this._plotDimensions.height-a.bottom))/2-this.getHeight()/2;this._elem.css({left:b,top:d});break;default:b=a.right,d=a.bottom,this._elem.css({right:b,bottom:d})}else if("outside"==this.placement)switch(this.location){case "nw":b=this._plotDimensions.width-a.left;d=a.top;this._elem.css("right",b);this._elem.css("top",d);break;
case "n":b=(a.left+(this._plotDimensions.width-a.right))/2-this.getWidth()/2;d=this._plotDimensions.height-a.top;this._elem.css("left",b);this._elem.css("bottom",d);break;case "ne":b=this._plotDimensions.width-a.right;d=a.top;this._elem.css({left:b,top:d});break;case "e":b=this._plotDimensions.width-a.right;d=(a.top+(this._plotDimensions.height-a.bottom))/2-this.getHeight()/2;this._elem.css({left:b,top:d});break;case "se":b=this._plotDimensions.width-a.right;d=a.bottom;this._elem.css({left:b,bottom:d});
break;case "s":b=(a.left+(this._plotDimensions.width-a.right))/2-this.getWidth()/2;d=this._plotDimensions.height-a.bottom;this._elem.css({left:b,top:d});break;case "sw":b=this._plotDimensions.width-a.left;d=a.bottom;this._elem.css({right:b,bottom:d});break;case "w":b=this._plotDimensions.width-a.left;d=(a.top+(this._plotDimensions.height-a.bottom))/2-this.getHeight()/2;this._elem.css({right:b,top:d});break;default:b=a.right,d=a.bottom,this._elem.css({right:b,bottom:d})}else switch(this.location){case "nw":this._elem.css({left:0,
top:a.top});break;case "n":b=(a.left+(this._plotDimensions.width-a.right))/2-this.getWidth()/2;this._elem.css({left:b,top:a.top});break;case "ne":this._elem.css({right:0,top:a.top});break;case "e":d=(a.top+(this._plotDimensions.height-a.bottom))/2-this.getHeight()/2;this._elem.css({right:a.right,top:d});break;case "se":this._elem.css({right:a.right,bottom:a.bottom});break;case "s":b=(a.left+(this._plotDimensions.width-a.right))/2-this.getWidth()/2;this._elem.css({left:b,bottom:a.bottom});break;case "sw":this._elem.css({left:a.left,
bottom:a.bottom});break;case "w":d=(a.top+(this._plotDimensions.height-a.bottom))/2-this.getHeight()/2;this._elem.css({left:a.left,top:d});break;default:this._elem.css({right:a.right,bottom:a.bottom})}};e.jqplot.ThemeEngine=function(){this.themes={};this.activeTheme=null};e.jqplot.ThemeEngine.prototype.init=function(){var a=new e.jqplot.Theme({_name:"Default"}),b,d;for(b in a.target)a.target[b]="textColor"==b?this.target.css("color"):this.target.css(b);if(this.title.show&&this.title._elem)for(b in a.title)a.title[b]=
"textColor"==b?this.title._elem.css("color"):this.title._elem.css(b);for(b in a.grid)a.grid[b]=this.grid[b];null==a.grid.backgroundColor&&null!=this.grid.background&&(a.grid.backgroundColor=this.grid.background);if(this.legend.show&&this.legend._elem)for(b in a.legend)a.legend[b]="textColor"==b?this.legend._elem.css("color"):this.legend._elem.css(b);var c;for(d=0;d<this.series.length;d++)for(b in c=this.series[d],c.renderer.constructor==e.jqplot.LineRenderer?a.series.push(new U):c.renderer.constructor==
e.jqplot.BarRenderer?a.series.push(new V):c.renderer.constructor==e.jqplot.PieRenderer?a.series.push(new W):c.renderer.constructor==e.jqplot.DonutRenderer?a.series.push(new X):c.renderer.constructor==e.jqplot.FunnelRenderer?a.series.push(new Y):c.renderer.constructor==e.jqplot.MeterGaugeRenderer?a.series.push(new Z):a.series.push({}),a.series[d])a.series[d][b]=c[b];for(b in this.axes){c=this.axes[b];d=a.axes[b]=new $;d.borderColor=c.borderColor;d.borderWidth=c.borderWidth;if(c._ticks&&c._ticks[0])for(nn in d.ticks)c._ticks[0].hasOwnProperty(nn)?
d.ticks[nn]=c._ticks[0][nn]:c._ticks[0]._elem&&(d.ticks[nn]=c._ticks[0]._elem.css(nn));if(c._label&&c._label.show)for(nn in d.label)c._label[nn]?d.label[nn]=c._label[nn]:c._label._elem&&(d.label[nn]="textColor"==nn?c._label._elem.css("color"):c._label._elem.css(nn))}this.themeEngine._add(a);this.themeEngine.activeTheme=this.themeEngine.themes[a._name]};e.jqplot.ThemeEngine.prototype.get=function(a){return a?this.themes[a]:this.activeTheme};e.jqplot.ThemeEngine.prototype.getThemeNames=function(){var a=
[],b;for(b in this.themes)a.push(b);return a.sort(L)};e.jqplot.ThemeEngine.prototype.getThemes=function(){var a=[],b=[],d;for(d in this.themes)a.push(d);a.sort(L);for(d=0;d<a.length;d++)b.push(this.themes[a[d]]);return b};e.jqplot.ThemeEngine.prototype.activate=function(a,b){var d=!1;!b&&(this.activeTheme&&this.activeTheme._name)&&(b=this.activeTheme._name);if(this.themes.hasOwnProperty(b)){var c=this.themes[b];this.activeTheme=c;var f;f=["xaxis","x2axis","yaxis","y2axis"];for(t=0;t<f.length;t++){var n=
f[t];null!=c.axesStyles.borderColor&&(a.axes[n].borderColor=c.axesStyles.borderColor);null!=c.axesStyles.borderWidth&&(a.axes[n].borderWidth=c.axesStyles.borderWidth)}for(axname in a.axes)if(t=a.axes[axname],t.show){n=e.jqplot.extend(!0,{},c.axes[axname]||{},c.axesStyles);null!=n.borderColor&&(t.borderColor=n.borderColor,d=!0);null!=n.borderWidth&&(t.borderWidth=n.borderWidth,d=!0);if(t._ticks&&t._ticks[0])for(nn in n.ticks)f=n.ticks[nn],null!=f&&(t.tickOptions[nn]=f,t._ticks=[],d=!0);if(t._label&&
t._label.show)for(nn in n.label)f=n.label[nn],null!=f&&(t.labelOptions[nn]=f,d=!0)}for(var k in c.grid)null!=c.grid[k]&&(a.grid[k]=c.grid[k]);d||a.grid.draw();if(a.legend.show)for(k in c.legend)null!=c.legend[k]&&(a.legend[k]=c.legend[k]);if(a.title.show)for(k in c.title)null!=c.title[k]&&(a.title[k]=c.title[k]);var t;for(t=0;t<c.series.length;t++)for(k in c.series[t])f=null!=c.seriesStyles[k]?c.seriesStyles[k]:c.series[t][k],null!=f&&("color"==k?(a.series[t].renderer.shapeRenderer.fillStyle=f,a.series[t].renderer.shapeRenderer.strokeStyle=
f,a.series[t][k]=f):"lineWidth"==k?(a.series[t].renderer.shapeRenderer.lineWidth=f,a.series[t][k]=f):"markerOptions"==k?(I(a.series[t].markerOptions,f),I(a.series[t].markerRenderer,f)):a.series[t][k]=f,d=!0);d&&(a.target.empty(),a.draw());for(k in c.target)null!=c.target[k]&&a.target.css(k,c.target[k])}else throw Error("No theme of that name");};e.jqplot.ThemeEngine.prototype._add=function(a,b){b&&(a._name=b);a._name||(a._name=Date.parse(new Date));if(this.themes.hasOwnProperty(a._name))throw Error("jqplot.ThemeEngine Error: Theme already in use");
this.themes[a._name]=a};e.jqplot.ThemeEngine.prototype.remove=function(a){return"Default"==a?!1:delete this.themes[a]};e.jqplot.ThemeEngine.prototype.newTheme=function(a,b){"object"==typeof a&&(b=b||a,a=null);a=b&&b._name?b._name:a||Date.parse(new Date);var d=this.copy(this.themes.Default._name,a);e.jqplot.extend(d,b);return d};e.jqplot.clone=H;e.jqplot.merge=I;e.jqplot.extend=function(){var a=arguments[0]||{},b=1,d=arguments.length,c=!1,f;"boolean"===typeof a&&(c=a,a=arguments[1]||{},b=2);for("object"!==
typeof a&&"[object Function]"===!toString.call(a)&&(a={});b<d;b++)if(null!=(f=arguments[b]))for(var n in f){var k=a[n],t=f[n];a!==t&&(c&&t&&"object"===typeof t&&!t.nodeType?a[n]=e.jqplot.extend(c,k||(null!=t.length?[]:{}),t):t!==x&&(a[n]=t))}return a};e.jqplot.ThemeEngine.prototype.rename=function(a,b){if("Default"==a||"Default"==b)throw Error("jqplot.ThemeEngine Error: Cannot rename from/to Default");if(this.themes.hasOwnProperty(b))throw Error("jqplot.ThemeEngine Error: New name already in use.");
if(this.themes.hasOwnProperty(a)){var d=this.copy(a,b);this.remove(a);return d}throw Error("jqplot.ThemeEngine Error: Old name or new name invalid");};e.jqplot.ThemeEngine.prototype.copy=function(a,b,d){if("Default"==b)throw Error("jqplot.ThemeEngine Error: Cannot copy over Default theme");if(!this.themes.hasOwnProperty(a))throw Error("jqplot.ThemeEngine Error: Source name invalid");if(this.themes.hasOwnProperty(b))throw Error("jqplot.ThemeEngine Error: Target name invalid");a=H(this.themes[a]);a._name=
b;e.jqplot.extend(!0,a,d);this._add(a);return a};e.jqplot.Theme=function(a,b){"object"==typeof a&&(b=b||a,a=null);this._name=a=a||Date.parse(new Date);this.target={backgroundColor:null};this.legend={textColor:null,fontFamily:null,fontSize:null,border:null,background:null};this.title={textColor:null,fontFamily:null,fontSize:null,textAlign:null};this.seriesStyles={};this.series=[];this.grid={drawGridlines:null,gridLineColor:null,gridLineWidth:null,backgroundColor:null,borderColor:null,borderWidth:null,
shadow:null};this.axesStyles={label:{},ticks:{}};this.axes={};"string"==typeof b?this._name=b:"object"==typeof b&&e.jqplot.extend(!0,this,b)};var $=function(){this.borderWidth=this.borderColor=null;this.ticks=new aa;this.label=new ba},aa=function(){this.fontFamily=this.fontSize=this.whiteSpace=this.textColor=this.size=this.showMark=this.showLabel=this.showGridline=this.show=null},ba=function(){this.fontWeight=this.fontFamily=this.fontSize=this.whiteSpace=this.textColor=null},U=function(){this.showMarker=
this.fillColor=this.shadow=this.lineWidth=this.color=null;this.markerOptions=new ca},ca=function(){this.shadow=this.color=this.size=this.lineWidth=this.style=this.show=null},V=function(){this.highlightColors=this.barWidth=this.barMargin=this.barPadding=this.shadow=this.lineWidth=this.seriesColors=this.color=null},W=function(){this.highlightColors=this.lineWidth=this.startAngle=this.shadow=this.fill=this.sliceMargin=this.padding=this.seriesColors=null},X=function(){this.highlightColors=this.ringMargin=
this.thickness=this.innerDiameter=this.lineWidth=this.startAngle=this.shadow=this.fill=this.sliceMargin=this.padding=this.seriesColors=null},Y=function(){this.highlightColors=this.seriesColors=this.sectionMargin=this.padding=this.shadow=this.lineWidth=this.color=null},Z=function(){this.needlePad=this.needleThickness=this.hubRadius=this.intervalOuterRadius=this.intervalInnerRadius=this.intervalColors=this.ringWidth=this.tickColor=this.ringColor=this.backgroundColor=this.padding=null};e.jqplot.sprintf=
function(){function a(a,b,c,d){b=a.length>=b?"":Array(1+b-a.length>>>0).join(c);return d?a+b:b+a}function b(b,c,d,f,e,p){var g=f-b.length;if(0<g){var q=" ";p&&(q="&nbsp;");b=d||!e?a(b,f,q,d):b.slice(0,c.length)+a("",g,"0",!0)+b.slice(c.length)}return b}function d(c,d,f,e,h,p,g,q){c>>>=0;f=f&&c&&{2:"0b",8:"0",16:"0x"}[d]||"";c=f+a(c.toString(d),p||0,"0",!1);return b(c,f,e,h,g,q)}var c=arguments,f=0;return c[f++].replace(e.jqplot.sprintf.regex,function(e,k,t,j,h,p,g){if("%%"==e)return"%";var q=!1,l=
"",r=!1,u=!1;h=!1;for(var x=0;t&&x<t.length;x++)switch(t.charAt(x)){case " ":l=" ";break;case "+":l="+";break;case "-":q=!0;break;case "0":r=!0;break;case "#":u=!0;break;case "&":h=!0}j=j?"*"==j?+c[f++]:"*"==j.charAt(0)?+c[j.slice(1,-1)]:+j:0;0>j&&(j=-j,q=!0);if(!isFinite(j))throw Error("$.jqplot.sprintf: (minimum-)width must be finite");p=p?"*"==p?+c[f++]:"*"==p.charAt(0)?+c[p.slice(1,-1)]:+p:-1<"fFeE".indexOf(g)?6:"d"==g?0:void 0;k=k?c[k.slice(0,-1)]:c[f++];switch(g){case "s":if(null==k)return"";
g=String(k);null!=p&&(g=g.slice(0,p));return b(g,"",q,j,r,h);case "c":return g=String.fromCharCode(+k),null!=p&&(g=g.slice(0,p)),b(g,"",q,j,r,h);case "b":return d(k,2,u,q,j,p,r,h);case "o":return d(k,8,u,q,j,p,r,h);case "x":return d(k,16,u,q,j,p,r,h);case "X":return d(k,16,u,q,j,p,r,h).toUpperCase();case "u":return d(k,10,u,q,j,p,r,h);case "i":e=parseInt(+k,10);if(isNaN(e))return"";l=0>e?"-":l;k=l+a(String(Math.abs(e)),p,"0",!1);return b(k,l,q,j,r,h);case "d":e=Math.round(+k);if(isNaN(e))return"";
l=0>e?"-":l;k=l+a(String(Math.abs(e)),p,"0",!1);return b(k,l,q,j,r,h);case "e":case "E":case "f":case "F":case "g":case "G":e=+k;if(isNaN(e))return"";l=0>e?"-":l;k=["toExponential","toFixed","toPrecision"]["efg".indexOf(g.toLowerCase())];g=["toString","toUpperCase"]["eEfFgG".indexOf(g)%2];k=l+Math.abs(e)[k](p);return b(k,l,q,j,r,h)[g]();case "p":case "P":e=+k;if(isNaN(e))return"";l=0>e?"-":l;t=String(Number(Math.abs(e)).toExponential()).split(/e|E/);k=-1!=t[0].indexOf(".")?t[0].length-1:t[0].length;
t=0>t[1]?-t[1]-1:0;k=1>Math.abs(e)?k+t<=p?l+Math.abs(e).toPrecision(k):k<=p-1?l+Math.abs(e).toExponential(k-1):l+Math.abs(e).toExponential(p-1):l+Math.abs(e).toPrecision(k<=p?k:p);g=["toString","toUpperCase"]["pP".indexOf(g)%2];return b(k,l,q,j,r,h)[g]();case "n":return"";default:return e}})};e.jqplot.sprintf.regex=/%%|%(\d+\$)?([-+#0& ]*)(\*\d+\$|\*|\d+)?(\.(\*\d+\$|\*|\d+))?([nAscboxXuidfegpEGP])/g})(jQuery);