/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2016-09-27 06:10:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.queryio.core.bean.Node;
import com.queryio.core.bean.Host;
import java.util.Set;
import java.util.ArrayList;
import org.apache.jasper.tagplugins.jstl.core.ForEach;
import java.util.HashMap;
import com.queryio.core.conf.RemoteManager;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--\n");
      out.write("<link rel=\"stylesheet\" href=\"styles/menu.css\" type=\"text/css\" />\n");
      out.write("<script src=\"scripts/navbar.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/jquery-1.7.2.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"styles/jquery.jqplot.min.css\" type=\"text/css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"styles/jquery.dataTables.css\" type=\"text/css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"styles/dashboard.css\" type=\"text/css\" />\n");
      out.write("<script src=\"scripts/jquery.treeTable.js\"></script>\n");
      out.write("<script src=\"scripts/jquery.jqplot.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"scripts/dashboard.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"styles/tree.css\" type=\"text/css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"styles/jquery.treeTable.css\" type=\"text/css\" />\n");
      out.write("\t\t<script src=\"scripts/jquery-ui-1.8.20.custom.min.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"scripts/jquery.dataTables.js\"></script>\n");
      out.write("-->\t\t \n");
      out.write(" <script type=\"text/javascript\">\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write(" <div id=\"menu_old\" style=\"margin-bottom: -8px;\">\n");
      out.write(" \n");
 ArrayList hostIPList = RemoteManager.getAllHostDetails();	
      out.write("\n");
      out.write("<ul id=\"menu_ul\">\n");
      out.write("\t\n");
      out.write("\t<li onmouseout=\"showDropDown(1);\"  id=\"Data_li\" style=\"margin-left: 1px;\" class=\"first\"><a id=\"Data\"  href=\"javascript:Navbar.changeTab('Data Migration','data', 'data_migration');hideDropDown(1);\" >Data</a>\n");
      out.write("\t\t<ul>\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(1);\"><a id=\"Data Migration\" href=\"javascript:Navbar.changeTab('Data Migration','data', 'data_migration');hideDropDown(1);\" >Data Import/Export</a></li>\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(1);\"><a href=\"javascript:Navbar.changeTab('Data','data');hideDropDown(1);\">Data Browser</a></li>\n");
      out.write("\t\t\t<!-- <li onmouseout=\"showDropDown(1);\"><a href=\"javascript:Navbar.changeTab('AdHocDataDefinition','data','AdHocDataDefinition');hideDropDown(1);\">Manage Hive</a></li> -->\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(1);\"><a href=\"javascript:Navbar.changeTab('DB_Config','data','define_data_tags');hideDropDown(1);\">Data Tagging</a>\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(1);\"><a href=\"javascript:Navbar.changeTab('DB_Config','data','manage_hive');hideDropDown(1);\">Manage Hive</a>\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(1);\"><a href=\"javascript:Navbar.changeTab('DB_Config','data','manage_datasources');hideDropDown(1);\">Manage Datasource</a>\n");
      out.write("\t\t\t\t<!-- <ul>\n");
      out.write("\t\t\t\t\t<li onmouseout=\"showDropDown(1);\"><a id=\"DB_Config\" href=\"javascript:Navbar.changeTab('DB_Config','data', 'db_Config');hideDropDown(1);\">Manage Databases</a></li>\n");
      out.write("\t\t\t\t\t<li onmouseout=\"showDropDown(1);\"><a id=\"System Config\" href=\"javascript:Navbar.changeTab('Data Connections','data', 'data_connections');hideDropDown(1);\">Manage Datasource Connections</a></li>\n");
      out.write("\t\t\t\t\t<li onmouseout=\"showDropDown(1);\"><a  href=\"javascript:Navbar.changeTab('Tag Manager','data','tag_manager');hideDropDown(1);\">Manage Data Tagging</a></li>\n");
      out.write("\t\t\t\t\t<li onmouseout=\"showDropDown(1);\"><a  href=\"javascript:Navbar.changeTab('AdHocContent','data','AdHocContent');hideDropDown(1);\">Manage Content Processor</a></li>\n");
      out.write("\t\t\t\t</ul> -->\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</li>\n");
      out.write("\t\n");
      out.write("\t<li onmouseout=\"showDropDown(3);\" id=\"Analytics_li\">\n");
      out.write("\t\t<a href=\"javascript:Navbar.changeTab('Analytics','analytics');hideDropDown(3);\">Analytics</a>\n");
      out.write("\t\t<ul>\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(3);\"><a  href=\"javascript:Navbar.changeTab('Analytics','analytics');hideDropDown(3);\">Query Manager</a></li>\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(3);\"><a  href=\"javascript:Navbar.changeTab('QueryDesigner','analytics','QueryDesigner');hideDropDown(3);\">Query Designer</a></li>\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(3);\"><a  href=\"javascript:Navbar.changeTab('QueryViewer','analytics','QueryViewer');hideDropDown(3);\">Query Viewer</a></li>\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(3);\"><a  href=\"javascript:Navbar.changeTab('QuerySpreadSheet','analytics','QuerySpreadSheet');hideDropDown(3);\">SpreadSheet Viewer</a></li>\n");
      out.write("\t\t\t<!-- <li onmouseout=\"showDropDown(3);\"><a  href=\"javascript:Navbar.changeTab('QuerySpreadSheetSlick','analytics','QuerySpreadSheetSlick');hideDropDown(3);\">Slick SpreadSheet Viewer</a></li>-->\n");
      out.write("\t\t</ul>\n");
      out.write("\t</li>\n");
      out.write("\t\n");
      out.write("\t<li onmouseout=\"showDropDown(5);\" id=\"Dashboard_li\"><a id=\"Dashboard\" href=\"javascript:Navbar.changeTab('Dashboard','dashboard');hideDropDown(5)\" >Dashboard</a>\n");
      out.write("\t\t<ul>\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(5);\"><a href=\"javascript:Navbar.changeTab('Dashboard','dashboard');hideDropDown(5);\"> HDFS Overview</a></li>\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(5);\"><a href=\"javascript:Navbar.changeTab('Dashboard','dashboard','MapReduce');hideDropDown(5);\"> MapReduce Overview</a></li>\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(5);\" ><a href=\"javascript:Navbar.changeTab('Status','dashboard', 'system_monitor');hideDropDown(5);\">System Monitor</a></li>\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(5);\"><a href=\"javascript:Navbar.changeTab('All Alerts','dashboard', 'all_alerts');hideDropDown(5);\">System Alerts</a></li>\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(5);\"><a id=\"Configure Alerts\" href=\"javascript:Navbar.changeTab('Configure Alerts','dashboard', 'set_alerts');hideDropDown(5);\">Rules for Alerts</a></li>\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(5);\"><a id=\"Users\" href=\"javascript:Navbar.changeTab('Notifications','dashboard','notifications');hideDropDown(5);\"> Notifications</a></li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</li>\n");
      out.write("\t\n");
      out.write("\t<li onmouseout=\"showDropDown(7);\" id=\"Hadoop_li\"><a id=\"Hadoop\" href=\"javascript:Navbar.changeTab('Hadoop','Hadoop');hideDropDown(7);\">Hadoop</a>\n");
      out.write("\t\t<ul>\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(7);\" ><a href=\"javascript:Navbar.changeTab('Hadoop','Hadoop');hideDropDown(7);\">System Monitor</a></li>\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(7);\"><a id=\"System Config\" href=\"javascript:Navbar.changeTab('Hadoop','Hadoop','HDFS');hideDropDown(7);\"  >HDFS</a>\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li onmouseout=\"showDropDown(7);\"><a href=\"javascript:Navbar.changeTab('Hadoop','Hadoop','HDFS');hideDropDown(7);\"> HDFS Overview</a></li>\n");
      out.write("\t\t\t\t\t<li onmouseout=\"showDropDown(7);\"><a href=\"javascript:Navbar.changeTab('Hadoop','nn_summary');hideDropDown(7);\">NameNode</a></li>\n");
      out.write("\t\t\t\t\t<li onmouseout=\"showDropDown(7);\"><a  href=\"javascript:Navbar.changeTab('Hadoop','dn_summary');hideDropDown(7);\" >DataNode</a></li>\n");
      out.write("\t\t\t\t\t<li onmouseout=\"showDropDown(7);\"><a id=\"Check Point\" href=\"javascript:Navbar.changeTab('System Config','Hadoop', 'JournalNode');hideDropDown(7);\"  >Journal Node</a></li>\n");
      out.write("\t\t\t\t\t<li onmouseout=\"showDropDown(7);\"><a id=\"Check Point\" href=\"javascript:Navbar.changeTab('System Config','Hadoop', 'CheckPointNode','CheckPointNode');hideDropDown(7);\"  >CheckPoint Node</a></li>\n");
      out.write("\t\t\t\t\t<li onmouseout=\"showDropDown(7);\"><a id=\"System Config\" href=\"javascript:Navbar.changeTab('Hadoop','Hadoop', 'system_config_HDFS');hideDropDown(7);\"  >Configure HDFS</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(7);\"><a href=\"javascript:Navbar.changeTab('Hadoop','Hadoop','MapReduce');hideDropDown(7);\"> MapReduce</a>\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li onmouseout=\"showDropDown(7);\"><a href=\"javascript:Navbar.changeTab('Hadoop','Hadoop','MapReduce');hideDropDown(7);\"> MapReduce Overview</a></li>\n");
      out.write("\t\t\t\t\t<li onmouseout=\"showDropDown(7);\"><a href=\"javascript:Navbar.changeTab('Hadoop','Hadoop', 'ResourceManager');hideDropDown(7);\">ResourceManager</a></li>\n");
      out.write("\t\t\t\t\t<li onmouseout=\"showDropDown(7);\"><a href=\"javascript:Navbar.changeTab('Hadoop','Hadoop', 'NodeManager');hideDropDown(7);\">NodeManager</a></li>\n");
      out.write("\t\t\t\t\t<li onmouseout=\"showDropDown(7);\"><a href=\"javascript:Navbar.changeTab('Hadoop','Hadoop','JobBrowser');hideDropDown(7);\">Job Manager</a></li>\n");
      out.write("\t\t\t\t\t<li onmouseout=\"showDropDown(7);\"><a id=\"System Config\" href=\"javascript:Navbar.changeTab('System Config','Hadoop', 'system_config_MR','MapReduce');hideDropDown(7);\"  >Configure MapReduce</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</li>\n");
      out.write("\t\n");
      out.write("\t<li onmouseout=\"showDropDown(9);\" id=\"Users_li\"  style=\"border-right:0px;width: 19.5%;\" class=\"end\">\n");
      out.write("\t\t<a id=\"Users\" href=\"javascript:Navbar.changeTab('Admin','admin');hideDropDown(9);\">Admin</a>\n");
      out.write("\t\t<ul id=\"Admin\">\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(9);\"><a id=\"automateCluster\" href=\"javascript:Navbar.changeTab('Admin','admin');hideDropDown(9);\">Cluster Setup</a></li>\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(9);\"><a id=\"Hosts\" href=\"javascript:Navbar.changeTab('Hosts','admin', 'hosts');hideDropDown(9);\" >Manage Hosts</a></li>\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(9);\"><a id=\"FTP Server\" href=\"javascript:Navbar.changeTab('QueryIO Services','admin', 'queryio_services');hideDropDown(9);\">QueryIO Services</a></li>\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(9);\"><a id=\"BackupAndRecovery\" href=\"javascript:Navbar.changeTab('System Config','admin', 'BackupAndRecovery','BackupAndRecovery');hideDropDown(9);\">Disaster Recovery</a></li>\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(9);\"><a href=\"javascript:Navbar.changeTab('All Reports','admin', 'all_reports');hideDropDown(9);\">System Reports</a></li>\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(9);\"><a id=\"Users\" href=\"javascript:Navbar.changeTab('Users','admin','users');hideDropDown(9);\"  > Users & Groups</a></li>\n");
      out.write("\t\t\t<li onmouseout=\"showDropDown(9);\"><a id=\"Report Schedules\" href=\"javascript:Navbar.changeTab('Report Schedules','admin', 'report_schedules');hideDropDown(9);\" >System Schedules</a></li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</li>\n");
      out.write("\t\n");
      out.write("</ul>\n");
      out.write("\t<span id=\"totaldn\" style=\"display: none\"><span id=\"hostList\" style=\"display: none\">");
      out.print(hostIPList.size() );
      out.write("</span>\n");
      out.write("\t\t\n");
      out.write("\t</span>\n");
      out.write("\t\t<br class=\"clearfix\" />\n");
      out.write("\t\t<script type=\"text/javascript\">\n");
      out.write("\t\tNavbar.setActiveTab();\n");
      out.write("\t\t$(function() {\n");
      out.write("\t\t\t  if ($.browser.msie && $.browser.version.substr(0,1)<7)\n");
      out.write("\t\t\t  {\n");
      out.write("\t\t\t\t$('li').has('ul').mouseover(function(){\n");
      out.write("\t\t\t\t\t$(this).children('ul').show();\n");
      out.write("\t\t\t\t\t}).mouseout(function(){\n");
      out.write("\t\t\t\t\t$(this).children('ul').hide();\n");
      out.write("\t\t\t\t\t})\n");
      out.write("\t\t\t  }\n");
      out.write("\t\t\t});    \n");
      out.write("\t\tvar tdn=$('#totaldn').text();\n");
      out.write("\t\tvar tnn=$('#totalnn').text();\n");
      out.write("\t\tvar thost=$('#hostList').text();\n");
      out.write("\t\t\n");
      out.write("\t\tif(thost == 0) {\n");
      out.write("\t\t\tisFirstTimeCluster = false;\n");
      out.write("\t\t\tNavbar.changeTab('Admin','admin');\n");
      out.write("\t\t\tUtil.deleteAllCookie();\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tif(tdn==1&&tnn==1&&Navbar.selectedTabId=='Admin'&&Navbar.selectedTabName=='admin'&&Navbar.isquickStartOpen){\n");
      out.write("\t\t\tNavbar.isquickStartOpen=false;\n");
      out.write("\t\t\tNavbar.gettingStarted();\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t</script>\n");
      out.write("\t</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
