package com.queryio.demo.mr.report.aos;

public enum JOB_COUNTER {
	RECORD_PARSE_TIME, MAP_CONTEXT_WRITE_TIME, REDUCE_CONTEXT_WRITE_TIME, MAP_TIME, REDUCE_TIME, CONSOLIDATE_TIME, ADDITIONAL_DETAILS_TIME,

	ZERO_BYTES_AND_LATENCY, SKIPPED_LABELS
}