/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2016-09-27 06:10:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Set;
import java.util.ArrayList;
import org.apache.jasper.tagplugins.jstl.core.ForEach;
import java.util.HashMap;
import com.queryio.core.conf.RemoteManager;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	
//String username = request.getRemoteUser();
String username = request.getUserPrincipal().getName();
if (username == null)
{
	System.out.println("username: " + username);
}


      out.write("\n");
      out.write("<!--[if IE]>\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=9\" />\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n");
      out.write("<link rel=\"stylesheet\" href=\"styles/globalforie.css\" type=\"text/css\" />\n");
      out.write("<![endif]-->\n");
      out.write("<![if !IE]>\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write(" <link rel=\"stylesheet\" href=\"styles/global.css\" type=\"text/css\" />\n");
      out.write("<![endif]>\n");
      out.write("<link rel=\"SHORTCUT ICON\" href=\"images/favicon.ico\">\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<title>QueryIO - Hadoop based SQL & Big Data Analytics Solution</title>\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- uncomment it for demo.queryio -->\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"demo.css\" type=\"text/css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"styles/jquery-ui-1.8.20.custom.css\" type=\"text/css\" />\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"scripts/jquery-1.7.2.min.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"scripts/jquery-ui-1.8.20.custom.min.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"demo.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"dwr/engine.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"dwr/util.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"dwr/interface/RemoteManager.js\"></script>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- comment it for demo.queryio -->\n");
      out.write("\t\t<!-- \n");
      out.write("\t\t<script type=\"text/javascript\" src=\"scripts/jquery-1.7.2.min.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"scripts/popup.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"scripts/jquery.alerts.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"scripts/jquery-ui-1.8.20.custom.min.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"scripts/navbar.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"scripts/util.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"scripts/jquery.treeTable.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"scripts/jquery.dataTables.js\"></script>\n");
      out.write("\t\t\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"dwr/engine.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"dwr/util.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"dwr/interface/RemoteManager.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"scripts/js/jquery.ui.datepicker.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"scripts/jquery-ui-timepicker-addon.js\"></script>\n");
      out.write("\t\t<script src=\"scripts/data_migration.js\"></script>\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"styles/jquery-ui-1.8.20.custom.css\" type=\"text/css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"styles/nav_bar.css\" type=\"text/css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"styles/surround_box.css\" type=\"text/css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"styles/tree.css\" type=\"text/css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"styles/jquery.treeTable.css\" type=\"text/css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"styles/lightbox.css\" type=\"text/css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"styles/ui.jqgrid.css\" type=\"text/css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"styles/nd.css\" type=\"text/css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"styles/jquery.alerts.css\" type=\"text/css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"styles/jquery.jqplot.min.css\" type=\"text/css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"styles/jquery.dataTables.css\" type=\"text/css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"styles/jquery-ui-timepicker-addon.css\" type=\"text/css\" />\n");
      out.write("\t\t\n");
      out.write("\t\t -->\n");
      out.write("\t\t<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\t\tcheckUrl();\n");
      out.write("\t\t\n");
      out.write("\t\tfunction  checkUrl()\n");
      out.write("\t\t{\n");
      out.write("\t\t\tvar domain;\n");
      out.write("\t\t\tvar logoutUrl = 'logout.jsp'\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tvar urLength , domainLength;\n");
      out.write("\t\t\tvar index;\n");
      out.write("\t\t\tvar url1 = document.URL;\n");
      out.write("\t\t\turLength = url1.length;\n");
      out.write("\t\t\tdomainLength = url1.indexOf('login');\n");
      out.write("\t\t\tif(domainLength != -1)\n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\tdomain = url1.substring(0 , domainLength);\n");
      out.write("\t\t\t\turl1 = url1.substring(domainLength , urLength);\n");
      out.write("\t\t\t\tif(url1=='login.jsp')\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\tdomain = domain + loginUrl;\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t$(window).bind('hashchange', function() {\n");
      out.write("\t\t checkUrl();\n");
      out.write("\t\t \n");
      out.write("\t\t});\n");
      out.write("\t\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\t\t\t\tfunction showDropDown(index){\n");
      out.write("\t\t\t\t\tvar li = document.getElementById('menu_ul').childNodes;\n");
      out.write("\t\t\t\t\tvar ul = li[index].childNodes;\n");
      out.write("\t\t\t\t\tul[ul.length-2].style.display = '';\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tfunction hideDropDown(index){\n");
      out.write("\t\t\t\t\tvar li = document.getElementById('menu_ul').childNodes;\n");
      out.write("\t\t\t\t\tvar ul = li[index].childNodes;\n");
      out.write("\t\t\t\t\tul[ul.length-2].style.display = 'none';\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\tvar selectedNameNode;\n");
      out.write("\t\t\tvar selectedDataNode;\n");
      out.write("\t\t\tvar selectedNodeTypeForDetailView;\n");
      out.write("\t\t\n");
      out.write("\t\t\tvar treeHidden = false;\n");
      out.write("\t\t\tfunction hideMenu()\n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\tif(treeHidden)\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"services_div\").style.display = \"block\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"service_ref\").style.width = \"85%\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"hideTreeButton\").innerHTML = \"<img src='images/hide_button.png' alt='Hide Menu' title='Hide Menu'/>\";\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\telse\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"services_div\").style.display = \"none\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"service_ref\").style.width = \"100%\";\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"hideTreeButton\").innerHTML = \"<img src='images/reveal_button.png' alt='Show Menu' title='Show Menu'/>\";\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\ttreeHidden = !treeHidden;\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\n");
      out.write("\t\t\tvar serverTime;\n");
      out.write("\t\t\tvar isFirstTime = true;\n");
      out.write("\t\t\tvar LOC_INDEX = {\n");
      out.write("\t\t\t\tready: function() {\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\tfunction showUserName(detailObject)\n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\tif (detailObject != null)\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\tvar user = detailObject.user;\n");
      out.write("\t\t\t\t\tif (user != null)\n");
      out.write("\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"loggedInUser\").firstChild.nodeValue = user.firstName + ' ' + user.lastName;\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"loggedInUserId\").innerHTML=user.id;\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"loggedInUserName\").innerHTML=user.userName;\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\tserverTime = detailObject.time;\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tupdateClock();\n");
      out.write("\t \t\t\t\t\n");
      out.write("\t \t\t\t\tsetInterval('updateClock()', 1000);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t/* RemoteManager.getServerTime(fetchServerTime); */\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tfunction getUserName(currentUser)\n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\tRemoteManager.getCurrentUserDetail(currentUser, showUserName);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t/* function fetchServerTime(time)\n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\tconsole.log(\"fetchServerTime: \" , time);\n");
      out.write(" \t\t\t\tserverTime = time;\n");
      out.write(" \t\t\t\t\n");
      out.write(" \t\t\t\tupdateClock();\n");
      out.write(" \t\t\t\t\n");
      out.write(" \t\t\t\tsetInterval('updateClock()', 1000);\n");
      out.write("\t\t\t} */\n");
      out.write(" \n");
      out.write("\t\t\tfunction updateClock()\n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\tvar currentTime;\n");
      out.write("\t\t\t\tif (isFirstTime)\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\tcurrentTime = new Date(serverTime);\n");
      out.write("\t\t\t\t\tisFirstTime = false;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\telse{\n");
      out.write("\t\t\t\t\tcurrentTime = new Date();\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t  \tdocument.getElementById(\"clock\").firstChild.nodeValue = currentTime;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t</script>\n");
      out.write("\t\t<style type=\"text/css\">\n");
      out.write("\t\t\t.submenu{display: none}\n");
      out.write("\t\t</style>\n");
      out.write("\t\t<style type=\"text/css\">\n");
      out.write("\t\t\t.subcategoryitems{display: none}\n");
      out.write("\t\t</style>\n");
      out.write("\t\t<style type=\"text/css\">\n");
      out.write("\t\t\t.sub2categoryitems{display: none}\n");
      out.write("\t\t</style>\n");
      out.write("\t</head>\n");
      out.write("\t<body class = \"appleGrey\" onload=\"\">\n");
      out.write("\t\t<div id=\"main\">\n");
      out.write("\t\t\t<div id=\"nav_bar\" class=\"nav_bar\">\n");
      out.write("\t\t\t\t<div class=\"nav\">\n");
      out.write("\t\t\t\t\t<p id=\"user_welcome\">\n");
      out.write("\t\t\t\t\t<span id=\"login_info\"><span id=\"clock\">&nbsp;</span>| Hello,<span id=\"loggedInUser\">&nbsp;</span><span id = \"loggedInUserName\" style=\"display: none;\"></span><span id = \"loggedInUserId\" style=\"display: none;\"></span>| <a href=\"javascript:Navbar.helpClicked();\">Help</a> | <a href=\"javascript:Navbar.gettingStarted();\">Quick Start</a> | <a href=\"logout.jsp\">Logout</a></span>\n");
      out.write("\t\t\t\t\t<span id=\"logo\">\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:Navbar.changeTab('Dashboard','dashboard');\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/queryio_logo.png\" style=\"width: 220px;height: 70px;\">\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"surround_box_div\">\n");
      out.write("\t \t\t<div id=\"surround_box\">\n");
      out.write("\t \t\t\t<!-- menu goes here -->\n");
      out.write("\t \t\t\t\n");
      out.write("\t\t\t\t<div id=\"menu_container\" > \t\t\t\n");
      out.write("\t\t\t\t</div>\t\t\t\n");
      out.write("\t \t\t\t\n");
      out.write("\t \t\t\t<!-- menu end here -->\n");
      out.write("\t \t\t\t\n");
      out.write("\t\t\t\t<div id=\"header_row\" style=\"display: none;\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\t\t<div>\n");
      out.write("\t  \t\t\t</div>\n");
      out.write("\t  \t\t\t<!-- <div id=\"main_box\" class=\"main_box\">\n");
      out.write("\t  \t\t\t\t</div>-->\n");
      out.write("\t\t\t\t<div id=\"right_header\" class=\"right_header\" style=\"width: 100%; float: left; \">\n");
      out.write("\t\t\t\t\t<span class=\"right_header_span\" id=\"rhs_header\" style=\"display: none\">Dashboard</span>\n");
      out.write("\t\t\t\t\t<div id=\"pathbar_div\"></div>\n");
      out.write("\t\t\t\t\t<button class=\"button\" id=\"refreshViewButton\" onclick=\"javascript:Navbar.refreshView()\" style=\"float: right;  display: block;height: 94%;margin-bottom: 1px;margin-right: 5px;margin-top: 1px;font-size: 100%;\">Refresh</button>\n");
      out.write("<!-- \t\t\t\t<button id = \"resumeRefresh\" onclick = \"javascript:Navbar.toggleRefresh(true);\" style = \"float: right; margin: 3px 20px; display: none;\">Resume</button>\n");
      out.write("\t\t\t\t\t<button id = \"pauseRefresh\" onclick = \"javascript:Navbar.toggleRefresh(false);\" style = \"float: right; margin: 3px 20px;\">Pause</button>\n");
      out.write("\t\t\t\t\t<span id = \"autoRefreshSpan\" style = \"float: right; margin-top: 3px;\">\n");
      out.write("\t\t\t\t\t\t<label>Auto Refresh Interval </label>\n");
      out.write("\t\t\t\t\t\t<input id = \"refreshTimeout\" onchange = \"javascript:Navbar.setAutoRefreshTimeout();\" type = \"text\" placeholder = \"(in seconds)\" />\n");
      out.write("\t\t\t\t\t</span>  -->\n");
      out.write("\t\t\t\t\t<span id=\"intervalHeader\" style=\"float: right;color: black; font-weight: normal; font-size: 16px; padding: 5px; display: none;\">\n");
      out.write("\t\t\t\t\t\t<span style=\"float: right; margin-right: 10pt;\">\n");
      out.write("\t\t\t\t\t\t\t<select style = \"font-size: 60%; padding: 0px 0px 0px 0px;\" id='chartInterval' onchange=\"javascript:Navbar.changeInterval(this.options[this.selectedIndex].value);\">\n");
      out.write("\t\t\t\t\t\t\t\t<option selected value='onehour'>1 hour</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='oneday'>1 day</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='oneweek'>7 days</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='onemonth'>30 days</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='quarter'>90 days</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='halfyear'>180 days</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option value='oneyear'>360 days</option>\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t<button class=\"button\" type=\"button\" id = \"migrationStatusBtn\" name=\"migrationStatusBtn\" onclick=\"javascript:DB_Config.moveToMigrationStatus();\" style=\"float: right; font-size: 100%; height: 94%; margin-top: 1px; margin-bottom: 1px; margin-right: 5px; display: none;\">Migration Statistics</button>\n");
      out.write("\t\t\t\t\t<span id=\"queryIONameNodeIdSpan\" style=\"float: right;color: black; font-weight: normal;  padding: 5px; display: none;\">\n");
      out.write("\t\t\t\t\t\t<span style=\" margin-right: 10pt;\">\n");
      out.write("\t\t\t\t\t\t\t<span>\tNamespace :\t</span>\n");
      out.write("\t\t\t\t\t\t\t<select id=\"queryIONameNodeId\" style = \"font-size: 100%;padding: 0px 0px 0px 0px;\" onchange=\"javascript:Navbar.changeQueryIONameNodeId(this.options[this.selectedIndex].value);\">\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<div id=\"service_ref\" class=\"right\" style=\"overflow: auto; float: none;\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t  \t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</body>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\tvar queryioUser = \"");
      out.print( request.getUserPrincipal().getName() );
      out.write("\" ;\n");
      out.write("\tgetUserName(queryioUser);\n");
      out.write("\t");
 Object message = request.getSession().getAttribute("message");
		System.out.println("message : " + message);
		boolean promtPassword = message != null ? true : false;
		request.getSession().removeAttribute("message");
	
      out.write("\n");
      out.write("\tNavbar.promptPasswordChange = ");
      out.print( promtPassword );
      out.write("\n");
      out.write("\t/* Remove this later */\n");
      out.write("\t/* Navbar.promptPasswordChange = true; */\n");
      out.write("\t/*  */\n");
      out.write("\tNavbar.ready();\n");
      out.write("\t\tvar lastSelectedId = 'Dashboard';\n");
      out.write("\t\tvar isFirstTimeCluster = true;\n");
      out.write("\t\tvar isFirstTime = true;\n");
      out.write("\t\tvar table_count=0;\n");
      out.write("\t\t$(LOC_INDEX.ready);\n");
      out.write("\t\tString.prototype.trim=function(){return this.replace(/^\\s+|\\s+$/g, '');};\n");
      out.write("\t</script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"scripts/jquery.dataTables.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"scripts/js/jquery.ui.datepicker.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"scripts/jquery-ui-timepicker-addon.js\"></script>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"styles/ui.jqgrid.css\" type=\"text/css\" />\n");
      out.write("\t<link rel=\"stylesheet\" href=\"styles/nd.css\" type=\"text/css\" />\n");
      out.write("\t<link rel=\"stylesheet\" href=\"styles/jquery.jqplot.min.css\" type=\"text/css\" />\n");
      out.write("\t<link rel=\"stylesheet\" href=\"styles/jquery-ui-timepicker-addon.css\" type=\"text/css\" />\n");
      out.write("\t<link rel=\"stylesheet\" href=\"styles/jquery.dataTables.css\" type=\"text/css\" />\n");
      out.write("\t\t\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
