/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2016-09-27 06:09:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.queryio.core.conf.RemoteManager;
import com.queryio.common.EnvironmentalConstants;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");

 	String mess = String.valueOf(request.getSession().getAttribute("message"));
	System.out.println("mess: " + mess);
	
	if (request.getRemoteUser() != null) {
		if(!request.getRemoteUser().equalsIgnoreCase("null"))
			response.sendRedirect("index.jsp");
	} else {
		int userCount = RemoteManager.getUserCount();

		if (userCount == 0) {
			response.sendRedirect("firstUserRegistration.jsp");
		}
	}
 

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"styles/nav_bar.css\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"styles/surround_box.css\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/navbar.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/util.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"scripts/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("<script src=\"scripts/jquery-ui-1.8.20.custom.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--[if IE]>\r\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=9\" />\r\n");
      out.write("\t\t<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"styles/globalforie.css\" type=\"text/css\" />\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("<![if !IE]>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"styles/global.css\" type=\"text/css\" />\r\n");
      out.write("<![endif]>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"SHORTCUT ICON\" href=\"images/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var isLoggedIn = ");
      out.print(request.getUserPrincipal());
      out.write(";\r\n");
      out.write("\r\n");
      out.write("var uri = window.location.href;\r\n");
      out.write("var pattern = new RegExp(\"(/login.jsp)$\");\r\n");
      out.write("if( ! uri.match(pattern)) {\r\n");
      out.write("\tif(isLoggedIn == null) {\r\n");
      out.write("\t\tvar loginLocation = window.location.protocol + \"//\" + window.location.host + \"/queryio/login.jsp\";\r\n");
      out.write("\t\twindow.location = loginLocation;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"main\">\r\n");
      out.write("\t\t<div id=\"nav_bar\" class=\"nav_bar\">\r\n");
      out.write("\t\t\t<div class=\"nav\">\r\n");
      out.write("\t\t\t\t<p id=\"user_welcome\">\r\n");
      out.write("\t\t\t\t\t<span id=\"login_info\"><a\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:Navbar.helpClicked();\">Help</a> | Welcome Guest </span>\r\n");
      out.write("\t\t\t\t\t<span id=\"logo\"> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"javascript:Navbar.changeTab('dashboard');\"><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:Navbar.changeTab('dashboard');\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"images/queryio_logo.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 220px; height: 70px;\"></a></a>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t<span style=\"font-size: 36px; color: #135; padding-left: 40px;\" >Big Data Server</span> -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"surround_box_div\">\r\n");
      out.write("\t\t\t<div id=\"surround_box\">\r\n");
      out.write("\t\t\t\t<span id=\"header_row\"\r\n");
      out.write("\t\t\t\t\tstyle=\"background: -webkit-gradient(linear, 0% 0%, 0% 80%, from(#579), to(#246) ); background-color: #135; color: white;\">\r\n");
      out.write("\t\t\t\t\t<span id=\"header\" class=\"full-height\" style=\"margin-left: 50%\">\r\n");
      out.write("\t\t\t\t\t\tLogin </span>\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t<div></div>\r\n");
      out.write("\t\t\t\t<div id=\"main_box\" class=\"main_box\"\r\n");
      out.write("\t\t\t\t\tstyle=\"border-bottom: 1px solid #DDD\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div id=\"formdiv\" style=\"margin-left: 43%\">\r\n");
      out.write("\t\t\t\t\t");

						String message = String.valueOf(request.getSession().getAttribute("message"));
					
						System.out.println("message: " + message);
					
						if (EnvironmentalConstants.isDemoVersion() && (message != null) && !("null".equalsIgnoreCase(message)))
						/* if (EnvironmentalConstants.isDemoVersion()) */
						{
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<p style=\"font-size: 11px;\" id=\"message\">");
      out.print(message );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<form method=\"post\" id=\"loginForm\" name=\"loginForm\" action=\"j_security_check\" onsubmit=\"return validateAndStoreLoginDetail();\">\r\n");
      out.write("\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr id=\"uname\" style=\"display: block;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\" width: 50px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tUsername \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"text medium\" name=\"j_username\" id=\"j_username\" tabindex=\"1\" style=\"margin-bottom: 5px; width: 130px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr id=\"passwd\" style=\" display: block;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td style=\" width: 50px\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tPassword \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"text medium\" name=\"j_password\" id=\"j_password\" tabindex=\"2\" style=\" width: 130px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr style=\"display: ; text-align: center;\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"2\" style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"button\" name=\"login\" value=\"Login\" tabindex=\"4\" style=\"margin-left: 10%; background: -webkit-gradient(linear, 0% 0%, 0% 80%, from(#579), to(#246) ); color: white; border-radius: 8px; background-color: #135;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (EnvironmentalConstants.isDemoVersion())
									{
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"button\" name=\"NewUser\" value=\"New User\" onclick=\"javascript:redirectToDemo();\" tabindex=\"4\" style=\"margin-left: 5%; background: -webkit-gradient(linear, 0% 0%, 0% 80%, from(#579), to(#246) ); color: white; border-radius: 8px; background-color: #135; padding: 5px 10px 6px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function validateAndStoreLoginDetail()\r\n");
      out.write("{\r\n");
      out.write("\t\t\r\n");
      out.write("\t   if( document.loginForm.j_username.value == \"\" )\r\n");
      out.write("\t   {\r\n");
      out.write("\t   \t document.getElementById(\"message\").text = \"Username was not provided. Please provide a valid username.\";\r\n");
      out.write("\t     document.loginForm.j_username.focus() ;\r\n");
      out.write("\t     return false;\r\n");
      out.write("\t   }\r\n");
      out.write("\t   else{\r\n");
      out.write("\t\t   Util.setCookie(\"queryioUser\",document.loginForm.j_username.value,-1);\r\n");
      out.write("\t\t   Util.setCookie(\"queryioUser\",document.loginForm.j_username.value,100);\r\n");
      out.write("\t   }\r\n");
      out.write("\t   if(document.loginForm.j_password.value == \"\")\r\n");
      out.write("\t   {\r\n");
      out.write("\t\t   document.getElementById(\"message\").text = \"Password was not provided. Please provide a valid password for user.\"\r\n");
      out.write("\t\t   document.loginForm.j_password.focus() ;\r\n");
      out.write("\t     return false;\r\n");
      out.write("\t   }\t\r\n");
      out.write("\t   \r\n");
      out.write("\t   return true;\r\n");
      out.write("\t   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\tfunction redirectToDemo()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t");
 System.out.println("redirectToDemo"); 
      out.write("\r\n");
      out.write("\t\tvar demoLoginLocation = window.location.protocol + \"//\" + window.location.host + \"/queryio/demoUserRegistration.jsp\";\r\n");
      out.write("\t\twindow.location = demoLoginLocation;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
