package com.queryio.common.database;

public interface ColumnConstants {
	String COL_HOST_ID = "ID";
	String COL_HOST_IP = "HOSTIP";
	String COL_HOST_INSTALLDIR = "INSTALLDIR";
	String COL_HOST_STATUS = "STATUS";
	String COL_HOST_RACKNAME = "RACKNAME";
	String COL_HOST_AGENTPORT = "AGENTPORT";
	String COL_HOST_MONITOR = "MONITOR";
	String COL_HOST_IS_WINDOWS = "IS_WINDOWS";

	String COL_NODE_ID = "ID";
	String COL_NODE_NODETYPE = "NODETYPE";
	String COL_NODE_HOSTID = "HOSTID";
	String COL_NODE_STATUS = "STATUS";
	String COL_NODE_JMXPORT = "JMXPORT";
	String COL_NODE_SERVICESTATUS = "SERVICESTATUS";
	String COL_NODE_HIVESERVICESTATUS = "HIVESERVICESTATUS";
	String COL_NODE_MONITOR = "MONITOR";

	String COL_NODERELATIONS_NODEID = "NODEID";
	String COL_NODERELATIONS_NAMENODEID = "NAMENODEID";

	String COL_HASTATUS_ACTIVENODEID = "ACTIVENODEID";
	String COL_HASTATUS_STANDBYNODEID = "STANDBYNODEID";

	String COL_USER_ID = "ID";
	String COL_USER_USERNAME = "USERNAME";
	String COL_USER_FIRSTNAME = "FIRSTNAME";
	String COL_USER_LASTNAME = "LASTNAME";
	String COL_USER_PASSWORD = "PASSWORD";
	String COL_USER_EMAIL = "EMAIL";
	// String COL_USER_MOBILENO = "MOBILENO";

	String COL_USER_ROLES_ROLENAME = "ROLENAME";

	String COL_SYSTEM_ATTRIBUTES_ATTRIBUTENAME = "ATTRIBUTENAME";
	String COL_SYSTEM_ATTRIBUTES_OBJECTNAME = "OBJECTNAME";
	String COL_SYSTEM_ATTRIBUTES_COLUMNNAME = "COLUMNNAME";
	String COL_SYSTEM_ATTRIBUTES_DESCRIPTION = "DESCRIPTION";
	String COL_SYSTEM_ATTRIBUTES_DATATYPE = "DATATYPE";
	String COL_SYSTEM_ATTRIBUTES_GROUPNAME = "GROUPNAME";

	String COL_LIVE_ATTRIBUTES_ATTRIBUTENAME = "ATTRIBUTENAME";
	String COL_LIVE_ATTRIBUTES_OBJECTNAME = "OBJECTNAME";
	String COL_LIVE_ATTRIBUTES_COLUMNNAME = "COLUMNNAME";
	String COL_LIVE_ATTRIBUTES_DESCRIPTION = "DESCRIPTION";
	String COL_LIVE_ATTRIBUTES_DATATYPE = "DATATYPE";

	String COL_MONITORDATA_MONITOR_TIME = "MONITOR_TIME";

	String COL_VOLUMES_NODEID = "NODEID";
	String COL_VOLUMES_DISK = "DISK";
	String COL_VOLUMES_PATH = "PATH";

	String COL_DISKMONITOREDDATA_HOSTID = "HOSTID";
	String COL_DISKMONITOREDDATA_DISKNAME = "DISKNAME";
	String COL_DISKMONITOREDDATA_DSKBYTEREADSPERSEC = "DSKBYTEREADSPERSEC";
	String COL_DISKMONITOREDDATA_DSKBYTEWRITESPERSEC = "DSKBYTEWRITESPERSEC";
	String COL_DISKMONITOREDDATA_DISKHEALTHSTATUS = "DISKHEALTHSTATUS";

	String COL_DISKHEALTHSTATUS = "DISKHEALTHSTATUS";
	String COL_CPUUSAGE = "CPUUSAGE";
	String COL_GC_COUNT = "GCCOUNT";
	String COL_RAMFREE = "RAMFREE";
	String COL_RAMTOTAL = "RAMTOTAL";
	String COL_GC_TIME_MILLIS = "GCTIMEMILLIS";

	String COL_NN_SUMMARYDATA_CAPACITYTOTALGB = "CAPACITYTOTALGB";
	String COL_NN_SUMMARYDATA_CAPACITYUSEDGB = "CAPACITYUSEDGB";
	String COL_NN_SUMMARYDATA_CAPACITYREMAININGGB = "CAPACITYREMAININGGB";
	String COL_NN_SUMMARYDATA_JVMHEAPUSED = "JVMHEAPUSED";
	String COL_NN_SUMMARYDATA_JVMSTARTEDON = "JVMSTARTEDON";
	String COL_NN_SUMMARYDATA_TOTALREQUESTSSERVED = "TOTALREQUESTSSERVED";
	String COL_NN_SUMMARYDATA_TOTALFILESREAD = "TOTALFILESREAD";
	String COL_NN_SUMMARYDATA_TOTALFILESWRITE = "TOTALFILESWRITE";
	String COL_NN_SUMMARYDATA_TOTALFILESAPPENDED = "TOTALFILESAPPENDED";
	String COL_NN_SUMMARYDATA_TOTALFILESRENAMED = "TOTALFILESRENAMED";
	String COL_NN_SUMMARYDATA_TOTALBLOCKSREAD = "TOTALBLOCKSREAD";
	String COL_NN_SUMMARYDATA_TOTALBLOCKSWRITE = "TOTALBLOCKSWRITE";
	String COL_NN_SUMMARYDATA_SAFEMODESTATUS = "SAFEMODESTATUS";
	String COL_NN_SUMMARYDATA_DELETEFILEOPS = "DELETEFILEOPS";
	String COL_NN_SUMMARYDATA_CREATEFILEOPS = "CREATEFILEOPS";
	String COL_NN_SUMMARYDATA_LISTOPS = "LISTOPS";

	// String COL_NN_SUMMARYDATA_CPUUSAGE = "CPUUSAGE";
	// String COL_NN_SUMMARYDATA_RAMFREE = "RAMFREE";
	// String COL_NN_SUMMARYDATA_RAMTOTAL = "RAMTOTAL";
	// String COL_NN_SUMMARYDATA_NETWORK = "NETWORK";
	// String COL_DN_SUMMARYDATA_DISKHEALTHSTATUS = "DISKHEALTHSTATUS";

	String COL_NN_SUMMARYDATA_TOTALFILES = "TOTALFILES";
	String COL_NN_SUMMARYDATA_TOTALBLOCKS = "TOTALBLOCKS";

	String COL_DN_SUMMARYDATA_VOLUMEINFO = "VOLUMEINFO";
	String COL_DN_SUMMARYDATA_BYTESREAD = "BYTESREAD";
	String COL_DN_SUMMARYDATA_BYTESWRITTEN = "BYTESWRITTEN";
	String COL_DN_SUMMARYDATA_JVMHEAPUSED = "JVMHEAPUSED";
	String COL_DN_SUMMARYDATA_JVMSTARTEDON = "JVMSTARTEDON";
	String COL_DN_SUMMARYDATA_TOTALREQUESTSSERVED = "TOTALREQUESTSSERVED";
	String COL_DN_SUMMARYDATA_TOTALFILEREADS = "TOTALFILEREADS";
	String COL_DN_SUMMARYDATA_TOTALFILEWRITES = "TOTALFILEWRITES";
	String COL_DN_SUMMARYDATA_TOTALBLOCKSREAD = "TOTALBLOCKSREAD";
	String COL_DN_SUMMARYDATA_TOTALBLOCKSWRITE = "TOTALBLOCKSWRITE";

	// String COL_DN_SUMMARYDATA_CPUUSAGE = "CPUUSAGE";
	// String COL_DN_SUMMARYDATA_RAMFREE = "RAMFREE";
	// String COL_DN_SUMMARYDATA_RAMTOTAL = "RAMTOTAL";
	// String COL_DN_SUMMARYDATA_NETWORK = "NETWORK";

	String COL_NN_MONITORDATA_REMAINING = "REMAINING";
	String COL_NN_MONITORDATA_DFSUSED = "DFSUSED";
	String COL_NN_MONITORDATA_ADDBLOCKOPS = "ADDBLOCKOPS";
	String COL_NN_MONITORDATA_DELETEFILEOPS = "DELETEFILEOPS";
	String COL_NN_MONITORDATA_CREATEFILEOPS = "CREATEFILEOPS";
	String COL_NN_MONITORDATA_LISTOPS = "LISTOPS";
	String COL_NN_MONITORDATA_FILESREAD = "TOTALFILESREAD";
	String COL_NN_MONITORDATA_FILESWRITE = "TOTALFILESWRITE";
	String COL_NN_MONITORDATA_TOTALFILESAPPENDED = "FILESAPPENDED";
	String COL_NN_MONITORDATA_TOTALFILESRENAMED = "FILESRENAMED";

	String COL_DN_MONITORDATA_BYTESREAD = "BYTESREAD";
	String COL_DN_MONITORDATA_BYTESWRITE = "BYTESWRITTEN";
	String COL_DN_MONITORDATA_BLOCKSREAD = "BLOCKSREAD";
	String COL_DN_MONITORDATA_BLOCKSWRITE = "BLOCKSWRITTEN";
	String COL_DN_MONITORDATA_BLOCKSREPLICATED = "BLOCKSREPLICATED";
	String COL_DN_MONITORDATA_BLOCKSREMOVED = "BLOCKSREMOVED";
	String COL_DN_MONITORDATA_BLOCKSVERIFIED = "BLOCKSVERIFIED";

	String[] nameNodeSummaryColumnNames = { COL_NN_SUMMARYDATA_JVMHEAPUSED, COL_NN_SUMMARYDATA_TOTALBLOCKSREAD,
			COL_NN_SUMMARYDATA_TOTALBLOCKSWRITE };
	String[] nameNodeSummaryColumnDescriptions = { "JVM Heap", "JVM Started On", "Total Blocks Read",
			"Total Blocks Write" };

	String[] allNameNodeSummaryColumnNames = { COL_NN_SUMMARYDATA_JVMHEAPUSED, COL_NN_SUMMARYDATA_TOTALBLOCKSREAD,
			COL_NN_SUMMARYDATA_TOTALBLOCKSWRITE, COL_NN_SUMMARYDATA_TOTALFILESREAD,
			COL_NN_SUMMARYDATA_TOTALFILESWRITE };
	String[] allNameNodeSummaryColumnDescriptions = { "JVM Heap", "JVM Started On", "Total Requests Served",
			"Total Blocks Read", "Total Blocks Write" };

	String[] dataNodeSummaryColumnNames = { COL_DN_SUMMARYDATA_JVMHEAPUSED, COL_DN_SUMMARYDATA_TOTALREQUESTSSERVED,
			COL_DN_SUMMARYDATA_TOTALBLOCKSREAD, COL_DN_SUMMARYDATA_TOTALBLOCKSWRITE };
	String[] dataNodeSummaryColumnDescriptions = { "JVM Heap", "JVM Started On", "Total Requests Served",
			"Total Blocks Read", "Total Blocks Write" };

	String COL_LAST_CONSOLIDATE_LOG_TIME = "LAST_CONSOLIDATE_LOG_TIME";
	String COL_LAST_CONSOLIDATE_LOG_ID = "ID";

	String COL_NW_RECDBYTESPERSEC = "NWRECDBYTESPERSEC";
	String COL_NW_SENTBYTESPERSEC = "NWSENTBYTESPERSEC";

	String COL_NOTIFICATIONSETTINGS_EMAIL_ENABLED = "EMAIL_ENABLED";
	String COL_NOTIFICATIONSETTINGS_EMAIL_SENDERNAME = "EMAIL_SENDERNAME";
	String COL_NOTIFICATIONSETTINGS_EMAIL_SENDERADD = "EMAIL_SENDERADD";
	String COL_NOTIFICATIONSETTINGS_SECUREDPROTOCOL = "SECUREDPROTOCOL";
	String COL_NOTIFICATIONSETTINGS_EMAIL_SMTPSERVER = "EMAIL_SMTPSERVER";
	String COL_NOTIFICATIONSETTINGS_EMAIL_SMTPPORT = "EMAIL_SMTPPORT";
	String COL_NOTIFICATIONSETTINGS_AUTHREQUIRED = "AUTHREQUIRED";
	String COL_NOTIFICATIONSETTINGS_EMAIL_USERNAME = "EMAIL_USERNAME";
	String COL_NOTIFICATIONSETTINGS_EMAIL_PASSWORD = "EMAIL_PASSWORD";
	String COL_NOTIFICATIONSETTINGS_SMS_ENABLED = "SMS_ENABLED";
	String COL_NOTIFICATIONSETTINGS_SMS_NUMBER = "SMS_NUMBER";
	String COL_NOTIFICATIONSETTINGS_SMS_SERIALPORT = "SMS_SERIALPORT";
	String COL_NOTIFICATIONSETTINGS_SMS_MANUFACTURER = "SMS_MANUFACTURER";
	String COL_NOTIFICATIONSETTINGS_SMS_MODEL = "SMS_MODEL";
	String COL_NOTIFICATIONSETTINGS_SMS_SELECTEDMODEL = "SMS_SELECTEDMODEL";
	String COL_NOTIFICATIONSETTINGS_SMS_BAUDRATE = "SMS_BAUDRATE";
	String COL_NOTIFICATIONSETTINGS_LOG_ENABLED = "LOG_ENABLED";
	String COL_NOTIFICATIONSETTINGS_LOG_FILEPATH = "LOG_FILEPATH";

	String COL_HADOOPCONFIG_TYPE = "TYPE";
	String COL_HADOOPCONFIG_HADOOPKEY = "HADOOPKEY";
	String COL_HADOOPCONFIG_DEFAULT_VALUE = "DEFAULT_VALUE";
	String COL_HADOOPCONFIG_DESCRIPTION = "DESCRIPTION";

	String COL_DSK_BYTESREADPERSEC = "DSKBYTEREADSPERSEC";
	String COL_DSK_BYTESWRITEPERSEC = "DSKBYTEWRITESPERSEC";

	// Columns for Rules table
	String COL_RULES_RULEID = "RULEID";
	String COL_RULES_IGNORERULE = "IGNORERULE";
	String COL_RULES_NODEID = "NODEID";
	String COL_RULES_SEVERITY = "SEVERITY";
	String COL_RULES_ALERTRAISEDNOTIFMSG = "ALERTRAISEDNOTIFMSG";
	String COL_RULES_ALERTRAISEDNOTIFSUB = "ALERTRAISEDNOTIFSUB";
	String COL_RULES_ALERTRESETNOTIFMSG = "ALERTRESETNOTIFMSG";
	String COL_RULES_ALERTRESETNOTIFSUB = "ALERTRESETNOTIFSUB";
	String COL_RULES_NOTIFICATIONTYPE = "NOTIFTYPE";

	// Columns for RuleExpressions table
	String COL_RULEEXPRESSIONS_RULEID = "RULEID";
	String COL_RULEEXPRESSIONS_CONDITION = "RULE_CONDITION";
	String COL_RULEEXPRESSIONS_VALUE = "EXPVALUE";
	String COL_RULEEXPRESSIONS_STARTTIME = "STARTTIME";
	String COL_RULEEXPRESSIONS_ENDTIME = "ENDTIME";
	String COL_RULEEXPRESSIONS_DURATION = "DURATION";
	String COL_RULEEXPRESSIONS_ATTRIBUTENAME = "ATTRIBUTENAME";
	String COL_RULEEXPRESSIONS_NODEID = "NODEID";

	// Columns for Alerts table
	String COL_ALERTS_RULEID = "RULEID";
	String COL_ALERTS_NODEID = "NODEID";
	String COL_ALERTS_SEVERITY = "SEVERITY";
	String COL_ALERTS_STARTTIME = "STARTTIME";
	String COL_ALERTS_ENDTIME = "ENDTIME";

	String COL_ALERTATTRIBUTES_RULEID = "RULEID";
	String COL_ALERTATTRIBUTES_NODEID = "NODEID";
	String COL_ALERTATTRIBUTES_ALERTTIME = "ALERTTIME";
	String COL_ALERTATTRIBUTES_ATTRIBUTENAME = "ATTRIBUTENAME";

	// Columns for AttributeState table
	String COL_ATTRIBUTESTATE_STATE = "STATE";
	String COL_ATTRIBUTESTATE_NODEID = "NODEID";
	String COL_ATTRIBUTESTATE_ATTRIBUTENAME = "ATTRIBUTENAME";
	String COL_ATTRIBUTESTATE_STARTTIME = "STARTTIME";
	String COL_ATTRIBUTESTATE_ENDTIME = "ENDTIME";

	// COLUMNS SERVICES
	String COL_HADOOPSERVICES_NODEID = "NODEID";
	String COL_HADOOPSERVICES_TIMEOFCALL = "TIMEOFCALL";
	String COL_HADOOPSERVICES_TYPE = "TYPE";
	String COL_HADOOPSERVICES_OUTPUTFILEPATH = "OUTPUTFILEPATH";
	String COL_HADOOPSERVICES_STATUS = "STATUS";

	// COLUMNS MIGRATIONSTATUS
	String COL_MIGRATIONINFO_ID = "ID";
	String COL_MIGRATIONINFO_NAMENODEID = "NAMENODEID";
	String COL_MIGRATIONINFO_ISIMPORTTYPE = "ISIMPORTTYPE";
	String COL_MIGRATIONINFO_TITLE = "TITLE";
	String COL_MIGRATIONINFO_STARTTIME = "STARTTIME";
	String COL_MIGRATIONINFO_ENDTIME = "ENDTIME";
	String COL_MIGRATIONINFO_DATASTORE = "DATASTORE";
	String COL_MIGRATIONINFO_DESTINATIONPATH = "DESTINATIONPATH";
	String COL_MIGRATIONINFO_SOURCEPATH = "SOURCEPATH";
	String COL_MIGRATIONINFO_STATUS = "STATUS";
	String COL_MIGRATIONINFO_PROGRESS = "PROGRESS";
	String COL_MIGRATIONINFO_ISSECURE = "ISSECURE";
	String COL_MIGRATIONINFO_UNZIP = "UNZIP";
	String COL_MIGRATIONINFO_COMPRESSION_TYPE = "COMPRESSION_TYPE";
	String COL_MIGRATIONINFO_ENCRYPTION_TYPE = "ENCRYPTION_TYPE";

	String[] PERSIST_COLUMN_NAMES = { ColumnConstants.COL_GC_COUNT, ColumnConstants.COL_GC_TIME_MILLIS,
			COL_NN_MONITORDATA_ADDBLOCKOPS, COL_NN_MONITORDATA_CREATEFILEOPS, COL_NN_MONITORDATA_DELETEFILEOPS,
			COL_NN_MONITORDATA_TOTALFILESAPPENDED, COL_NN_MONITORDATA_TOTALFILESRENAMED, COL_NN_MONITORDATA_LISTOPS,
			COL_NN_MONITORDATA_FILESREAD, COL_NN_MONITORDATA_FILESWRITE, COL_DN_MONITORDATA_BLOCKSWRITE,
			COL_DN_MONITORDATA_BLOCKSREAD, COL_DN_MONITORDATA_BLOCKSREPLICATED, COL_DN_MONITORDATA_BLOCKSREMOVED,
			COL_DN_MONITORDATA_BLOCKSVERIFIED, COL_DN_MONITORDATA_BYTESWRITE, COL_DN_MONITORDATA_BYTESREAD, };

	// COL_NN_MONITORDATA_ADDBLOCKOPS, COL_NN_MONITORDATA_CREATEFILEOPS,
	// COL_NN_MONITORDATA_DELETEFILEOPS,
	// COL_NN_MONITORDATA_TOTALFILESAPPENDED,
	// COL_NN_MONITORDATA_TOTALFILESRENAMED, COL_NN_MONITORDATA_LISTOPS,
	// COL_NN_MONITORDATA_FILESREAD, COL_NN_MONITORDATA_FILESWRITE,

	// COL_DN_MONITORDATA_BLOCKSWRITE, COL_DN_MONITORDATA_BLOCKSREAD,
	// COL_DN_MONITORDATA_BLOCKSREPLICATED
	// COL_DN_MONITORDATA_BLOCKSREMOVED, COL_DN_MONITORDATA_BLOCKSVERIFIED
	// COL_DN_MONITORDATA_BYTESWRITE, COL_DN_MONITORDATA_BYTESREAD

	// ADDBLOCKOPS, CREATEFILEOPS, DELETEFILEOPS, FILESAPPENDED, FILESRENAMED,
	// LISTOPS, TOTALFILESREAD, TOTALFILESWRITE
	// BLOCKSWRITTEN, BLOCKSREAD, BLOCKSREPLICATED, BLOCKSREMOVED,
	// BLOCKSVERIFIED, BYTESWRITTEN, BYTESREAD

	String COL_NODESTATUS_NODEID = "NODEID";
	String COL_NODESTATUS_TIME = "TIME";
	String COL_NODESTATUS_STATUS = "STATUS";

	String COL_NODESTATUS_CONSOLIDATEDDATA_ID = "NODEID";
	String COL_NODESTATUS_CONSOLIDATEDDATA_TIME = "TIME";
	String COL_NODESTATUS_CONSOLIDATEDDATA_STATUS = "STATUS";

	String COL_SNAPSHOTS_ID = "ID";
	String COL_SNAPSHOTS_HOSTNAME = "HOSTNAME";
	String COL_SNAPSHOTS_LOCATION = "LOCATION";
	String COL_SNAPSHOTS_STATUS = "STATUS";
	String COL_SNAPSHOTS_TIME = "TIME";

	String COL_BILLING_REPORT_DATA_BILLINGID = "BILLINGID";
	String COL_BILLING_REPORT_DATA_TIMESTAMP = "DATATIMESTAMP";
	String COL_BILLING_REPORT_DATA_USEDSTORAGE = "USEDSTORAGE";
	String COL_BILLING_REPORT_DATA_BYTESREAD = "BYTESREAD";
	String COL_BILLING_REPORT_DATA_BYTESWRITTEN = "BYTESWRITTEN";
	String COL_BILLING_REPORT_DATA_PUTREQUESTS = "PUTREQUESTS";
	String COL_BILLING_REPORT_DATA_GETREQUESTS = "GETREQUESTS";
	String COL_BILLING_REPORT_DATA_LISTREQUESTS = "LISTREQUESTS";
	String COL_BILLING_REPORT_DATA_DELETEREQUESTS = "DELETEREQUESTS";

	String COL_TASKS_ID = "ID";
	String COL_TASKS_TIMESTAMP = "TASK_TIMESTAMP";
	String COL_TASKS_TYPE = "TASK_TYPE";
	String COL_TASKS_BUCKET_NAME = "BUCKET_NAME";
	String COL_TASKS_OBJECT_NAME = "OBJECT_NAME";
	String COL_TASKS_REPLICATION_ATTEMPTS = "REPLICATION_ATTEMPTS";

	String COL_LAST_SYNC_ID = "LAST_SYNC_ID";

	String COL_REPLICATION_CONFIG_REPLICATE = "REPLICATE";

	String COL_REPLICATION_SETTINGS_PRIMARY_NAMENODE_HOST = "PRIMARY_NAMENODE_HOST";
	String COL_REPLICATION_SETTINGS_SECONDARY_NAMENODE_HOST = "SECONDARY_NAMENODE_HOST";
	String COL_REPLICATION_SETTINGS_DELAY = "DELAY";
	String COL_REPLICATION_SETTINGS_BATCH_SIZE = "BATCH_SIZE";
	String COL_REPLICATION_SETTINGS_IS_INITIAL = "IS_INITIAL";
	String COL_REPLICATION_SETTINGS_PRIMARY_NAMENODE_PORT = "PRIMARY_NAMENODE_PORT";
	String COL_REPLICATION_SETTINGS_SECONDARY_NAMENODE_PORT = "SECONDARY_NAMENODE_PORT";

	String COL_BILLING_APPEND_RATE = "RATE";

	String COL_GROUPS_GROUPID = "ID";
	String COL_GROUPS_GROUPNAME = "NAME";

	String COL_USER_GROUPS_USERID = "USERID";
	String COL_USER_GROUPS_GROUPID = "GROUPID";
	String COL_USER_GROUPS_ISDEFAULT = "ISDEFAULT";

	String COL_RESOURCE_MANAGER_APPSSUBMITTED = "APPSSUBMITTED";
	String COL_RESOURCE_MANAGER_APPSRUNNING = "APPSRUNNING";
	String COL_RESOURCE_MANAGER_APPSPENDING = "APPSPENDING";
	String COL_RESOURCE_MANAGER_APPSCOMPLETED = "APPSCOMPLETED";
	String COL_RESOURCE_MANAGER_APPSKILLED = "APPSKILLED";
	String COL_RESOURCE_MANAGER_ALLOCATEDMB = "ALLOCATEDMB";
	String COL_RESOURCE_MANAGER_AVAILABLEMB = "AVAILABLEMB";
	String COL_RESOURCE_MANAGER_PENDINGMB = "PENDINGMB";
	String COL_RESOURCE_MANAGER_RESERVEDMB = "RESERVEDMB";
	String COL_RESOURCE_MANAGER_NUMACTIVENMS = "NUMACTIVENMS";
	String COL_RESOURCE_MANAGER_NUMDECOMMISSIONEDNMS = "NUMDECOMMISSIONEDNMS";
	String COL_RESOURCE_MANAGER_NUMLOSTNMS = "NUMLOSTNMS";
	String COL_RESOURCE_MANAGER_NUMUNHEALTHYNMS = "NUMUNHEALTHYNMS";
	String COL_RESOURCE_MANAGER_NUMREBOOTEDNMS = "NUMREBOOTEDNMS";
	String COL_RESOURCE_MANAGER_CONTAINERSRUNNING = "CONTAINERSRUNNING";

	String COL_NODE_MANAGER_CONTAINERSLAUNCHED = "CONTAINERSLAUNCHED";
	String COL_NODE_MANAGER_CONTAINERSCOMPLETED = "CONTAINERSCOMPLETED";
	String COL_NODE_MANAGER_CONTAINERSFAILED = "CONTAINERSFAILED";
	String COL_NODE_MANAGER_CONTAINERSKILLED = "CONTAINERSKILLED";
	String COL_NODE_MANAGER_CONTAINERSRUNNING = "CONTAINERSRUNNING";
	String COL_NODE_MANAGER_CONTAINERSINITING = "CONTAINERSINITING";

	String COL_MAPREDJOBCONFIG_NAMENODEID = "NAMENODEID";
	String COL_MAPREDJOBCONFIG_RMID = "RMID";
	String COL_MAPREDJOBCONFIG_JOBNAME = "JOBNAME";
	String COL_MAPREDJOBCONFIG_JARFILE = "JARFILE";
	String COL_MAPREDJOBCONFIG_LIBJARS = "LIBJARS";
	String COL_MAPREDJOBCONFIG_FILES = "FILES";
	String COL_MAPREDJOBCONFIG_CLASSNAME = "CLASSNAME";
	String COL_MAPREDJOBCONFIG_ARGUMENTS = "ARGUMENTS";

	String COL_ADHOCJOBCONFIG_NAMENODEID = "NAMENODEID";
	String COL_ADHOCJOBCONFIG_RMID = "RMID";
	String COL_ADHOCJOBCONFIG_JOBNAME = "JOBNAME";
	String COL_ADHOCJOBCONFIG_JARFILE = "JARFILE";
	String COL_ADHOCJOBCONFIG_LIBJARS = "LIBJARS";
	String COL_ADHOCJOBCONFIG_FILES = "FILES";
	String COL_ADHOCJOBCONFIG_CLASSNAME = "CLASSNAME";
	String COL_ADHOCJOBCONFIG_SOURCEPATH = "SOURCEPATH";
	String COL_ADHOCJOBCONFIG_PATHPATTERN = "PATHPATTERN";
	String COL_ADHOCJOBCONFIG_ARGUMENTS = "ARGUMENTS";

	String COL_CHECKPOINTNODES_ID = "ID";
	String COL_CHECKPOINTNODES_HOSTID = "HOSTID";

	String COL_TAGS_ID = "ID";
	String COL_TAGS_NAME = "NAME";

	String COL_TAG_VALUES_FILEPATH = "FILEPATH";
	String COL_TAG_VALUES_ACCESSTIME = "ACCESSTIME";
	String COL_TAG_VALUES_MODIFICATIONTIME = "MODIFICATIONTIME";
	String COL_TAG_VALUES_OWNER = "OWNER";
	String COL_TAG_VALUES_USERGROUP = "USERGROUP";
	String COL_TAG_VALUES_PERMISSION = "PERMISSION";
	String COL_TAG_VALUES_BLOCKSIZE = "BLOCKSIZE";
	String COL_TAG_VALUES_REPLICATION = "REPLICATION";
	String COL_TAG_VALUES_LENGTH = "LEN";
	String COL_TAG_VALUES_BLOCKS = "BLOCKS";

	String COL_FILES_ID = "ID";
	String COL_FILES_PATH = "PATH";

	String COL_DIRECTORIES_ID = "ID";
	String COL_DIRECTORIES_PATH = "PATH";

	String COL_LOOKUP_ID = "ID";
	String COL_LOOKUP_VALUE = "VALUE";

	String COL_CHARTPREFERENCES_PROPERTIES = "PROPERTIES";

	// Columns for new added tables
	String COL_BIGQUERIES_ID = "ID";
	String COL_BIGQUERIES_PROPERTIES = "PROPERTIES";
	String COL_BIGQUERIES_DESCRIPTION = "DESCRIPTION";
	String COL_BIGQUERIES_QUERY_ID = "QUERY_ID";
	String COL_BIGQUERIES_NAMENODEID = "NAMENODEID";
	String COL_BIGQUERIES_USERNAME = "USERNAME";
	String COL_BIGQUERIES_DBNAME = "DBNAME";

	String COL_CHARTS_ID = "ID";
	String COL_CHARTS_PROPERTIES = "PROPERTIES";
	String COL_CHARTS_DESCRIPTION = "DESCRIPTION";
	String COL_CHARTS_QUERY_ID = "QUERY_ID";

	String COL_TABLES_ID = "ID";
	String COL_TABLES_PROPERTIES = "PROPERTIES";
	String COL_TABLES_DESCRIPTION = "DESCRIPTION";
	String COL_TABLES_QUERY_ID = "QUERY_ID";

	String COL_QUERIES_ID = "ID";
	String COL_QUERIES_PROPERTIES = "PROPERTIES";
	String COL_QUERIES_DESCRIPTION = "DESCRIPTION";
	String COL_QUERIES_NAMENODEID = "NAMENODEID";
	String COL_QUERIES_USERNAME = "USERNAME";
	String COL_QUERIES_DBNAME = "DBNAME";

	String COL_QUERYEXECUTION_ID = "EXECUTIONID";
	String COL_QUERYEXECUTION_QUERY_ID = "QUERYID";
	String COL_QUERYEXECUTION_APP_ID = "APPLICATIONID";
	String COL_QUERYEXECUTION_STATUS = "STATUS";
	String COL_QUERYEXECUTION_PATH = "PATH";
	String COL_QUERYEXECUTION_USERNAME = "USERNAME";
	String COL_QUERYEXECUTION_NAMENODEID = "NAMENODEID";

	String COL_DATABASE_CONNNECTION_NAME = "CONNNECTION_NAME";
	String COL_DATABASE_CONNECTION_URL = "CONNECTION_URL";
	String COL_DATABASE_USERNAME = "USERNAME";
	String COL_DATABASE_PASSWORD = "PASSWORD";
	String COL_DATABASE_DRIVER_NAME = "DRIVER_NAME";

	String COL_TAGPARSERS_TAGPARSERID = "TAGPARSERID";
	String COL_TAGPARSERS_TAGPARSERNAME = "TAGPARSERNAME";
	String COL_TAGPARSERS_TAGPARSERDESC = "TAGPARSERDESCRIPTION";
	String COL_TAGPARSERS_TAGPARSERLIB = "TAGPARSERLIB";
	String COL_TAGPARSERS_FILETYPE = "FILETYPE";
	String COL_TAGPARSERS_CLASSNAME = "CLASSNAME";
	String COL_TAGPARSERS_NAMENODEID = "NAMENODEID";
	String COL_TAGPARSERS_ONINGEST = "ONINGEST";
	String COL_TAGPARSERS_ISACTIVE = "ISACTIVE";

	String COL_JOB_MAPPING_JOBNAME = "JOBNAME";
	String COL_JOB_MAPPING_TABLENAME = "TABLENAME";

	String COL_NAMENODE_CUSTOMDB_MAPPING_NAMENODE_ID = "NAMENODEID";
	String COL_NAMENODE_CUSTOMDB_MAPPING_DBNAME = "DBNAME";
	String COL_NAMENODE_CUSTOMDB_MAPPING_ANALYTICS_DBNAME = "ANALYTICSDBNAME";

	String COL_DECOMMISSIONNODES_NODEID = "ID";

	String COL_DB_MIGRATION_STATUS_SOURCEDBNAME = "SOURCEDBNAME";
	String COL_DB_MIGRATION_STATUS_DESTINATIONDBNAME = "DESTINATIONDBNAME";
	String COL_DB_MIGRATION_STATUS_STARTTIME = "STARTTIME";
	String COL_DB_MIGRATION_STATUS_ENDTIME = "ENDTIME";
	String COL_DB_MIGRATION_STATUS_STATUS = "STATUS";
	String COL_DB_MIGRATION_STATUS_PROGRESS = "PROGRESS";
	String COL_DB_MIGRATION_STATUS_ERROR = "ERROR";

	String COL_QUERYIOSERVICES_NODEID = "NODEID";
	String COL_QUERYIOSERVICES_NODETYPE = "NODETYPE";
	String COL_QUERYIOSERVICES_STATUS = "STATUS";

	String STARTTIME = "STARTTIME";
	String ENDTIME = "ENDTIME";
	String STATUS = "STATUS";
	String REASON_FOR_FAILURE = "REASON_FOR_FAILURE";
	String ID = "ID";
	String JOB_NAME = "JOB_NAME";
	String JOB_GROUP = "JOB_GROUP";

	String COL_NN_DB_MIGRATION_STATUS_MIGRATIONID = "MIGRATIONID";
	String COL_NN_DB_MIGRATION_STATUS_NAMENODEID = "NAMENODEID";
	String COL_NN_DB_MIGRATION_STATUS_HOSTID = "HOSTID";
	String COL_NN_DB_MIGRATION_STATUS_DESTPATH = "DESTPATH";
	String COL_NN_DB_MIGRATION_STATUS_DESTDBNAME = "DESTDBNAME";
	String COL_NN_DB_MIGRATION_STATUS_START_TIME = "START_TIME";
	String COL_NN_DB_MIGRATION_STATUS_END_TIME = "END_TIME";
	String COL_NN_DB_MIGRATION_STATUS_STATUS = "STATUS";
	String COL_NN_DB_MIGRATION_STATUS_ERROR = "ERROR";

	String COL_NN_RESTORE_STATUS_RESTOREID = "RESTOREID";
	String COL_NN_RESTORE_STATUS_MIGRATIONID = "MIGRATIONID";
	String COL_NN_RESTORE_STATUS_NAMENODEID = "NAMENODEID";
	String COL_NN_RESTORE_STATUS_START_TIME = "START_TIME";
	String COL_NN_RESTORE_STATUS_END_TIME = "END_TIME";
	String COL_NN_RESTORE_STATUS_STATUS = "STATUS";

	String COL_NN_DB_DIAGNOSIS_STATUS_DIAGNOSISID = "DIAGNOSISID";
	String COL_NN_DB_DIAGNOSIS_STATUS_NAMENODEID = "NAMENODEID";
	String COL_NN_DB_DIAGNOSIS_STATUS_START_TIME = "START_TIME";
	String COL_NN_DB_DIAGNOSIS_STATUS_END_TIME = "END_TIME";
	String COL_NN_DB_DIAGNOSIS_STATUS_STATUS = "STATUS";
	String COL_NN_DB_DIAGNOSIS_STATUS_ERROR = "ERROR";
	String COL_NN_DB_DIAGNOSIS_STATUS_ISREPAIR = "ISREPAIR";

	String COL_ADHOC_QUERY_ADHOCID = "ADHOCID";
	String COL_ADHOC_QUERY_NAMENODEID = "NAMENODEID";
	String COL_ADHOC_QUERY_RMID = "RMID";
	String COL_ADHOC_QUERY_SOURCEPATH = "SOURCEPATH";
	String COL_ADHOC_QUERY_PARSE_RECURSIVE = "PARSERECURSIVE";
	String COL_ADHOC_QUERY_TYPE = "TYPE";
	String COL_ADHOC_QUERY_ADHOC_TABLE_NAME = "ADHOCTABLENAME";
	String COL_ADHOC_QUERY_FILE_PATH_PATTERN = "FILEPATHPATTERN";
	String COL_ADHOC_QUERY_FIELDS = "FIELDS";
	String COL_ADHOC_QUERY_ENCODING = "ENCODING";
	String COL_ADHOC_QUERY_ARGUMENTS = "ARGUMENTS";

	String COL_NS_METADATA_KEY = "KEYPATTERN";
	String COL_NS_METADATA_VALUE = "VALUE";

	String COL_DATA_CONNECTION_ID = "ID";
	String COL_DATA_CONNECTION_TYPE = "DATA_CONNECTION_TYPE";

	String COL_FTP_DATASOURCE_ID = "ID";
	String COL_FTP_DATASOURCE_HOST = "HOST";
	String COL_FTP_DATASOURCE_PORT = "PORT";
	String COL_FTP_DATASOURCE_USERNAME = "USERNAME";
	String COL_FTP_DATASOURCE_PASSWORD = "PASSWORD";

	String COL_SFTP_DATASOURCE_ID = "ID";
	String COL_SFTP_DATASOURCE_HOST = "HOST";
	String COL_SFTP_DATASOURCE_PORT = "PORT";
	String COL_SFTP_DATASOURCE_USERNAME = "USERNAME";
	String COL_SFTP_DATASOURCE_PASSWORD = "PASSWORD";

	String COL_S3_DATASOURCE_ID = "ID";
	String COL_S3_DATASOURCE_ACCESS_KEY = "ACCESSKEY";
	String COL_S3_DATASOURCE_SECERT_ACCESS_KEY = "SECRETACCESSKEY";

	String COL_HTTP_DATASOURCE_ID = "ID";
	String COL_HTTP_DATASOURCE_BASEURL = "BASEURL";
	String COL_HTTP_DATASOURCE_USERNAME = "USERNAME";
	String COL_HTTP_DATASOURCE_PASSWORD = "PASSWORD";

	String COL_EMAIL_DATASOURCE_ID = "ID";
	String COL_EMAIL_DATASOURCE_EMAILADDRESS = "EMAILADDRESS";
	String COL_EMAIL_DATASOURCE_PASSWORD = "PASSWORD";
	String COL_EMAIL_DATASOURCE_MAILSERVERADDRESS = "MAILSERVERADDRESS";
	String COL_EMAIL_DATASOURCE_ACCOUNTNAME = "ACCOUNTNAME";
	String COL_EMAIL_DATASOURCE_PROTOCOL = "PROTOCOL";
	String COL_EMAIL_DATASOURCE_SOCKET = "SOCKET";
	String COL_EMAIL_DATASOURCE_PORT = "PORT";
	String COL_EMAIL_DATASOURCE_CONNECTIONTIMEOUT = "CONNECTIONTIMEOUT";
	String COL_EMAIL_DATASOURCE_READTIMEOUT = "READTIMEOUT";

	String COL_HDFS_DATASOURCE_ID = "ID";
	String COL_HDFS_DATASOURCE_HOST = "HOST";
	String COL_HDFS_DATASOURCE_PORT = "PORT";
	String COL_HDFS_DATASOURCE_GROUP = "GROUPNAME";
	String COL_HDFS_DATASOURCE_USERNAME = "USERNAME";

	String COL_SSH_DATASOURCE_ID = "ID";
	String COL_SSH_DATASOURCE_HOST = "HOST";
	String COL_SSH_DATASOURCE_PORT = "PORT";
	String COL_SSH_DATASOURCE_USERNAME = "USERNAME";
	String COL_SSH_DATASOURCE_PASSWORD = "PASSWORD";
	String COL_SSH_DATASOURCE_KEY = "KEY";

	String COL_DATABASE_DATASOURCE_ID = "ID";
	String COL_DATABASE_DATASOURCE_DRIVER_CLASS = "DRIVERCLASS";
	String COL_DATABASE_DATASOURCE_CONNECTION_URL = "CONNECTIONURL";
	String COL_DATABASE_DATASOURCE_USERNAME = "USERNAME";
	String COL_DATABASE_DATASOURCE_PASSWORD = "PASSWORD";
	String COL_DATABASE_DATASOURCE_DRIVER_JAR = "DATABASEDRIVERJAR";
	String COL_DATABASE_DATASOURCE_MAX_CONNECTIONS = "MAXCONN";
	String COL_DATABASE_DATASOURCE_MAX_IDLE_CONNECTIONS = "MAXIDLECONN";
	String COL_DATABASE_DATASOURCE_MAX_WAITTIME = "WAITTIME";

	String COL_SPREADSHEETS_SHEET_ID = "SHEETID";
	String COL_SPREADSHEETS_PATH = "PATH";
	String COL_SPREADSHEETS_NAMENODEID = "NAMENODEID";

	String COL_HIVETABLES_TABLENAME = "TABLENAME";
	String COL_HIVETABLES_NAMENODEID = "NAMENODEID";
	String COL_HIVETABLES_RMID = "RMID";
	String COL_HIVETABLES_FILE_TYPE = "FILE_TYPE";
	String COL_HIVETABLES_FILE_NAME = "FILE_NAME";

	String COL_CUSTOMTAG_METADATA_ID = "ID";
	String COL_CUSTOMTAG_METADATA_JSON = "JSON";
	String COL_CUSTOMTAG_METADATA_DESC = "DESCRIPTION";
	String COL_CUSTOMTAG_METADATA_IS_ACTIVE = "ISACTIVE";
	String COL_CUSTOMTAG_METADATA_DB_TYPE = "DB_TYPE";
	String COL_CUSTOMTAG_METADATA_FILE_TYPE = "FILE_TYPE";
	String COL_CUSTOMTAG_METADATA_NAMENODE_ID = "NAMENODEID";
	String COL_CUSTOMTAG_METADATA_TABLE_NAME = "TABLE_NAME";
	String COL_CUSTOMTAG_METADATA_TAGGING_SCHEDULE_INFO = "SCHEDULE_INFO";
	String COL_CUSTOMTAG_METADATA_JOB_NAMES = "JOB_NAMES";

}