package com.queryio.common.database;
/*
	Need to rename later and move to a different package.
*/

public interface TableConstants
{
	String TABLE_TASKS = "TASKS";
	String FAILED_TASKS = "FAILED_TASKS";
	String LAST_SYNC = "LAST_SYNC";
	String REPLICATION_CONFIG = "REPLICATION_CONFIG";
	String TABLE_REPLICATION_SETTINGS = "REPLICATION_SETTINGS";

	String TABLE_HOSTS = "HOSTS";
	String TABLE_NODES = "NODES";
	String TABLE_NODERELATIONS = "NODERELATIONS";
	String TABLE_USERS = "USERS";
	String TABLE_USER_ROLES = "USER_ROLES";
	String TABLE_VOLUMES = "VOLUMES";
	String TABLE_DISKMONITOREDDATA = "DISKMONITOREDDATA";
	String TABLE_HADOOPCONFIG = "HADOOPCONFIG";
	String TABLE_HADOOPSERVICES = "HADOOPSERVICES";
	String TABLE_MIGRATIONINFO = "MIGRATIONSTATUS";
	String TABLE_HASTATUS = "HASTATUS";
	String TABLE_TAGPARSERS = "TAGPARSERS";
	
	String TABLE_NAMENODE_SYSTEM_ATTRIBUTES = "NAMENODE_SYSTEM_ATTRIBUTES";
	String TABLE_DATANODE_SYSTEM_ATTRIBUTES = "DATANODE_SYSTEM_ATTRIBUTES";
	String TABLE_HOST_SYSTEM_ATTRIBUTES = "HOST_SYSTEM_ATTRIBUTES";	
	String TABLE_JOBTRACKER_SYSTEM_ATTRIBUTES = "JOBTRACKER_SYSTEM_ATTRIBUTES";
	String TABLE_TASKTRACKER_SYSTEM_ATTRIBUTES = "TASKTRACKER_SYSTEM_ATTRIBUTES";
	
	String TABLE_RESOURCE_MANAGER_SYSTEM_ATTRIBUES = "RESOURCE_MANAGER_SYSTEM_ATTRIBUTES";
	String TABLE_NODE_MANAGER_SYSTEM_ATTRIBUES = "NODE_MANAGER_SYSTEM_ATTRIBUTES";
	
	String TABLE_RESOURCE_MANAGER_LIVE_ATTRIBUTES = "RESOURCE_MANAGER_LIVE_ATTRIBUTES";
	String TABLE_NODE_MANAGER_LIVE_ATTRIBUES = "NODE_MANAGER_LIVE_ATTRIBUTES";
	
	String TABLE_NAMENODE_LIVE_ATTRIBUTES = "NAMENODE_LIVE_ATTRIBUTES";
	String TABLE_DATANODE_LIVE_ATTRIBUTES = "DATANODE_LIVE_ATTRIBUTES";
	String TABLE_HOST_LIVE_ATTRIBUTES = "HOST_LIVE_ATTRIBUTES";
	String TABLE_JOBTRACKER_LIVE_ATTRIBUTES = "JOBTRACKER_LIVE_ATTRIBUTES";
	String TABLE_TASKTRACKER_LIVE_ATTRIBUTES = "TASKTRACKER_LIVE_ATTRIBUTES";
	
	String TABLE_LAST_CONSOLIDATE_LOG = "LAST_CONSOLIDATE_LOG";
	String TABLE_NOTIFICATIONSETTINGS = "NOTIFICATIONSETTINGS"; 
	
	String TABLE_RULES = "RULES";

	// RuleExpressions table
	String TABLE_RULEEXPRESSIONS = "RULEEXPRESSIONS";

	// Alerts table
	String TABLE_ALERTS = "ALERTS";
	
	// AlertAttribute table
	String TABLE_ALERTATTRIBUTES = "ALERTATTRIBUTES";
	
	//AttributeState table
	String TABLE_ATTRIBUTESTATE = "ATTRIBUTESTATE";
	
	String TABLE_NODESTATUS = "NODESTATUS";
	String TABLE_NODESTATUS_CONSOLIDATEDDATA = "NODESTATUS_CONSOLIDATEDDATA";
	
	String TABLE_SNAPSHOTS = "SNAPSHOTS";
	
	String TABLE_BILLING_REPORT_DATA = "BILLING_REPORT_DATA";
	
	String TABLE_FAILED_TASKS = "FAILED_TASKS";
	String TABLE_LAST_SYNC = "LAST_SYNC";
	String TABLE_REPLICATION_CONFIG = "REPLICATION_CONFIG";
	String TABLE_BILLING_CONFIG_DATA = "BILLING_CONFIG_DATA";
	
	String TABLE_GROUPS = "GROUPS";
	String TABLE_USER_GROUPS = "USERGROUPS";
	
	String TABLE_MAPREDJOBCONFIG = "MAPREDJOBCONFIG";
	String TABLE_ADHOCJOBCONFIG = "ADHOCJOBCONFIG";
	
	String TABLE_CHECKPOINTNODES = "CHECKPOINTNODES";
	
	String TABLE_LOOKUP = "LOOKUPTABLE";
	String TABLE_DIRECTORIES = "DIRECTORIES";
	String TABLE_TAGS = "TAGS";
	String TABLE_FILES = "FILES";
	
	String TABLE_BIGQUERIES = "BIGQUERIES";
	
	String TABLE_CHARTPREFERENCES = "CHARTPREFERENCES";
	
	String TABLE_DATABASE = "DATABASE";
	
	String TABLE_JOB_MAPPING = "JOBMAPPING";
	String TABLE_QUERYEXECUTION = "QUERYEXECUTION";
	
	String TABLE_NAMENODE_CUSTOMDB_MAPPING = "NAMENODE_CUSTOMDB_MAPPING";
	
	String TABLE_DECOMMISSIONNODES = "DECOMMISSIONNODES";
	
	String TABLE_DB_MIGRATION_STATUS = "DBMIGRATIONSTATUS";
	
	String TABLE_QUERYIOSERVICES = "QUERYIOSERVICES";
	
	String TABLE_HDFS_METADATA = "HDFS_METADATA";

	String TABLE_TRIGGERED_SCHEDULEJOB_STATE = "TRIGGERED_SCHEDULEJOB_STATE";
	
	String TABLE_NN_DB_MIGRATION_STATUS = "NNDBMIGRATIONSTATUS";
	
	String TABLE_NN_RESTORE_STATUS = "NNRESTORESTATUS";
	
	String TABLE_NN_DB_DIAGNOSIS_STATUS = "NNDBDIAGNOSISSTATUS";
	
	String TABLE_ADHOC_QUERY = "ADHOCQUERY";
	
	String TABLE_NS_METADATA = "NS_METADATA";
	
	//Tables to be excluded from AdhocDB - PostgreSQL.
	String TABLES_TO_BE_EXCLUDED[] = 
	{
		"BUCKETING_COLS",
		"CDS",
		"COLUMNS_OLD",
		"COLUMNS_V2",
		"DATABASE_PARAMS",
		"DBS",
		"DB_PRIVS",
		"GLOBAL_PRIVS",
		"IDXS",
		"INDEX_PARAMS",
		"NUCLEUS_TABLES",
		"PARTITIONS",
		"PARTITION_EVENTS",
		"PARTITION_KEYS",
		"PARTITION_KEY_VALS",
		"PARTITION_PARAMS",
		"PART_COL_PRIVS",
		"PART_PRIVS",
		"ROLES",
		"ROLE_MAP",
		"SDS",
		"SD_PARAMS",
		"SEQUENCE_TABLE",
		"SERDES",
		"SERDE_PARAMS",
		"SKEWED_COL_NAMES",
		"SKEWED_COL_VALUE_LOC_MAP",
		"SKEWED_STRING_LIST",
		"SKEWED_STRING_LIST_VALUES",
		"SKEWED_VALUES",
		"SORT_COLS",
		"TABLE_PARAMS",
		"TBLS",
		"TBL_COL_PRIVS",
		"TBL_PRIVS",
		"TYPES",
		"TYPE_FIELDS",
		"PART_COL_STATS",
		"TAB_COL_STATS",
		"VERSION",
		"func_ru",
		"funcs"
	};
	
	String TABLE_DATA_CONNECTIONS = "DATA_CONNECTIONS";
	String TABLE_FTP_DATASOURCES = "FTP_DATASOURCE";
	String TABLE_SFTP_DATASOURCES = "SFTP_DATASOURCE";
	String TABLE_S3_DATASOURCES = "S3_DATASOURCE";
	String TABLE_HTTP_DATASOURCES = "HTTP_DATASOURCE";
	String TABLE_EMAIL_DATASOURCES = "EMAIL_DATASOURCE";
	String TABLE_HDFS_DATASOURCES = "HDFS_DATASOURCE";
	String TABLE_SSH_DATASOURCES = "SSH_DATASOURCE";
	String TABLE_DATABASE_DATASOURCES = "DATABASE_DATASOURCE";
	
	String TABLE_SPREADSHEETS = "SPREADSHEETS";
	
	String TABLE_HIVETABLE = "HIVETABLES";
	
	String TABLE_CUSTOM_TAG_METADATA = "CUSTOMTAG_METADATA";
}